.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.2 */

dlabel __osContinitialized
    /* C56F0 800EA340 00000000 */ .word 0x00000000
    /* C56F4 800EA344 00000000 */ .word 0x00000000
    /* C56F8 800EA348 00000000 */ .word 0x00000000
    /* C56FC 800EA34C 00000000 */ .word 0x00000000
