.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.2 */

dlabel __osHwIntTable
    /* C6140 800EAD90 00000000 */ .word 0x00000000
    /* C6144 800EAD94 00000000 */ .word 0x00000000
    /* C6148 800EAD98 00000000 */ .word 0x00000000
    /* C614C 800EAD9C 00000000 */ .word 0x00000000
    /* C6150 800EADA0 00000000 */ .word 0x00000000
    /* C6154 800EADA4 00000000 */ .word 0x00000000
    /* C6158 800EADA8 00000000 */ .word 0x00000000
    /* C615C 800EADAC 00000000 */ .word 0x00000000
