.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.2 */

.align 2
dlabel D_800EAFC0
    /* C6370 800EAFC0 */ .asciz "BLOCK : %x CHANGED\n"
    /* 424C4F434B203A202578204348414E4745440A00 */
.align 2

.align 2
dlabel D_800EAFD4
    /* C6384 800EAFD4 */ .asciz "IN EEPROM CASE\n"
    /* 494E20454550524F4D20434153450A00 */
.align 2

.align 2
dlabel D_800EAFE4
    /* C6394 800EAFE4 */ .asciz "SAVING GAME Block: %x\n"
    /* 534156494E472047414D4520426C6F636B3A2025780A0000 */
.align 2

.align 2
dlabel D_800EAFFC
    /* C63AC 800EAFFC */ .asciz "ERRRRRRORRR \n"
    /* 455252525252524F525252200A000000 */
.align 2

.align 2
dlabel D_800EB00C
    /* C63BC 800EB00C */ .asciz "LOADING GAME\n"
    /* 4C4F4144494E472047414D450A000000 */
.align 2

.align 2
dlabel D_800EB01C
    /* C63CC 800EB01C */ .asciz "ERRRRRRORRR  %d\n"
    /* 455252525252524F525252202025640A00000000 */
.align 2

.align 2
dlabel D_800EB030
    /* C63E0 800EB030 */ .asciz "DONE LOAD\n"
    /* 444F4E45204C4F41440A0000 */
.align 2

.align 2
dlabel D_800EB03C
    /* C63EC 800EB03C */ .ascii "\x1B"
                      .ascii "[1m"
                      .ascii "\x1B"
                      .ascii "[7m *** GAME CRASH CONFIRMED!!! *** "
                      .ascii "\x1B"
                      .asciz "[0m\n"
    /* 1B5B316D1B5B376D202A2A2A2047414D4520435241534820434F4E4649524D4544212121202A2A2A201B5B306D0A0000 */
.align 2

.align 2
dlabel D_800EB06C
    /* C641C 800EB06C */ .asciz "Heap memory available on startup: %d\n"
    /* 48656170206D656D6F727920617661696C61626C65206F6E20737461727475703A2025640A000000 */
.align 2

.align 2
dlabel D_800EB094
    /* C6444 800EB094 */ .asciz "GFX Got Reset\n"
    /* 47465820476F742052657365740A0000 */
.align 2

.align 2
dlabel D_800EB0A4
    /* C6454 800EB0A4 */ .asciz "Item: $%x Bank:%x"
    /* 4974656D3A202425782042616E6B3A2578000000 */
.align 2

.align 2
dlabel D_800EB0B8
    /* C6468 800EB0B8 */ .asciz "in LoadBankItem (phear.c)"
    /* 696E204C6F616442616E6B4974656D202870686561722E6329000000 */
.align 2

.align 2
dlabel D_800EB0D4
    /* C6484 800EB0D4 */ .asciz "No mem for Item: $%x Bank:%x"
    /* 4E6F206D656D20666F72204974656D3A202425782042616E6B3A257800000000 */
.align 2

.align 2
dlabel D_800EB0F4
    /* C64A4 800EB0F4 */ .asciz "in LoadBankItem (phear.c)"
    /* 696E204C6F616442616E6B4974656D202870686561722E6329000000 */
.align 2

.align 2
dlabel D_800EB110
    /* C64C0 800EB110 */ .asciz "Bank: %x Item: %x"
    /* 42616E6B3A202578204974656D3A202578000000 */
.align 2

.align 2
dlabel D_800EB124
    /* C64D4 800EB124 */ .asciz "huffman found"
    /* 687566666D616E20666F756E64000000 */
.align 2

.align 2
dlabel D_800EB134
    /* C64E4 800EB134 */ .asciz "No mem for Item: $%x Bank:%x"
    /* 4E6F206D656D20666F72204974656D3A202425782042616E6B3A257800000000 */
.align 2

.align 2
dlabel D_800EB154
    /* C6504 800EB154 */ .asciz "in LoadBankItem (phear.c)"
    /* 696E204C6F616442616E6B4974656D202870686561722E6329000000 */
.align 2

.align 2
dlabel D_800EB170
    /* C6520 800EB170 */ .asciz "Bank: %x Item: %x"
    /* 42616E6B3A202578204974656D3A202578000000 */
.align 2

.align 2
dlabel D_800EB184
    /* C6534 800EB184 */ .asciz "huffman found"
    /* 687566666D616E20666F756E64000000 */
.align 2
.align 2
    /* C6544 800EB194 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* C6548 800EB198 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* C654C 800EB19C */ .asciz ""
    /* 00000000 */
.align 2

.align 2
dlabel D_800EB1A0
    /* C6550 800EB1A0 */ .asciz "Failure initing controllers\n"
    /* 4661696C75726520696E6974696E6720636F6E74726F6C6C6572730A00000000 */
.align 2

.align 2
dlabel D_800EB1C0
    /* C6570 800EB1C0 */ .asciz "BD"
    /* 42440000 */
.align 2

.align 2
dlabel D_800EB1C4
    /* C6574 800EB1C4 */ .asciz "IP8"
    /* 49503800 */
.align 2

.align 2
dlabel D_800EB1C8
    /* C6578 800EB1C8 */ .asciz "IP7"
    /* 49503700 */
.align 2

.align 2
dlabel D_800EB1CC
    /* C657C 800EB1CC */ .asciz "IP6"
    /* 49503600 */
.align 2

.align 2
dlabel D_800EB1D0
    /* C6580 800EB1D0 */ .asciz "IP5"
    /* 49503500 */
.align 2

.align 2
dlabel D_800EB1D4
    /* C6584 800EB1D4 */ .asciz "IP4"
    /* 49503400 */
.align 2

.align 2
dlabel D_800EB1D8
    /* C6588 800EB1D8 */ .asciz "IP3"
    /* 49503300 */
.align 2

.align 2
dlabel D_800EB1DC
    /* C658C 800EB1DC */ .asciz "IP2"
    /* 49503200 */
.align 2

.align 2
dlabel D_800EB1E0
    /* C6590 800EB1E0 */ .asciz "IP1"
    /* 49503100 */
.align 2

.align 2
dlabel D_800EB1E4
    /* C6594 800EB1E4 */ .asciz "Interrupt"
    /* 496E74657272757074000000 */
.align 2

.align 2
dlabel D_800EB1F0
    /* C65A0 800EB1F0 */ .asciz "TLB modification exception"
    /* 544C42206D6F64696669636174696F6E20657863657074696F6E0000 */
.align 2

.align 2
dlabel D_800EB20C
    /* C65BC 800EB20C */ .asciz "TLB load or instruction fetch"
    /* 544C42206C6F6164206F7220696E737472756374696F6E206665746368000000 */
.align 2

.align 2
dlabel D_800EB22C
    /* C65DC 800EB22C */ .asciz "TLB exception on store"
    /* 544C4220657863657074696F6E206F6E2073746F72650000 */
.align 2

.align 2
dlabel D_800EB244
    /* C65F4 800EB244 */ .asciz "Address load or instruction fetch"
    /* 41646472657373206C6F6164206F7220696E737472756374696F6E206665746368000000 */
.align 2

.align 2
dlabel D_800EB268
    /* C6618 800EB268 */ .asciz "Address error on store"
    /* 41646472657373206572726F72206F6E2073746F72650000 */
.align 2

.align 2
dlabel D_800EB280
    /* C6630 800EB280 */ .asciz "Bus error instruction fetch"
    /* 427573206572726F7220696E737472756374696F6E20666574636800 */
.align 2

.align 2
dlabel D_800EB29C
    /* C664C 800EB29C */ .asciz "Bus error data reference"
    /* 427573206572726F722064617461207265666572656E636500000000 */
.align 2

.align 2
dlabel D_800EB2B8
    /* C6668 800EB2B8 */ .asciz "System call exception"
    /* 53797374656D2063616C6C20657863657074696F6E000000 */
.align 2

.align 2
dlabel D_800EB2D0
    /* C6680 800EB2D0 */ .asciz "Breakpoint exception"
    /* 427265616B706F696E7420657863657074696F6E00000000 */
.align 2

.align 2
dlabel D_800EB2E8
    /* C6698 800EB2E8 */ .asciz "Reserved instruction exception"
    /* 526573657276656420696E737472756374696F6E20657863657074696F6E0000 */
.align 2

.align 2
dlabel D_800EB308
    /* C66B8 800EB308 */ .asciz "Coprocessor unusable exception"
    /* 436F70726F636573736F7220756E757361626C6520657863657074696F6E0000 */
.align 2

.align 2
dlabel D_800EB328
    /* C66D8 800EB328 */ .asciz "Arithmetic overflow exception"
    /* 41726974686D65746963206F766572666C6F7720657863657074696F6E000000 */
.align 2

.align 2
dlabel D_800EB348
    /* C66F8 800EB348 */ .asciz "Trap exception"
    /* 5472617020657863657074696F6E0000 */
.align 2

.align 2
dlabel D_800EB358
    /* C6708 800EB358 */ .asciz "Virtual coherency intruction fetch"
    /* 5669727475616C20636F686572656E637920696E7472756374696F6E2066657463680000 */
.align 2

.align 2
dlabel D_800EB37C
    /* C672C 800EB37C */ .asciz "Floating point (see fpcsr)"
    /* 466C6F6174696E6720706F696E742028736565206670637372290000 */
.align 2

.align 2
dlabel D_800EB398
    /* C6748 800EB398 */ .asciz "Watchpoint exception"
    /* 5761746368706F696E7420657863657074696F6E00000000 */
.align 2

.align 2
dlabel D_800EB3B0
    /* C6760 800EB3B0 */ .asciz "Virtual coherency data reference"
    /* 5669727475616C20636F686572656E63792064617461207265666572656E636500000000 */
.align 2

dlabel D_800EB3D4
    /* C6784 800EB3D4 00000000 */ .word 0x00000000

.align 2
dlabel D_800EB3D8
    /* C6788 800EB3D8 */ .asciz "CU3"
    /* 43553300 */
.align 2

.align 2
dlabel D_800EB3DC
    /* C678C 800EB3DC */ .asciz "CU2"
    /* 43553200 */
.align 2

.align 2
dlabel D_800EB3E0
    /* C6790 800EB3E0 */ .asciz "CU1"
    /* 43553100 */
.align 2

.align 2
dlabel D_800EB3E4
    /* C6794 800EB3E4 */ .asciz "CU0"
    /* 43553000 */
.align 2

.align 2
dlabel D_800EB3E8
    /* C6798 800EB3E8 */ .asciz "RP"
    /* 52500000 */
.align 2

.align 2
dlabel D_800EB3EC
    /* C679C 800EB3EC */ .asciz "FR"
    /* 46520000 */
.align 2

.align 2
dlabel D_800EB3F0
    /* C67A0 800EB3F0 */ .asciz "RE"
    /* 52450000 */
.align 2

.align 2
dlabel D_800EB3F4
    /* C67A4 800EB3F4 */ .asciz "BEV"
    /* 42455600 */
.align 2

.align 2
dlabel D_800EB3F8
    /* C67A8 800EB3F8 */ .asciz "TS"
    /* 54530000 */
.align 2

.align 2
dlabel D_800EB3FC
    /* C67AC 800EB3FC */ .asciz "SR"
    /* 53520000 */
.align 2

.align 2
dlabel D_800EB400
    /* C67B0 800EB400 */ .asciz "CH"
    /* 43480000 */
.align 2

.align 2
dlabel D_800EB404
    /* C67B4 800EB404 */ .asciz "CE"
    /* 43450000 */
.align 2

.align 2
dlabel D_800EB408
    /* C67B8 800EB408 */ .asciz "DE"
    /* 44450000 */
.align 2

.align 2
dlabel D_800EB40C
    /* C67BC 800EB40C */ .asciz "IM8"
    /* 494D3800 */
.align 2

.align 2
dlabel D_800EB410
    /* C67C0 800EB410 */ .asciz "IM7"
    /* 494D3700 */
.align 2

.align 2
dlabel D_800EB414
    /* C67C4 800EB414 */ .asciz "IM6"
    /* 494D3600 */
.align 2

.align 2
dlabel D_800EB418
    /* C67C8 800EB418 */ .asciz "IM5"
    /* 494D3500 */
.align 2

.align 2
dlabel D_800EB41C
    /* C67CC 800EB41C */ .asciz "IM4"
    /* 494D3400 */
.align 2

.align 2
dlabel D_800EB420
    /* C67D0 800EB420 */ .asciz "IM3"
    /* 494D3300 */
.align 2

.align 2
dlabel D_800EB424
    /* C67D4 800EB424 */ .asciz "IM2"
    /* 494D3200 */
.align 2

.align 2
dlabel D_800EB428
    /* C67D8 800EB428 */ .asciz "IM1"
    /* 494D3100 */
.align 2

.align 2
dlabel D_800EB42C
    /* C67DC 800EB42C */ .asciz "KX"
    /* 4B580000 */
.align 2

.align 2
dlabel D_800EB430
    /* C67E0 800EB430 */ .asciz "SX"
    /* 53580000 */
.align 2

.align 2
dlabel D_800EB434
    /* C67E4 800EB434 */ .asciz "UX"
    /* 55580000 */
.align 2

.align 2
dlabel D_800EB438
    /* C67E8 800EB438 */ .asciz "USR"
    /* 55535200 */
.align 2

.align 2
dlabel D_800EB43C
    /* C67EC 800EB43C */ .asciz "SUP"
    /* 53555000 */
.align 2

.align 2
dlabel D_800EB440
    /* C67F0 800EB440 */ .asciz "KER"
    /* 4B455200 */
.align 2

.align 2
dlabel D_800EB444
    /* C67F4 800EB444 */ .asciz "ERL"
    /* 45524C00 */
.align 2

.align 2
dlabel D_800EB448
    /* C67F8 800EB448 */ .asciz "EXL"
    /* 45584C00 */
.align 2

.align 2
dlabel D_800EB44C
    /* C67FC 800EB44C */ .asciz "IE"
    /* 49450000 */
.align 2

dlabel D_800EB450
    /* C6800 800EB450 00000000 */ .word 0x00000000

.align 2
dlabel D_800EB454
    /* C6804 800EB454 */ .asciz "FS"
    /* 46530000 */
.align 2

.align 2
dlabel D_800EB458
    /* C6808 800EB458 */ .asciz "C"
    /* 43000000 */
.align 2

.align 2
dlabel D_800EB45C
    /* C680C 800EB45C */ .asciz "Unimplemented operation"
    /* 556E696D706C656D656E746564206F7065726174696F6E00 */
.align 2

.align 2
dlabel D_800EB474
    /* C6824 800EB474 */ .asciz "Invalid operation"
    /* 496E76616C6964206F7065726174696F6E000000 */
.align 2

.align 2
dlabel D_800EB488
    /* C6838 800EB488 */ .asciz "Division by zero"
    /* 4469766973696F6E206279207A65726F00000000 */
.align 2

.align 2
dlabel D_800EB49C
    /* C684C 800EB49C */ .asciz "Overflow"
    /* 4F766572666C6F7700000000 */
.align 2

.align 2
dlabel D_800EB4A8
    /* C6858 800EB4A8 */ .asciz "Underflow"
    /* 556E646572666C6F77000000 */
.align 2

.align 2
dlabel D_800EB4B4
    /* C6864 800EB4B4 */ .asciz "Inexact operation"
    /* 496E6578616374206F7065726174696F6E000000 */
.align 2

.align 2
dlabel D_800EB4C8
    /* C6878 800EB4C8 */ .asciz "EV"
    /* 45560000 */
.align 2

.align 2
dlabel D_800EB4CC
    /* C687C 800EB4CC */ .asciz "EZ"
    /* 455A0000 */
.align 2

.align 2
dlabel D_800EB4D0
    /* C6880 800EB4D0 */ .asciz "EO"
    /* 454F0000 */
.align 2

.align 2
dlabel D_800EB4D4
    /* C6884 800EB4D4 */ .asciz "EU"
    /* 45550000 */
.align 2

.align 2
dlabel D_800EB4D8
    /* C6888 800EB4D8 */ .asciz "EI"
    /* 45490000 */
.align 2

.align 2
dlabel D_800EB4DC
    /* C688C 800EB4DC */ .asciz "FV"
    /* 46560000 */
.align 2

.align 2
dlabel D_800EB4E0
    /* C6890 800EB4E0 */ .asciz "FZ"
    /* 465A0000 */
.align 2

.align 2
dlabel D_800EB4E4
    /* C6894 800EB4E4 */ .asciz "FO"
    /* 464F0000 */
.align 2

.align 2
dlabel D_800EB4E8
    /* C6898 800EB4E8 */ .asciz "FU"
    /* 46550000 */
.align 2

.align 2
dlabel D_800EB4EC
    /* C689C 800EB4EC */ .asciz "FI"
    /* 46490000 */
.align 2

.align 2
dlabel D_800EB4F0
    /* C68A0 800EB4F0 */ .asciz "RN"
    /* 524E0000 */
.align 2

.align 2
dlabel D_800EB4F4
    /* C68A4 800EB4F4 */ .asciz "RZ"
    /* 525A0000 */
.align 2

.align 2
dlabel D_800EB4F8
    /* C68A8 800EB4F8 */ .asciz "RP"
    /* 52500000 */
.align 2

.align 2
dlabel D_800EB4FC
    /* C68AC 800EB4FC */ .asciz "RM"
    /* 524D0000 */
.align 2

dlabel D_800EB500
    /* C68B0 800EB500 00000000 */ .word 0x00000000

.align 2
dlabel D_800EB504
    /* C68B4 800EB504 */ .asciz "%s\n%s\n"
    /* 25730A25730A0000 */
.align 2

.align 2
dlabel D_800EB50C
    /* C68BC 800EB50C */ .asciz "Reason: %s\n Routine: %s\n String: %s\n"
    /* 526561736F6E3A2025730A20526F7574696E653A2025730A20537472696E673A2025730A00000000 */
.align 2

.align 2
dlabel D_800EB534
    /* C68E4 800EB534 */ .asciz "My God, That Musta Hurt!   Memory available: %d\n"
    /* 4D7920476F642C2054686174204D757374612048757274212020204D656D6F727920617661696C61626C653A2025640A00000000 */
.align 2

.align 2
dlabel D_800EB568
    /* C6918 800EB568 */ .asciz "\nFault in thread %d:\n\n"
    /* 0A4661756C7420696E207468726561642025643A0A0A0000 */
.align 2

.align 2
dlabel D_800EB580
    /* C6930 800EB580 */ .asciz "epc\t\t0x%08x\n"
    /* 65706309093078253038780A00000000 */
.align 2

.align 2
dlabel D_800EB590
    /* C6940 800EB590 */ .asciz "cause"
    /* 6361757365000000 */
.align 2

.align 2
dlabel D_800EB598
    /* C6948 800EB598 */ .asciz "sr"
    /* 73720000 */
.align 2

.align 2
dlabel D_800EB59C
    /* C694C 800EB59C */ .asciz "badvaddr\t0x%08x\n\n"
    /* 6261647661646472093078253038780A0A000000 */
.align 2

.align 2
dlabel D_800EB5B0
    /* C6960 800EB5B0 */ .asciz "at 0x%016llx v0 0x%016llx v1 0x%016llx\n"
    /* 6174203078253031366C6C78207630203078253031366C6C78207631203078253031366C6C780A00 */
.align 2

.align 2
dlabel D_800EB5D8
    /* C6988 800EB5D8 */ .asciz "a0 0x%016llx a1 0x%016llx a2 0x%016llx\n"
    /* 6130203078253031366C6C78206131203078253031366C6C78206132203078253031366C6C780A00 */
.align 2

.align 2
dlabel D_800EB600
    /* C69B0 800EB600 */ .asciz "a3 0x%016llx t0 0x%016llx t1 0x%016llx\n"
    /* 6133203078253031366C6C78207430203078253031366C6C78207431203078253031366C6C780A00 */
.align 2

.align 2
dlabel D_800EB628
    /* C69D8 800EB628 */ .asciz "t2 0x%016llx t3 0x%016llx t4 0x%016llx\n"
    /* 7432203078253031366C6C78207433203078253031366C6C78207434203078253031366C6C780A00 */
.align 2

.align 2
dlabel D_800EB650
    /* C6A00 800EB650 */ .asciz "t5 0x%016llx t6 0x%016llx t7 0x%016llx\n"
    /* 7435203078253031366C6C78207436203078253031366C6C78207437203078253031366C6C780A00 */
.align 2

.align 2
dlabel D_800EB678
    /* C6A28 800EB678 */ .asciz "s0 0x%016llx s1 0x%016llx s2 0x%016llx\n"
    /* 7330203078253031366C6C78207331203078253031366C6C78207332203078253031366C6C780A00 */
.align 2

.align 2
dlabel D_800EB6A0
    /* C6A50 800EB6A0 */ .asciz "s3 0x%016llx s4 0x%016llx s5 0x%016llx\n"
    /* 7333203078253031366C6C78207334203078253031366C6C78207335203078253031366C6C780A00 */
.align 2

.align 2
dlabel D_800EB6C8
    /* C6A78 800EB6C8 */ .asciz "s6 0x%016llx s7 0x%016llx t8 0x%016llx\n"
    /* 7336203078253031366C6C78207337203078253031366C6C78207438203078253031366C6C780A00 */
.align 2

.align 2
dlabel D_800EB6F0
    /* C6AA0 800EB6F0 */ .asciz "t9 0x%016llx gp 0x%016llx sp 0x%016llx\n"
    /* 7439203078253031366C6C78206770203078253031366C6C78207370203078253031366C6C780A00 */
.align 2

.align 2
dlabel D_800EB718
    /* C6AC8 800EB718 */ .asciz "s8 0x%016llx ra 0x%016llx\n\n"
    /* 7338203078253031366C6C78207261203078253031366C6C780A0A00 */
.align 2

.align 2
dlabel D_800EB734
    /* C6AE4 800EB734 */ .asciz "fpcsr"
    /* 6670637372000000 */
.align 2

.align 2
dlabel D_800EB73C
    /* C6AEC 800EB73C */ .asciz "fault: thread "
    /* 6661756C743A20746872656164200000 */
.align 2

.align 2
dlabel D_800EB74C
    /* C6AFC 800EB74C */ .asciz "%d"
    /* 25640000 */
.align 2

.align 2
dlabel D_800EB750
    /* C6B00 800EB750 */ .asciz "epc: $%08x\n"
    /* 6570633A2024253038780A00 */
.align 2

.align 2
dlabel D_800EB75C
    /* C6B0C 800EB75C */ .asciz "ra: $%08x   sp: $%08x\n"
    /* 72613A20242530387820202073703A2024253038780A0000 */
.align 2

.align 2
dlabel D_800EB774
    /* C6B24 800EB774 */ .asciz "fault: thread "
    /* 6661756C743A20746872656164200000 */
.align 2

.align 2
dlabel D_800EB784
    /* C6B34 800EB784 */ .asciz "%d"
    /* 25640000 */
.align 2

.align 2
dlabel D_800EB788
    /* C6B38 800EB788 */ .asciz "epc: $%08x\n"
    /* 6570633A2024253038780A00 */
.align 2

.align 2
dlabel D_800EB794
    /* C6B44 800EB794 */ .asciz "ra: $%08x\n"
    /* 72613A2024253038780A0000 */
.align 2

.align 2
dlabel D_800EB7A0
    /* C6B50 800EB7A0 */ .asciz "sp: $%08x\n"
    /* 73703A2024253038780A0000 */
.align 2

.align 2
dlabel D_800EB7AC
    /* C6B5C 800EB7AC */ .asciz "            stack dump\n"
    /* 202020202020202020202020737461636B2064756D700A00 */
.align 2

.align 2
dlabel D_800EB7C4
    /* C6B74 800EB7C4 */ .asciz "$00: %08x %08x %08x\n"
    /* 2430303A2025303878202530387820253038780A00000000 */
.align 2

.align 2
dlabel D_800EB7DC
    /* C6B8C 800EB7DC */ .asciz "$03: %08x %08x %08x\n"
    /* 2430333A2025303878202530387820253038780A00000000 */
.align 2

.align 2
dlabel D_800EB7F4
    /* C6BA4 800EB7F4 */ .asciz "$06: %08x %08x %08x\n"
    /* 2430363A2025303878202530387820253038780A00000000 */
.align 2

.align 2
dlabel D_800EB80C
    /* C6BBC 800EB80C */ .asciz "$09: %08x %08x %08x\n"
    /* 2430393A2025303878202530387820253038780A00000000 */
.align 2

.align 2
dlabel D_800EB824
    /* C6BD4 800EB824 */ .asciz "$0c: %08x %08x %08x\n"
    /* 2430633A2025303878202530387820253038780A00000000 */
.align 2

.align 2
dlabel D_800EB83C
    /* C6BEC 800EB83C */ .asciz "$0f: %08x %08x %08x\n"
    /* 2430663A2025303878202530387820253038780A00000000 */
.align 2

.align 2
dlabel D_800EB854
    /* C6C04 800EB854 */ .asciz "$12: %08x %08x %08x\n"
    /* 2431323A2025303878202530387820253038780A00000000 */
.align 2

.align 2
dlabel D_800EB86C
    /* C6C1C 800EB86C */ .asciz "$15: %08x %08x %08x\n"
    /* 2431353A2025303878202530387820253038780A00000000 */
.align 2

.align 2
dlabel D_800EB884
    /* C6C34 800EB884 */ .asciz "$18: %08x %08x %08x\n"
    /* 2431383A2025303878202530387820253038780A00000000 */
.align 2

.align 2
dlabel D_800EB89C
    /* C6C4C 800EB89C */ .asciz "$1b: %08x %08x %08x\n"
    /* 2431623A2025303878202530387820253038780A00000000 */
.align 2

.align 2
dlabel D_800EB8B4
    /* C6C64 800EB8B4 */ .asciz "$1e: %08x %08x %08x\n"
    /* 2431653A2025303878202530387820253038780A00000000 */
.align 2

.align 2
dlabel D_800EB8CC
    /* C6C7C 800EB8CC */ .asciz "$21: %08x %08x %08x\n"
    /* 2432313A2025303878202530387820253038780A00000000 */
.align 2

.align 2
dlabel D_800EB8E4
    /* C6C94 800EB8E4 */ .asciz "$24: %08x %08x %08x\n"
    /* 2432343A2025303878202530387820253038780A00000000 */
.align 2

.align 2
dlabel D_800EB8FC
    /* C6CAC 800EB8FC */ .asciz "           register dump\n"
    /* 202020202020202020202072656769737465722064756D700A000000 */
.align 2

.align 2
dlabel D_800EB918
    /* C6CC8 800EB918 */ .asciz "   at: $%08x v0: $%08x\n"
    /* 20202061743A2024253038782076303A2024253038780A00 */
.align 2

.align 2
dlabel D_800EB930
    /* C6CE0 800EB930 */ .asciz "   v1: $%08x a0: $%08x\n"
    /* 20202076313A2024253038782061303A2024253038780A00 */
.align 2

.align 2
dlabel D_800EB948
    /* C6CF8 800EB948 */ .asciz "   a1: $%08x a2: $%08x\n"
    /* 20202061313A2024253038782061323A2024253038780A00 */
.align 2

.align 2
dlabel D_800EB960
    /* C6D10 800EB960 */ .asciz "   a3: $%08x t0: $%08x\n"
    /* 20202061333A2024253038782074303A2024253038780A00 */
.align 2

.align 2
dlabel D_800EB978
    /* C6D28 800EB978 */ .asciz "   t1: $%08x t2: $%08x\n"
    /* 20202074313A2024253038782074323A2024253038780A00 */
.align 2

.align 2
dlabel D_800EB990
    /* C6D40 800EB990 */ .asciz "   t3: $%08x t4: $%08x\n"
    /* 20202074333A2024253038782074343A2024253038780A00 */
.align 2

.align 2
dlabel D_800EB9A8
    /* C6D58 800EB9A8 */ .asciz "   t5: $%08x t6: $%08x\n"
    /* 20202074353A2024253038782074363A2024253038780A00 */
.align 2

.align 2
dlabel D_800EB9C0
    /* C6D70 800EB9C0 */ .asciz "   t7: $%08x t8: $%08x\n"
    /* 20202074373A2024253038782074383A2024253038780A00 */
.align 2

.align 2
dlabel D_800EB9D8
    /* C6D88 800EB9D8 */ .asciz "   s0: $%08x s1: $%08x\n"
    /* 20202073303A2024253038782073313A2024253038780A00 */
.align 2

.align 2
dlabel D_800EB9F0
    /* C6DA0 800EB9F0 */ .asciz "   s2: $%08x s3: $%08x\n"
    /* 20202073323A2024253038782073333A2024253038780A00 */
.align 2

.align 2
dlabel D_800EBA08
    /* C6DB8 800EBA08 */ .asciz "   s4: $%08x s5: $%08x\n"
    /* 20202073343A2024253038782073353A2024253038780A00 */
.align 2

.align 2
dlabel D_800EBA20
    /* C6DD0 800EBA20 */ .asciz "   s6: $%08x s7: $%08x\n"
    /* 20202073363A2024253038782073373A2024253038780A00 */
.align 2

.align 2
dlabel D_800EBA38
    /* C6DE8 800EBA38 */ .asciz "   s8: $%08x gp: $%08x\n"
    /* 20202073383A2024253038782067703A2024253038780A00 */
.align 2

.align 2
dlabel D_800EBA50
    /* C6E00 800EBA50 */ .asciz "%s"
    /* 25730000 */
.align 2

.align 2
dlabel D_800EBA54
    /* C6E04 800EBA54 */ .asciz "%s\n"
    /* 25730A00 */
.align 2

.align 2
dlabel D_800EBA58
    /* C6E08 800EBA58 */ .asciz "%s\t\t0x%08x "
    /* 257309093078253038782000 */
.align 2

.align 2
dlabel D_800EBA64
    /* C6E14 800EBA64 */ .asciz "<"
    /* 3C000000 */
.align 2

.align 2
dlabel D_800EBA68
    /* C6E18 800EBA68 */ .asciz ","
    /* 2C000000 */
.align 2

.align 2
dlabel D_800EBA6C
    /* C6E1C 800EBA6C */ .asciz "%s"
    /* 25730000 */
.align 2

.align 2
dlabel D_800EBA70
    /* C6E20 800EBA70 */ .asciz ">\n"
    /* 3E0A0000 */
.align 2
.align 2
    /* C6E24 800EBA74 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* C6E28 800EBA78 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* C6E2C 800EBA7C */ .asciz ""
    /* 00000000 */
.align 2

.align 2
dlabel D_800EBA80
    /* C6E30 800EBA80 */ .asciz "asked to overwrite animStream"
    /* 61736B656420746F206F766572777269746520616E696D53747265616D000000 */
.align 2

.align 2
dlabel D_800EBAA0
    /* C6E50 800EBAA0 */ .asciz "detected by LWAllocateMemory"
    /* 6465746563746564206279204C57416C6C6F636174654D656D6F727900000000 */
.align 2

.align 2
dlabel D_800EBAC0
    /* C6E70 800EBAC0 */ .asciz "asked to overwrite geomStream"
    /* 61736B656420746F206F76657277726974652067656F6D53747265616D000000 */
.align 2

.align 2
dlabel D_800EBAE0
    /* C6E90 800EBAE0 */ .asciz "detected by LWAllocateMemory"
    /* 6465746563746564206279204C57416C6C6F636174654D656D6F727900000000 */
.align 2

.align 2
dlabel D_800EBB00
    /* C6EB0 800EBB00 */ .asciz "unaligned geomStream"
    /* 756E616C69676E65642067656F6D53747265616D00000000 */
.align 2

.align 2
dlabel D_800EBB18
    /* C6EC8 800EBB18 */ .asciz "detected by LWAllocateMemory"
    /* 6465746563746564206279204C57416C6C6F636174654D656D6F727900000000 */
.align 2

.align 2
dlabel D_800EBB38
    /* C6EE8 800EBB38 */ .asciz "geomStream not valid"
    /* 67656F6D53747265616D206E6F742076616C696400000000 */
.align 2

.align 2
dlabel D_800EBB50
    /* C6F00 800EBB50 */ .asciz "detected by LWAllocateMemory"
    /* 6465746563746564206279204C57416C6C6F636174654D656D6F727900000000 */
.align 2

.align 2
dlabel D_800EBB70
    /* C6F20 800EBB70 */ .asciz "unaligned memory ptr"
    /* 756E616C69676E6564206D656D6F72792070747200000000 */
.align 2

.align 2
dlabel D_800EBB88
    /* C6F38 800EBB88 */ .asciz "detected by LWAllocateMemory"
    /* 6465746563746564206279204C57416C6C6F636174654D656D6F727900000000 */
.align 2

.align 2
dlabel D_800EBBA8
    /* C6F58 800EBBA8 */ .asciz "unaligned animStream"
    /* 756E616C69676E656420616E696D53747265616D00000000 */
.align 2

.align 2
dlabel D_800EBBC0
    /* C6F70 800EBBC0 */ .asciz "detected by LWAllocateMemory"
    /* 6465746563746564206279204C57416C6C6F636174654D656D6F727900000000 */
.align 2

.align 2
dlabel D_800EBBE0
    /* C6F90 800EBBE0 */ .asciz "invalid memory ptr"
    /* 696E76616C6964206D656D6F7279207074720000 */
.align 2

.align 2
dlabel D_800EBBF4
    /* C6FA4 800EBBF4 */ .asciz "detected by LWAllocateMemory"
    /* 6465746563746564206279204C57416C6C6F636174654D656D6F727900000000 */
.align 2

.align 2
dlabel D_800EBC14
    /* C6FC4 800EBC14 */ .asciz "animmStream address not valid"
    /* 616E696D6D53747265616D2061646472657373206E6F742076616C6964000000 */
.align 2

.align 2
dlabel D_800EBC34
    /* C6FE4 800EBC34 */ .asciz "detected by LWAllocateMemory"
    /* 6465746563746564206279204C57416C6C6F636174654D656D6F727900000000 */
.align 2

.align 2
dlabel D_800EBC54
    /* C7004 800EBC54 */ .asciz "memory address bad after alloc"
    /* 6D656D6F727920616464726573732062616420616674657220616C6C6F630000 */
.align 2

.align 2
dlabel D_800EBC74
    /* C7024 800EBC74 */ .asciz "detected by LWAllocateMemory"
    /* 6465746563746564206279204C57416C6C6F636174654D656D6F727900000000 */
.align 2

.align 2
dlabel D_800EBC94
    /* C7044 800EBC94 */ .asciz "LWInfo ptr is invalid"
    /* 4C57496E666F2070747220697320696E76616C6964000000 */
.align 2

.align 2
dlabel D_800EBCAC
    /* C705C 800EBCAC */ .asciz "detected by LWPlayAnimation"
    /* 6465746563746564206279204C57506C6179416E696D6174696F6E00 */
.align 2

.align 2
dlabel D_800EBCC8
    /* C7078 800EBCC8 */ .asciz "geom info ptr is invalid"
    /* 67656F6D20696E666F2070747220697320696E76616C696400000000 */
.align 2

.align 2
dlabel D_800EBCE4
    /* C7094 800EBCE4 */ .asciz "detected by LWPlayAnimation"
    /* 6465746563746564206279204C57506C6179416E696D6174696F6E00 */
.align 2

.align 2
dlabel D_800EBD00
    /* C70B0 800EBD00 */ .asciz "geomstream address is invalid"
    /* 67656F6D73747265616D206164647265737320697320696E76616C6964000000 */
.align 2

.align 2
dlabel D_800EBD20
    /* C70D0 800EBD20 */ .asciz "detected by LWPlayAnimation"
    /* 6465746563746564206279204C57506C6179416E696D6174696F6E00 */
.align 2

.align 2
dlabel D_800EBD3C
    /* C70EC 800EBD3C */ .asciz "animStream address invalid"
    /* 616E696D53747265616D206164647265737320696E76616C69640000 */
.align 2

.align 2
dlabel D_800EBD58
    /* C7108 800EBD58 */ .asciz "detected by LWPlayAnimation"
    /* 6465746563746564206279204C57506C6179416E696D6174696F6E00 */
.align 2

.align 2
dlabel D_800EBD74
    /* C7124 800EBD74 */ .asciz "lights[0] address invalid"
    /* 6C69676874735B305D206164647265737320696E76616C6964000000 */
.align 2

.align 2
dlabel D_800EBD90
    /* C7140 800EBD90 */ .asciz "detected by LWPlayAnimation"
    /* 6465746563746564206279204C57506C6179416E696D6174696F6E00 */
.align 2

.align 2
dlabel D_800EBDAC
    /* C715C 800EBDAC */ .asciz "lights[1] address invalid"
    /* 6C69676874735B315D206164647265737320696E76616C6964000000 */
.align 2

.align 2
dlabel D_800EBDC8
    /* C7178 800EBDC8 */ .asciz "detected by LWPlayAnimation"
    /* 6465746563746564206279204C57506C6179416E696D6174696F6E00 */
.align 2

.align 2
dlabel D_800EBDE4
    /* C7194 800EBDE4 */ .asciz "lightinfo address invalid"
    /* 6C69676874696E666F206164647265737320696E76616C6964000000 */
.align 2

.align 2
dlabel D_800EBE00
    /* C71B0 800EBE00 */ .asciz "detected by LWPlayAnimation"
    /* 6465746563746564206279204C57506C6179416E696D6174696F6E00 */
.align 2

.align 2
dlabel D_800EBE1C
    /* C71CC 800EBE1C */ .asciz "objectinfo address invalid"
    /* 6F626A656374696E666F206164647265737320696E76616C69640000 */
.align 2

.align 2
dlabel D_800EBE38
    /* C71E8 800EBE38 */ .asciz "detected by LWPlayAnimation"
    /* 6465746563746564206279204C57506C6179416E696D6174696F6E00 */
.align 2

.align 2
dlabel D_800EBE54
    /* C7204 800EBE54 */ .asciz "materiallights[0] address invalid"
    /* 6D6174657269616C6C69676874735B305D206164647265737320696E76616C6964000000 */
.align 2

.align 2
dlabel D_800EBE78
    /* C7228 800EBE78 */ .asciz "detected by LWPlayAnimation"
    /* 6465746563746564206279204C57506C6179416E696D6174696F6E00 */
.align 2

.align 2
dlabel D_800EBE94
    /* C7244 800EBE94 */ .asciz "materiallights[1] address invalid"
    /* 6D6174657269616C6C69676874735B315D206164647265737320696E76616C6964000000 */
.align 2

.align 2
dlabel D_800EBEB8
    /* C7268 800EBEB8 */ .asciz "detected by LWPlayAnimation"
    /* 6465746563746564206279204C57506C6179416E696D6174696F6E00 */
.align 2

.align 2
dlabel D_800EBED4
    /* C7284 800EBED4 */ .asciz "CANNOT GET INVERSE\n"
    /* 43414E4E4F542047455420494E56455253450A00 */
.align 2

.align 3
dlabel D_800EBEE8
    /* C7298 800EBEE8 406FE00000000000 */ .double 255
