.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.2 */

.align 2
dlabel D_800F1170
    /* CC520 800F1170 */ .asciz "Jun  6 1997"
    /* 4A756E202036203139393700 */
.align 2
.align 2
    /* CC52C 800F117C */ .asciz "21:45:51"
    /* 32313A34353A353100000000 */
.align 2
.align 2
    /* CC538 800F1188 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* CC53C 800F118C */ .asciz ""
    /* 00000000 */
.align 2
