.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.2 */

dlabel __libm_qnan_f
    /* CC880 800F14D0 7F810000 */ .word 0x7F810000
    /* CC884 800F14D4 00000000 */ .word 0x00000000
    /* CC888 800F14D8 00000000 */ .word 0x00000000
    /* CC88C 800F14DC 00000000 */ .word 0x00000000
