.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.42.2 */

dlabel D_800F2040
    /* 800F2040 */ .space 0x04

dlabel D_800F2044
    /* 800F2044 */ .space 0x04

dlabel D_800F2048
    /* 800F2048 */ .space 0x04

dlabel D_800F204C
    /* 800F204C */ .space 0x04

dlabel D_800F2050
    /* 800F2050 */ .space 0x200

dlabel D_800F2250
    /* 800F2250 */ .space 0x40

dlabel D_800F2290
    /* 800F2290 */ .space 0x08

dlabel D_800F2298
    /* 800F2298 */ .space 0x18

dlabel D_800F22B0
    /* 800F22B0 */ .space 0x04

dlabel D_800F22B4
    /* 800F22B4 */ .space 0x04

dlabel D_800F22B8
    /* 800F22B8 */ .space 0x04

dlabel D_800F22BC
    /* 800F22BC */ .space 0x04

dlabel D_800F22C0
    /* 800F22C0 */ .space 0x04

dlabel D_800F22C4
    /* 800F22C4 */ .space 0x04

dlabel D_800F22C8
    /* 800F22C8 */ .space 0x18

dlabel D_800F22E0
    /* 800F22E0 */ .space 0x20

dlabel D_800F2300
    /* 800F2300 */ .space 0x28

dlabel D_800F2328
    /* 800F2328 */ .space 0x10

dlabel mainThread
    /* 800F2338 */ .space 0x1B0

dlabel idleThread
    /* 800F24E8 */ .space 0x1B0

dlabel schedThread
    /* 800F2698 */ .space 0x21B0

dlabel mainThreadStack
    /* 800F4848 */ .space 0x2000

dlabel idleThreadStack
    /* 800F6848 */ .space 0x2000

dlabel schedThreadStack
    /* 800F8848 */ .space 0x2000

dlabel D_800FA848
    /* 800FA848 */ .space 0x320

dlabel D_800FAB68
    /* 800FAB68 */ .space 0x18

dlabel D_800FAB80
    /* 800FAB80 */ .space 0x18

dlabel D_800FAB98
    /* 800FAB98 */ .space 0x20

dlabel D_800FABB8
    /* 800FABB8 */ .space 0x08

dlabel D_800FABC0
    /* 800FABC0 */ .space 0x04

dlabel D_800FABC4
    /* 800FABC4 */ .space 0x0C

dlabel D_800FABD0
    /* 800FABD0 */ .space 0x40

dlabel D_800FAC10
    /* 800FAC10 */ .space 0x18

dlabel D_800FAC28
    /* 800FAC28 */ .space 0x40

dlabel D_800FAC68
    /* 800FAC68 */ .space 0x58

dlabel D_800FACC0
    /* 800FACC0 */ .space 0x18EC

dlabel D_800FC5AC
    /* 800FC5AC */ .space 0x24

dlabel D_800FC5D0
    /* 800FC5D0 */ .space 0x18F0

dlabel D_800FDEC0
    /* 800FDEC0 */ .space 0x30

dlabel D_800FDEF0
    /* 800FDEF0 */ .space 0x288

dlabel D_800FE178
    /* 800FE178 */ .space 0x08

dlabel D_800FE180
    /* 800FE180 */ .space 0x2000

dlabel D_80100180
    /* 80100180 */ .space 0x08

dlabel D_80100188
    /* 80100188 */ .space 0x04

dlabel D_8010018C
    /* 8010018C */ .space 0x04

dlabel faultThread
    /* 80100190 */ .space 0x1B0

dlabel faultThreadStack
    /* 80100340 */ .space 0x2000

dlabel D_80102340
    /* 80102340 */ .space 0x18

dlabel D_80102358
    /* 80102358 */ .space 0x08

dlabel D_80102360
    /* 80102360 */ .space 0x20

dlabel D_80102380
    /* 80102380 */ .space 0x20

dlabel D_801023A0
    /* 801023A0 */ .space 0x1E0

dlabel D_80102580
    /* 80102580 */ .space 0x03

dlabel D_80102583
    /* 80102583 */ .space 0x0D

dlabel D_80102590
    /* 80102590 */ .space 0x40

dlabel D_801025D0
    /* 801025D0 */ .space 0x04

dlabel D_801025D4
    /* 801025D4 */ .space 0x04

dlabel D_801025D8
    /* 801025D8 */ .space 0x18

dlabel D_801025F0
    /* 801025F0 */ .space 0x58

dlabel D_80102648
    /* 80102648 */ .space 0x08

dlabel D_80102650
    /* 80102650 */ .space 0x14

dlabel D_80102664
    /* 80102664 */ .space 0x02

dlabel D_80102666
    /* 80102666 */ .space 0x0A

dlabel D_80102670
    /* 80102670 */ .space 0x18

dlabel D_80102688
    /* 80102688 */ .space 0x04

dlabel D_8010268C
    /* 8010268C */ .space 0x04

dlabel D_80102690
    /* 80102690 */ .space 0x04

dlabel D_80102694
    /* 80102694 */ .space 0x04

dlabel D_80102698
    /* 80102698 */ .space 0x04

dlabel D_8010269C
    /* 8010269C */ .space 0x04

dlabel D_801026A0
    /* 801026A0 */ .space 0x04

dlabel D_801026A4
    /* 801026A4 */ .space 0x04

dlabel D_801026A8
    /* 801026A8 */ .space 0x04

dlabel D_801026AC
    /* 801026AC */ .space 0x04

dlabel D_801026B0
    /* 801026B0 */ .space 0x08

dlabel D_801026B8
    /* 801026B8 */ .space 0x04

dlabel D_801026BC
    /* 801026BC */ .space 0x04

dlabel D_801026C0
    /* 801026C0 */ .space 0x02

dlabel D_801026C2
    /* 801026C2 */ .space 0x02

dlabel D_801026C4
    /* 801026C4 */ .space 0x04

dlabel D_801026C8
    /* 801026C8 */ .space 0x200

dlabel D_801028C8
    /* 801028C8 */ .space 0x04

dlabel D_801028CC
    /* 801028CC */ .space 0x04

dlabel D_801028D0
    /* 801028D0 */ .space 0x04

dlabel D_801028D4
    /* 801028D4 */ .space 0x04

dlabel D_801028D8
    /* 801028D8 */ .space 0x18

dlabel D_801028F0
    /* 801028F0 */ .space 0x28

dlabel D_80102918
    /* 80102918 */ .space 0x04

dlabel D_8010291C
    /* 8010291C */ .space 0x78

dlabel D_80102994
    /* 80102994 */ .space 0x14

dlabel D_801029A8
    /* 801029A8 */ .space 0x14

dlabel D_801029BC
    /* 801029BC */ .space 0x14

dlabel D_801029D0
    /* 801029D0 */ .space 0x14

dlabel D_801029E4
    /* 801029E4 */ .space 0x02

dlabel D_801029E6
    /* 801029E6 */ .space 0x02

dlabel D_801029E8
    /* 801029E8 */ .space 0x06

dlabel D_801029EE
    /* 801029EE */ .space 0x01

dlabel D_801029EF
    /* 801029EF */ .space 0x01

dlabel D_801029F0
    /* 801029F0 */ .space 0x01

dlabel D_801029F1
    /* 801029F1 */ .space 0x01

dlabel D_801029F2
    /* 801029F2 */ .space 0x01

dlabel D_801029F3
    /* 801029F3 */ .space 0x01

dlabel D_801029F4
    /* 801029F4 */ .space 0x01

dlabel D_801029F5
    /* 801029F5 */ .space 0x01

dlabel D_801029F6
    /* 801029F6 */ .space 0x01

dlabel D_801029F7
    /* 801029F7 */ .space 0x8D

dlabel D_80102A84
    /* 80102A84 */ .space 0x01

dlabel D_80102A85
    /* 80102A85 */ .space 0x01

dlabel D_80102A86
    /* 80102A86 */ .space 0x01

dlabel D_80102A87
    /* 80102A87 */ .space 0x01

dlabel D_80102A88
    /* 80102A88 */ .space 0x24

dlabel D_80102AAC
    /* 80102AAC */ .space 0x08

dlabel D_80102AB4
    /* 80102AB4 */ .space 0x08

dlabel D_80102ABC
    /* 80102ABC */ .space 0x06

dlabel D_80102AC2
    /* 80102AC2 */ .space 0x01

dlabel D_80102AC3
    /* 80102AC3 */ .space 0x01

dlabel D_80102AC4
    /* 80102AC4 */ .space 0x30

dlabel D_80102AF4
    /* 80102AF4 */ .space 0x08

dlabel D_80102AFC
    /* 80102AFC */ .space 0x08

dlabel D_80102B04
    /* 80102B04 */ .space 0x01

dlabel D_80102B05
    /* 80102B05 */ .space 0x01

dlabel D_80102B06
    /* 80102B06 */ .space 0x01

dlabel D_80102B07
    /* 80102B07 */ .space 0x03

dlabel D_80102B0A
    /* 80102B0A */ .space 0x0A

dlabel D_80102B14
    /* 80102B14 */ .space 0x04

dlabel D_80102B18
    /* 80102B18 */ .space 0x04

dlabel D_80102B1C
    /* 80102B1C */ .space 0x04

dlabel D_80102B20
    /* 80102B20 */ .space 0x08

dlabel D_80102B28
    /* 80102B28 */ .space 0x40

dlabel D_80102B68
    /* 80102B68 */ .space 0x40

dlabel D_80102BA8
    /* 80102BA8 */ .space 0x08

dlabel D_80102BB0
    /* 80102BB0 */ .space 0x40

dlabel D_80102BF0
    /* 80102BF0 */ .space 0x08

dlabel D_80102BF8
    /* 80102BF8 */ .space 0x40

dlabel D_80102C38
    /* 80102C38 */ .space 0x08

dlabel D_80102C40
    /* 80102C40 */ .space 0x14

dlabel D_80102C54
    /* 80102C54 */ .space 0x04

dlabel D_80102C58
    /* 80102C58 */ .space 0x04

dlabel D_80102C5C
    /* 80102C5C */ .space 0x04

dlabel D_80102C60
    /* 80102C60 */ .space 0x04

dlabel D_80102C64
    /* 80102C64 */ .space 0x04

dlabel D_80102C68
    /* 80102C68 */ .space 0x04

dlabel D_80102C6C
    /* 80102C6C */ .space 0x04

dlabel D_80102C70
    /* 80102C70 */ .space 0x04

dlabel D_80102C74
    /* 80102C74 */ .space 0x02

dlabel D_80102C76
    /* 80102C76 */ .space 0x02

dlabel D_80102C78
    /* 80102C78 */ .space 0x02

dlabel D_80102C7A
    /* 80102C7A */ .space 0x02

dlabel D_80102C7C
    /* 80102C7C */ .space 0x02

dlabel D_80102C7E
    /* 80102C7E */ .space 0x02

dlabel D_80102C80
    /* 80102C80 */ .space 0x02

dlabel D_80102C82
    /* 80102C82 */ .space 0x02

dlabel D_80102C84
    /* 80102C84 */ .space 0x04

dlabel D_80102C88
    /* 80102C88 */ .space 0x68

dlabel D_80102CF0
    /* 80102CF0 */ .space 0x04

dlabel D_80102CF4
    /* 80102CF4 */ .space 0x04

dlabel D_80102CF8
    /* 80102CF8 */ .space 0x04

dlabel D_80102CFC
    /* 80102CFC */ .space 0x04

dlabel D_80102D00
    /* 80102D00 */ .space 0x08

dlabel D_80102D08
    /* 80102D08 */ .space 0x04

dlabel D_80102D0C
    /* 80102D0C */ .space 0x1C

dlabel D_80102D28
    /* 80102D28 */ .space 0x1C

dlabel D_80102D44
    /* 80102D44 */ .space 0x04

dlabel D_80102D48
    /* 80102D48 */ .space 0x04

dlabel D_80102D4C
    /* 80102D4C */ .space 0x80

dlabel D_80102DCC
    /* 80102DCC */ .space 0x02

dlabel D_80102DCE
    /* 80102DCE */ .space 0x222

dlabel D_80102FF0
    /* 80102FF0 */ .space 0x1F8

dlabel D_801031E8
    /* 801031E8 */ .space 0x1C

dlabel D_80103204
    /* 80103204 */ .space 0x0C

dlabel D_80103210
    /* 80103210 */ .space 0x10

dlabel D_80103220
    /* 80103220 */ .space 0x04

dlabel D_80103224
    /* 80103224 */ .space 0xD0

dlabel D_801032F4
    /* 801032F4 */ .space 0x64

dlabel D_80103358
    /* 80103358 */ .space 0x04

dlabel D_8010335C
    /* 8010335C */ .space 0x04

dlabel D_80103360
    /* 80103360 */ .space 0x04

dlabel D_80103364
    /* 80103364 */ .space 0x10

dlabel D_80103374
    /* 80103374 */ .space 0x14

dlabel D_80103388
    /* 80103388 */ .space 0x1A

dlabel D_801033A2
    /* 801033A2 */ .space 0x08

dlabel D_801033AA
    /* 801033AA */ .space 0x02

dlabel D_801033AC
    /* 801033AC */ .space 0x0C

dlabel D_801033B8
    /* 801033B8 */ .space 0x04

dlabel D_801033BC
    /* 801033BC */ .space 0x10

dlabel D_801033CC
    /* 801033CC */ .space 0x04

dlabel D_801033D0
    /* 801033D0 */ .space 0x04

dlabel D_801033D4
    /* 801033D4 */ .space 0x0C

dlabel D_801033E0
    /* 801033E0 */ .space 0x18

dlabel D_801033F8
    /* 801033F8 */ .space 0x0C

dlabel D_80103404
    /* 80103404 */ .space 0x20

dlabel D_80103424
    /* 80103424 */ .space 0x28

dlabel D_8010344C
    /* 8010344C */ .space 0x04

dlabel D_80103450
    /* 80103450 */ .space 0x04

dlabel D_80103454
    /* 80103454 */ .space 0x07

dlabel D_8010345B
    /* 8010345B */ .space 0x4FD

dlabel D_80103958
    /* 80103958 */ .space 0x04

dlabel D_8010395C
    /* 8010395C */ .space 0x04

dlabel D_80103960
    /* 80103960 */ .space 0x08

dlabel D_80103968
    /* 80103968 */ .space 0x40

dlabel D_801039A8
    /* 801039A8 */ .space 0x02

dlabel D_801039AA
    /* 801039AA */ .space 0x02

dlabel D_801039AC
    /* 801039AC */ .space 0x02

dlabel D_801039AE
    /* 801039AE */ .space 0x02

dlabel D_801039B0
    /* 801039B0 */ .space 0x04

dlabel D_801039B4
    /* 801039B4 */ .space 0x04

dlabel D_801039B8
    /* 801039B8 */ .space 0x04

dlabel D_801039BC
    /* 801039BC */ .space 0x04

dlabel D_801039C0
    /* 801039C0 */ .space 0x08

dlabel D_801039C8
    /* 801039C8 */ .space 0x22

dlabel D_801039EA
    /* 801039EA */ .space 0x02

dlabel D_801039EC
    /* 801039EC */ .space 0x04

dlabel D_801039F0
    /* 801039F0 */ .space 0x04

dlabel D_801039F4
    /* 801039F4 */ .space 0x0C

dlabel D_80103A00
    /* 80103A00 */ .space 0x900

dlabel D_80104300
    /* 80104300 */ .space 0x610

dlabel D_80104910
    /* 80104910 */ .space 0x200

dlabel D_80104B10
    /* 80104B10 */ .space 0x18

dlabel D_80104B28
    /* 80104B28 */ .space 0x20

dlabel D_80104B48
    /* 80104B48 */ .space 0x18

dlabel D_80104B60
    /* 80104B60 */ .space 0x20

dlabel D_80104B80
    /* 80104B80 */ .space 0x38

dlabel D_80104BB8
    /* 80104BB8 */ .space 0x38

dlabel D_80104BF0
    /* 80104BF0 */ .space 0x08

dlabel D_80104BF8
    /* 80104BF8 */ .space 0x10

dlabel D_80104C08
    /* 80104C08 */ .space 0x08

dlabel D_80104C10
    /* 80104C10 */ .space 0xC0

dlabel D_80104CD0
    /* 80104CD0 */ .space 0x08

dlabel D_80104CD8
    /* 80104CD8 */ .space 0x04

dlabel D_80104CDC
    /* 80104CDC */ .space 0x0C

dlabel D_80104CE8
    /* 80104CE8 */ .space 0x1B0

dlabel D_80104E98
    /* 80104E98 */ .space 0x18

dlabel D_80104EB0
    /* 80104EB0 */ .space 0x20

dlabel D_80104ED0
    /* 80104ED0 */ .space 0x18

dlabel D_80104EE8
    /* 80104EE8 */ .space 0x20

dlabel D_80104F08
    /* 80104F08 */ .space 0x44

dlabel D_80104F4C
    /* 80104F4C */ .space 0x200C

dlabel D_80106F58
    /* 80106F58 */ .space 0x0C

dlabel D_80106F64
    /* 80106F64 */ .space 0x04

dlabel D_80106F68
    /* 80106F68 */ .space 0x04

dlabel D_80106F6C
    /* 80106F6C */ .space 0x04

dlabel D_80106F70
    /* 80106F70 */ .space 0x20

dlabel D_80106F90
    /* 80106F90 */ .space 0x18

dlabel D_80106FA8
    /* 80106FA8 */ .space 0x04

dlabel D_80106FAC
    /* 80106FAC */ .space 0x04

dlabel D_80106FB0
    /* 80106FB0 */ .space 0x04

dlabel D_80106FB4
    /* 80106FB4 */ .space 0x2D0

dlabel D_80107284
    /* 80107284 */ .space 0x04

dlabel D_80107288
    /* 80107288 */ .space 0x08

dlabel D_80107290
    /* 80107290 */ .space 0x157C

dlabel D_8010880C
    /* 8010880C */ .space 0x04

dlabel D_80108810
    /* 80108810 */ .space 0x01

dlabel D_80108811
    /* 80108811 */ .space 0x0B

dlabel D_8010881C
    /* 8010881C */ .space 0x04

dlabel D_80108820
    /* 80108820 */ .space 0x05

dlabel D_80108825
    /* 80108825 */ .space 0x03

dlabel D_80108828
    /* 80108828 */ .space 0x157C

dlabel D_80109DA4
    /* 80109DA4 */ .space 0x05

dlabel D_80109DA9
    /* 80109DA9 */ .space 0x09

dlabel D_80109DB2
    /* 80109DB2 */ .space 0x02

dlabel D_80109DB4
    /* 80109DB4 */ .space 0x04

dlabel D_80109DB8
    /* 80109DB8 */ .space 0x04

dlabel D_80109DBC
    /* 80109DBC */ .space 0x04

dlabel D_80109DC0
    /* 80109DC0 */ .space 0x450

dlabel D_8010A210
    /* 8010A210 */ .space 0x112C

dlabel D_8010B33C
    /* 8010B33C */ .space 0x05

dlabel D_8010B341
    /* 8010B341 */ .space 0x09

dlabel D_8010B34A
    /* 8010B34A */ .space 0x0A

dlabel D_8010B354
    /* 8010B354 */ .space 0x04

dlabel D_8010B358
    /* 8010B358 */ .space 0x350

dlabel D_8010B6A8
    /* 8010B6A8 */ .space 0x114

dlabel D_8010B7BC
    /* 8010B7BC */ .space 0x08

dlabel D_8010B7C4
    /* 8010B7C4 */ .space 0x04

dlabel D_8010B7C8
    /* 8010B7C8 */ .space 0xF00

dlabel D_8010C6C8
    /* 8010C6C8 */ .space 0x2C0

dlabel D_8010C988
    /* 8010C988 */ .space 0xF00

dlabel D_8010D888
    /* 8010D888 */ .space 0x2C0

dlabel D_8010DB48
    /* 8010DB48 */ .space 0xF00

dlabel D_8010EA48
    /* 8010EA48 */ .space 0x2C0

dlabel D_8010ED08
    /* 8010ED08 */ .space 0xF08

dlabel D_8010FC10
    /* 8010FC10 */ .space 0x80

dlabel D_8010FC90
    /* 8010FC90 */ .space 0x100

dlabel D_8010FD90
    /* 8010FD90 */ .space 0x04

dlabel D_8010FD94
    /* 8010FD94 */ .space 0x04

dlabel D_8010FD98
    /* 8010FD98 */ .space 0x01

dlabel D_8010FD99
    /* 8010FD99 */ .space 0x01

dlabel D_8010FD9A
    /* 8010FD9A */ .space 0x06

dlabel D_8010FDA0
    /* 8010FDA0 */ .space 0x04

dlabel D_8010FDA4
    /* 8010FDA4 */ .space 0x08

dlabel D_8010FDAC
    /* 8010FDAC */ .space 0x04

dlabel D_8010FDB0
    /* 8010FDB0 */ .space 0x04

dlabel D_8010FDB4
    /* 8010FDB4 */ .space 0x04

dlabel D_8010FDB8
    /* 8010FDB8 */ .space 0x04

dlabel D_8010FDBC
    /* 8010FDBC */ .space 0x04

dlabel D_8010FDC0
    /* 8010FDC0 */ .space 0x04

dlabel D_8010FDC4
    /* 8010FDC4 */ .space 0x14

dlabel D_8010FDD8
    /* 8010FDD8 */ .space 0x04

dlabel D_8010FDDC
    /* 8010FDDC */ .space 0x04

dlabel D_8010FDE0
    /* 8010FDE0 */ .space 0x10

dlabel D_8010FDF0
    /* 8010FDF0 */ .space 0x01

dlabel D_8010FDF1
    /* 8010FDF1 */ .space 0x427

dlabel D_80110218
    /* 80110218 */ .space 0x08

dlabel D_80110220
    /* 80110220 */ .space 0x02

dlabel D_80110222
    /* 80110222 */ .space 0x3A

dlabel D_8011025C
    /* 8011025C */ .space 0x6C5

dlabel D_80110921
    /* 80110921 */ .space 0xF7F

dlabel D_801118A0
    /* 801118A0 */ .space 0xD1C

dlabel D_801125BC
    /* 801125BC */ .space 0x04

dlabel D_801125C0
    /* 801125C0 */ .space 0x06

dlabel D_801125C6
    /* 801125C6 */ .space 0x0C

dlabel D_801125D2
    /* 801125D2 */ .space 0x08

dlabel D_801125DA
    /* 801125DA */ .space 0x12

dlabel D_801125EC
    /* 801125EC */ .space 0x02

dlabel D_801125EE
    /* 801125EE */ .space 0x04

dlabel D_801125F2
    /* 801125F2 */ .space 0x04

dlabel D_801125F6
    /* 801125F6 */ .space 0x04

dlabel D_801125FA
    /* 801125FA */ .space 0x08

dlabel D_80112602
    /* 80112602 */ .space 0x32

dlabel D_80112634
    /* 80112634 */ .space 0x56

dlabel D_8011268A
    /* 8011268A */ .space 0x02

dlabel D_8011268C
    /* 8011268C */ .space 0x4E

dlabel D_801126DA
    /* 801126DA */ .space 0x10C

dlabel D_801127E6
    /* 801127E6 */ .space 0x02

dlabel D_801127E8
    /* 801127E8 */ .space 0x51E

dlabel D_80112D06
    /* 80112D06 */ .space 0x02

dlabel D_80112D08
    /* 80112D08 */ .space 0x0E

dlabel D_80112D16
    /* 80112D16 */ .space 0x02

dlabel D_80112D18
    /* 80112D18 */ .space 0x14

dlabel D_80112D2C
    /* 80112D2C */ .space 0x164

dlabel D_80112E90
    /* 80112E90 */ .space 0x08

dlabel D_80112E98
    /* 80112E98 */ .space 0x04

dlabel D_80112E9C
    /* 80112E9C */ .space 0x04

dlabel D_80112EA0
    /* 80112EA0 */ .space 0x04

dlabel D_80112EA4
    /* 80112EA4 */ .space 0x02

dlabel D_80112EA6
    /* 80112EA6 */ .space 0x02

dlabel D_80112EA8
    /* 80112EA8 */ .space 0x126

dlabel D_80112FCE
    /* 80112FCE */ .space 0x204

dlabel D_801131D2
    /* 801131D2 */ .space 0x01

dlabel D_801131D3
    /* 801131D3 */ .space 0x01

dlabel D_801131D4
    /* 801131D4 */ .space 0x01

dlabel D_801131D5
    /* 801131D5 */ .space 0x14B

dlabel D_80113320
    /* 80113320 */ .space 0x01

dlabel D_80113321
    /* 80113321 */ .space 0x01

dlabel D_80113322
    /* 80113322 */ .space 0x01

dlabel D_80113323
    /* 80113323 */ .space 0x05

dlabel D_80113328
    /* 80113328 */ .space 0x12C

dlabel D_80113454
    /* 80113454 */ .space 0x2E

dlabel D_80113482
    /* 80113482 */ .space 0x06

dlabel D_80113488
    /* 80113488 */ .space 0x0C

dlabel D_80113494
    /* 80113494 */ .space 0x30

dlabel D_801134C4
    /* 801134C4 */ .space 0x6C5

dlabel D_80113B89
    /* 80113B89 */ .space 0xF7F

dlabel D_80114B08
    /* 80114B08 */ .space 0xD1C

dlabel D_80115824
    /* 80115824 */ .space 0x04

dlabel D_80115828
    /* 80115828 */ .space 0x12

dlabel D_8011583A
    /* 8011583A */ .space 0x1A

dlabel D_80115854
    /* 80115854 */ .space 0x02

dlabel D_80115856
    /* 80115856 */ .space 0x04

dlabel D_8011585A
    /* 8011585A */ .space 0x04

dlabel D_8011585E
    /* 8011585E */ .space 0x04

dlabel D_80115862
    /* 80115862 */ .space 0x08

dlabel D_8011586A
    /* 8011586A */ .space 0x32

dlabel D_8011589C
    /* 8011589C */ .space 0x56

dlabel D_801158F2
    /* 801158F2 */ .space 0x02

dlabel D_801158F4
    /* 801158F4 */ .space 0x4E

dlabel D_80115942
    /* 80115942 */ .space 0x63C

dlabel D_80115F7E
    /* 80115F7E */ .space 0x02

dlabel D_80115F80
    /* 80115F80 */ .space 0x180

dlabel D_80116100
    /* 80116100 */ .space 0x04

dlabel D_80116104
    /* 80116104 */ .space 0x08

dlabel D_8011610C
    /* 8011610C */ .space 0x02

dlabel D_8011610E
    /* 8011610E */ .space 0x02

dlabel D_80116110
    /* 80116110 */ .space 0x126

dlabel D_80116236
    /* 80116236 */ .space 0x204

dlabel D_8011643A
    /* 8011643A */ .space 0x01

dlabel D_8011643B
    /* 8011643B */ .space 0x01

dlabel D_8011643C
    /* 8011643C */ .space 0x01

dlabel D_8011643D
    /* 8011643D */ .space 0x01

dlabel D_8011643E
    /* 8011643E */ .space 0x01

dlabel D_8011643F
    /* 8011643F */ .space 0x01

dlabel D_80116440
    /* 80116440 */ .space 0x01

dlabel D_80116441
    /* 80116441 */ .space 0x01

dlabel D_80116442
    /* 80116442 */ .space 0x01

dlabel D_80116443
    /* 80116443 */ .space 0x01

dlabel D_80116444
    /* 80116444 */ .space 0x01

dlabel D_80116445
    /* 80116445 */ .space 0x143

dlabel D_80116588
    /* 80116588 */ .space 0x02

dlabel D_8011658A
    /* 8011658A */ .space 0x01

dlabel D_8011658B
    /* 8011658B */ .space 0x05

dlabel D_80116590
    /* 80116590 */ .space 0x12C

dlabel D_801166BC
    /* 801166BC */ .space 0x34

dlabel D_801166F0
    /* 801166F0 */ .space 0x80

dlabel D_80116770
    /* 80116770 */ .space 0x480

dlabel D_80116BF0
    /* 80116BF0 */ .space 0x4900

dlabel D_8011B4F0
    /* 8011B4F0 */ .space 0x1A91

dlabel D_8011CF81
    /* 8011CF81 */ .space 0xA6F

dlabel D_8011D9F0
    /* 8011D9F0 */ .space 0x9200

dlabel D_80126BF0
    /* 80126BF0 */ .space 0x500

dlabel D_801270F0
    /* 801270F0 */ .space 0xC00

