.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.42.2 */

dlabel D_800F2040
    /* 800F2040 */ .space 0x04

dlabel D_800F2044
    /* 800F2044 */ .space 0x04

dlabel D_800F2048
    /* 800F2048 */ .space 0x04

dlabel D_800F204C
    /* 800F204C */ .space 0x04
