.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.42.2 */

dlabel D_8013FAB0
    /* 8013FAB0 */ .space 0x04

dlabel D_8013FAB4
    /* 8013FAB4 */ .space 0x04

dlabel D_8013FAB8
    /* 8013FAB8 */ .space 0x08

dlabel D_8013FAC0
    /* 8013FAC0 */ .space 0x02

dlabel D_8013FAC2
    /* 8013FAC2 */ .space 0x02

dlabel D_8013FAC4
    /* 8013FAC4 */ .space 0x02

dlabel D_8013FAC6
    /* 8013FAC6 */ .space 0x02

dlabel D_8013FAC8
    /* 8013FAC8 */ .space 0x02

dlabel D_8013FACA
    /* 8013FACA */ .space 0x02

dlabel D_8013FACC
    /* 8013FACC */ .space 0x02

dlabel D_8013FACE
    /* 8013FACE */ .space 0x02

dlabel D_8013FAD0
    /* 8013FAD0 */ .space 0x02

dlabel D_8013FAD2
    /* 8013FAD2 */ .space 0x02

dlabel D_8013FAD4
    /* 8013FAD4 */ .space 0x02

dlabel D_8013FAD6
    /* 8013FAD6 */ .space 0x02

dlabel D_8013FAD8
    /* 8013FAD8 */ .space 0x02

dlabel D_8013FADA
    /* 8013FADA */ .space 0x02

dlabel D_8013FADC
    /* 8013FADC */ .space 0x04

dlabel D_8013FAE0
    /* 8013FAE0 */ .space 0x04

dlabel D_8013FAE4
    /* 8013FAE4 */ .space 0x04

dlabel D_8013FAE8
    /* 8013FAE8 */ .space 0x04

dlabel D_8013FAEC
    /* 8013FAEC */ .space 0x04

dlabel D_8013FAF0
    /* 8013FAF0 */ .space 0x01

dlabel D_8013FAF1
    /* 8013FAF1 */ .space 0x07

dlabel D_8013FAF8
    /* 8013FAF8 */ .space 0x05

dlabel D_8013FAFD
    /* 8013FAFD */ .space 0xD0CB

dlabel D_8014CBC8
    /* 8014CBC8 */ .space 0xC0

dlabel D_8014CC88
    /* 8014CC88 */ .space 0x10

dlabel D_8014CC98
    /* 8014CC98 */ .space 0x04

dlabel D_8014CC9C
    /* 8014CC9C */ .space 0x74

dlabel D_8014CD10
    /* 8014CD10 */ .space 0x48

dlabel D_8014CD58
    /* 8014CD58 */ .space 0x80

dlabel D_8014CDD8
    /* 8014CDD8 */ .space 0x480

dlabel D_8014D258
    /* 8014D258 */ .space 0x04

dlabel D_8014D25C
    /* 8014D25C */ .space 0x04

dlabel D_8014D260
    /* 8014D260 */ .space 0x02

dlabel D_8014D262
    /* 8014D262 */ .space 0x02

dlabel D_8014D264
    /* 8014D264 */ .space 0x02

dlabel D_8014D266
    /* 8014D266 */ .space 0x02

dlabel D_8014D268
    /* 8014D268 */ .space 0x4900

dlabel D_80151B68
    /* 80151B68 */ .space 0x9200

dlabel D_8015AD68
    /* 8015AD68 */ .space 0x2500

dlabel D_8015D268
    /* 8015D268 */ .space 0x502

dlabel D_8015D76A
    /* 8015D76A */ .space 0x02

dlabel D_8015D76C
    /* 8015D76C */ .space 0x04

dlabel D_8015D770
    /* 8015D770 */ .space 0x04

dlabel D_8015D774
    /* 8015D774 */ .space 0x04

dlabel D_8015D778
    /* 8015D778 */ .space 0x20

dlabel D_8015D798
    /* 8015D798 */ .space 0x20

dlabel D_8015D7B8
    /* 8015D7B8 */ .space 0x20

dlabel D_8015D7D8
    /* 8015D7D8 */ .space 0x20

dlabel D_8015D7F8
    /* 8015D7F8 */ .space 0x20

dlabel D_8015D818
    /* 8015D818 */ .space 0x20

dlabel D_8015D838
    /* 8015D838 */ .space 0x20

dlabel D_8015D858
    /* 8015D858 */ .space 0x20

dlabel D_8015D878
    /* 8015D878 */ .space 0x20

dlabel D_8015D898
    /* 8015D898 */ .space 0x20

dlabel D_8015D8B8
    /* 8015D8B8 */ .space 0x20

dlabel D_8015D8D8
    /* 8015D8D8 */ .space 0x20

dlabel D_8015D8F8
    /* 8015D8F8 */ .space 0x20

dlabel D_8015D918
    /* 8015D918 */ .space 0x20

dlabel D_8015D938
    /* 8015D938 */ .space 0x20

dlabel D_8015D958
    /* 8015D958 */ .space 0x20

dlabel D_8015D978
    /* 8015D978 */ .space 0x04

dlabel D_8015D97C
    /* 8015D97C */ .space 0x01

dlabel D_8015D97D
    /* 8015D97D */ .space 0x03

dlabel D_8015D980
    /* 8015D980 */ .space 0x08

dlabel D_8015D988
    /* 8015D988 */ .space 0xC00

dlabel D_8015E588
    /* 8015E588 */ .space 0x08

dlabel D_8015E590
    /* 8015E590 */ .space 0x400

dlabel D_8015E990
    /* 8015E990 */ .space 0x08

dlabel D_8015E998
    /* 8015E998 */ .space 0x400

dlabel D_8015ED98
    /* 8015ED98 */ .space 0x04

dlabel D_8015ED9C
    /* 8015ED9C */ .space 0x04

dlabel D_8015EDA0
    /* 8015EDA0 */ .space 0x04

dlabel D_8015EDA4
    /* 8015EDA4 */ .space 0x04

dlabel D_8015EDA8
    /* 8015EDA8 */ .space 0x04

dlabel D_8015EDAC
    /* 8015EDAC */ .space 0x02

dlabel D_8015EDAE
    /* 8015EDAE */ .space 0x02

dlabel D_8015EDB0
    /* 8015EDB0 */ .space 0x02

dlabel D_8015EDB2
    /* 8015EDB2 */ .space 0x02

dlabel D_8015EDB4
    /* 8015EDB4 */ .space 0x02

dlabel D_8015EDB6
    /* 8015EDB6 */ .space 0x02

dlabel D_8015EDB8
    /* 8015EDB8 */ .space 0x02

dlabel D_8015EDBA
    /* 8015EDBA */ .space 0x02

dlabel D_8015EDBC
    /* 8015EDBC */ .space 0x04

dlabel D_8015EDC0
    /* 8015EDC0 */ .space 0x5A

dlabel D_8015EE1A
    /* 8015EE1A */ .space 0x06

dlabel D_8015EE20
    /* 8015EE20 */ .space 0x60

dlabel D_8015EE80
    /* 8015EE80 */ .space 0x06

dlabel D_8015EE86
    /* 8015EE86 */ .space 0x42

dlabel D_8015EEC8
    /* 8015EEC8 */ .space 0x08

dlabel D_8015EED0
    /* 8015EED0 */ .space 0x600

dlabel D_8015F4D0
    /* 8015F4D0 */ .space 0x02

dlabel D_8015F4D2
    /* 8015F4D2 */ .space 0x02

dlabel D_8015F4D4
    /* 8015F4D4 */ .space 0x04

dlabel D_8015F4D8
    /* 8015F4D8 */ .space 0x04

dlabel D_8015F4DC
    /* 8015F4DC */ .space 0x02

dlabel D_8015F4DE
    /* 8015F4DE */ .space 0x02

dlabel D_8015F4E0
    /* 8015F4E0 */ .space 0x02

dlabel D_8015F4E2
    /* 8015F4E2 */ .space 0x02

dlabel D_8015F4E4
    /* 8015F4E4 */ .space 0x02

dlabel D_8015F4E6
    /* 8015F4E6 */ .space 0x02

dlabel D_8015F4E8
    /* 8015F4E8 */ .space 0x02

dlabel D_8015F4EA
    /* 8015F4EA */ .space 0x02

dlabel D_8015F4EC
    /* 8015F4EC */ .space 0x02

dlabel D_8015F4EE
    /* 8015F4EE */ .space 0x02

dlabel D_8015F4F0
    /* 8015F4F0 */ .space 0x02

dlabel D_8015F4F2
    /* 8015F4F2 */ .space 0x02

dlabel D_8015F4F4
    /* 8015F4F4 */ .space 0x02

dlabel D_8015F4F6
    /* 8015F4F6 */ .space 0x02

dlabel D_8015F4F8
    /* 8015F4F8 */ .space 0x02

dlabel D_8015F4FA
    /* 8015F4FA */ .space 0x02

dlabel D_8015F4FC
    /* 8015F4FC */ .space 0x02

dlabel D_8015F4FE
    /* 8015F4FE */ .space 0x02

dlabel D_8015F500
    /* 8015F500 */ .space 0x02

dlabel D_8015F502
    /* 8015F502 */ .space 0x02

dlabel D_8015F504
    /* 8015F504 */ .space 0x02

dlabel D_8015F506
    /* 8015F506 */ .space 0x02

dlabel D_8015F508
    /* 8015F508 */ .space 0x08

dlabel D_8015F510
    /* 8015F510 */ .space 0x24

dlabel D_8015F534
    /* 8015F534 */ .space 0x02

dlabel D_8015F536
    /* 8015F536 */ .space 0x02

dlabel D_8015F538
    /* 8015F538 */ .space 0x08

dlabel D_8015F540
    /* 8015F540 */ .space 0x24

dlabel D_8015F564
    /* 8015F564 */ .space 0x02

dlabel D_8015F566
    /* 8015F566 */ .space 0x02

dlabel D_8015F568
    /* 8015F568 */ .space 0x08

dlabel D_8015F570
    /* 8015F570 */ .space 0x24

dlabel D_8015F594
    /* 8015F594 */ .space 0x02

dlabel D_8015F596
    /* 8015F596 */ .space 0x02

dlabel D_8015F598
    /* 8015F598 */ .space 0x02

dlabel D_8015F59A
    /* 8015F59A */ .space 0x02

dlabel D_8015F59C
    /* 8015F59C */ .space 0x02

dlabel D_8015F59E
    /* 8015F59E */ .space 0x02

dlabel D_8015F5A0
    /* 8015F5A0 */ .space 0x02

dlabel D_8015F5A2
    /* 8015F5A2 */ .space 0x02

dlabel D_8015F5A4
    /* 8015F5A4 */ .space 0x02

dlabel D_8015F5A6
    /* 8015F5A6 */ .space 0x02

dlabel D_8015F5A8
    /* 8015F5A8 */ .space 0x02

dlabel D_8015F5AA
    /* 8015F5AA */ .space 0x02

dlabel D_8015F5AC
    /* 8015F5AC */ .space 0x02

dlabel D_8015F5AE
    /* 8015F5AE */ .space 0x02

dlabel D_8015F5B0
    /* 8015F5B0 */ .space 0x02

dlabel D_8015F5B2
    /* 8015F5B2 */ .space 0x02

dlabel D_8015F5B4
    /* 8015F5B4 */ .space 0x02

dlabel D_8015F5B6
    /* 8015F5B6 */ .space 0x02

dlabel D_8015F5B8
    /* 8015F5B8 */ .space 0x02

dlabel D_8015F5BA
    /* 8015F5BA */ .space 0x06

dlabel D_8015F5C0
    /* 8015F5C0 */ .space 0x202

dlabel D_8015F7C2
    /* 8015F7C2 */ .space 0x02

dlabel D_8015F7C4
    /* 8015F7C4 */ .space 0x02

dlabel D_8015F7C6
    /* 8015F7C6 */ .space 0x02

dlabel D_8015F7C8
    /* 8015F7C8 */ .space 0x02

dlabel D_8015F7CA
    /* 8015F7CA */ .space 0x02

dlabel D_8015F7CC
    /* 8015F7CC */ .space 0x02

dlabel D_8015F7CE
    /* 8015F7CE */ .space 0x02

dlabel D_8015F7D0
    /* 8015F7D0 */ .space 0x02

dlabel D_8015F7D2
    /* 8015F7D2 */ .space 0x02

dlabel D_8015F7D4
    /* 8015F7D4 */ .space 0x02

dlabel D_8015F7D6
    /* 8015F7D6 */ .space 0x02

dlabel D_8015F7D8
    /* 8015F7D8 */ .space 0x02

dlabel D_8015F7DA
    /* 8015F7DA */ .space 0x02

dlabel D_8015F7DC
    /* 8015F7DC */ .space 0x02

dlabel D_8015F7DE
    /* 8015F7DE */ .space 0x02

dlabel D_8015F7E0
    /* 8015F7E0 */ .space 0x02

dlabel D_8015F7E2
    /* 8015F7E2 */ .space 0x02

dlabel D_8015F7E4
    /* 8015F7E4 */ .space 0x02

dlabel D_8015F7E6
    /* 8015F7E6 */ .space 0x02

dlabel D_8015F7E8
    /* 8015F7E8 */ .space 0x02

dlabel D_8015F7EA
    /* 8015F7EA */ .space 0x02

dlabel D_8015F7EC
    /* 8015F7EC */ .space 0x02

dlabel D_8015F7EE
    /* 8015F7EE */ .space 0x02

dlabel D_8015F7F0
    /* 8015F7F0 */ .space 0x02

dlabel D_8015F7F2
    /* 8015F7F2 */ .space 0x02

dlabel D_8015F7F4
    /* 8015F7F4 */ .space 0x02

dlabel D_8015F7F6
    /* 8015F7F6 */ .space 0x02

dlabel D_8015F7F8
    /* 8015F7F8 */ .space 0x02

dlabel D_8015F7FA
    /* 8015F7FA */ .space 0x02

dlabel D_8015F7FC
    /* 8015F7FC */ .space 0x02

dlabel D_8015F7FE
    /* 8015F7FE */ .space 0x02

dlabel D_8015F800
    /* 8015F800 */ .space 0x02

dlabel D_8015F802
    /* 8015F802 */ .space 0x02

dlabel D_8015F804
    /* 8015F804 */ .space 0x02

dlabel D_8015F806
    /* 8015F806 */ .space 0x02

dlabel D_8015F808
    /* 8015F808 */ .space 0x02

dlabel D_8015F80A
    /* 8015F80A */ .space 0x02

dlabel D_8015F80C
    /* 8015F80C */ .space 0x02

dlabel D_8015F80E
    /* 8015F80E */ .space 0x02

dlabel D_8015F810
    /* 8015F810 */ .space 0x02

dlabel D_8015F812
    /* 8015F812 */ .space 0x02

dlabel D_8015F814
    /* 8015F814 */ .space 0x02

dlabel D_8015F816
    /* 8015F816 */ .space 0x02

dlabel D_8015F818
    /* 8015F818 */ .space 0x02

dlabel D_8015F81A
    /* 8015F81A */ .space 0x04

dlabel D_8015F81E
    /* 8015F81E */ .space 0x04

dlabel D_8015F822
    /* 8015F822 */ .space 0x04

dlabel D_8015F826
    /* 8015F826 */ .space 0x04

dlabel D_8015F82A
    /* 8015F82A */ .space 0x04

dlabel D_8015F82E
    /* 8015F82E */ .space 0x04

dlabel D_8015F832
    /* 8015F832 */ .space 0x04

dlabel D_8015F836
    /* 8015F836 */ .space 0x04

dlabel D_8015F83A
    /* 8015F83A */ .space 0x04

dlabel D_8015F83E
    /* 8015F83E */ .space 0x04

dlabel D_8015F842
    /* 8015F842 */ .space 0x06

dlabel D_8015F848
    /* 8015F848 */ .space 0x06

dlabel D_8015F84E
    /* 8015F84E */ .space 0x02

dlabel D_8015F850
    /* 8015F850 */ .space 0x04

dlabel D_8015F854
    /* 8015F854 */ .space 0x04

dlabel D_8015F858
    /* 8015F858 */ .space 0x04

dlabel D_8015F85C
    /* 8015F85C */ .space 0x04

dlabel D_8015F860
    /* 8015F860 */ .space 0x04

dlabel D_8015F864
    /* 8015F864 */ .space 0x04

dlabel D_8015F868
    /* 8015F868 */ .space 0x04

dlabel D_8015F86C
    /* 8015F86C */ .space 0x04

dlabel D_8015F870
    /* 8015F870 */ .space 0x04

dlabel D_8015F874
    /* 8015F874 */ .space 0x04

dlabel D_8015F878
    /* 8015F878 */ .space 0x02

dlabel D_8015F87A
    /* 8015F87A */ .space 0x02

dlabel D_8015F87C
    /* 8015F87C */ .space 0x02

dlabel D_8015F87E
    /* 8015F87E */ .space 0x02

dlabel D_8015F880
    /* 8015F880 */ .space 0x02

dlabel D_8015F882
    /* 8015F882 */ .space 0x02

dlabel D_8015F884
    /* 8015F884 */ .space 0x02

dlabel D_8015F886
    /* 8015F886 */ .space 0x02

dlabel D_8015F888
    /* 8015F888 */ .space 0x02

dlabel D_8015F88A
    /* 8015F88A */ .space 0x02

dlabel D_8015F88C
    /* 8015F88C */ .space 0x02

dlabel D_8015F88E
    /* 8015F88E */ .space 0x02

dlabel D_8015F890
    /* 8015F890 */ .space 0x02

dlabel D_8015F892
    /* 8015F892 */ .space 0x02

dlabel D_8015F894
    /* 8015F894 */ .space 0x02

dlabel D_8015F896
    /* 8015F896 */ .space 0x02

dlabel D_8015F898
    /* 8015F898 */ .space 0x02

dlabel D_8015F89A
    /* 8015F89A */ .space 0x02

dlabel D_8015F89C
    /* 8015F89C */ .space 0x02

dlabel D_8015F89E
    /* 8015F89E */ .space 0x02

dlabel D_8015F8A0
    /* 8015F8A0 */ .space 0x02

dlabel D_8015F8A2
    /* 8015F8A2 */ .space 0x06

dlabel D_8015F8A8
    /* 8015F8A8 */ .space 0xC0

dlabel D_8015F968
    /* 8015F968 */ .space 0x02

dlabel D_8015F96A
    /* 8015F96A */ .space 0x02

dlabel D_8015F96C
    /* 8015F96C */ .space 0x02

dlabel D_8015F96E
    /* 8015F96E */ .space 0x02

dlabel D_8015F970
    /* 8015F970 */ .space 0x08

dlabel D_8015F978
    /* 8015F978 */ .space 0x40

dlabel D_8015F9B8
    /* 8015F9B8 */ .space 0x40

dlabel D_8015F9F8
    /* 8015F9F8 */ .space 0x08

dlabel D_8015FA00
    /* 8015FA00 */ .space 0x02

dlabel D_8015FA02
    /* 8015FA02 */ .space 0x02

dlabel D_8015FA04
    /* 8015FA04 */ .space 0x02

dlabel D_8015FA06
    /* 8015FA06 */ .space 0x02

dlabel D_8015FA08
    /* 8015FA08 */ .space 0x02

dlabel D_8015FA0A
    /* 8015FA0A */ .space 0x06

dlabel D_8015FA10
    /* 8015FA10 */ .space 0x10E

dlabel D_8015FB1E
    /* 8015FB1E */ .space 0x12

dlabel D_8015FB30
    /* 8015FB30 */ .space 0x02

dlabel D_8015FB32
    /* 8015FB32 */ .space 0x0E

dlabel D_8015FB40
    /* 8015FB40 */ .space 0x02

dlabel D_8015FB42
    /* 8015FB42 */ .space 0x02

dlabel D_8015FB44
    /* 8015FB44 */ .space 0x02

dlabel D_8015FB46
    /* 8015FB46 */ .space 0x02

dlabel D_8015FB48
    /* 8015FB48 */ .space 0x2A0

dlabel D_8015FDE8
    /* 8015FDE8 */ .space 0x04

dlabel D_8015FDEC
    /* 8015FDEC */ .space 0x02

dlabel D_8015FDEE
    /* 8015FDEE */ .space 0x02

dlabel D_8015FDF0
    /* 8015FDF0 */ .space 0x02

dlabel D_8015FDF2
    /* 8015FDF2 */ .space 0x02

dlabel D_8015FDF4
    /* 8015FDF4 */ .space 0x02

dlabel D_8015FDF6
    /* 8015FDF6 */ .space 0x02

dlabel D_8015FDF8
    /* 8015FDF8 */ .space 0x02

dlabel D_8015FDFA
    /* 8015FDFA */ .space 0x02

dlabel D_8015FDFC
    /* 8015FDFC */ .space 0x02

dlabel D_8015FDFE
    /* 8015FDFE */ .space 0x02

dlabel D_8015FE00
    /* 8015FE00 */ .space 0x04

dlabel D_8015FE04
    /* 8015FE04 */ .space 0x04

dlabel D_8015FE08
    /* 8015FE08 */ .space 0x02

dlabel D_8015FE0A
    /* 8015FE0A */ .space 0x02

dlabel D_8015FE0C
    /* 8015FE0C */ .space 0x02

dlabel D_8015FE0E
    /* 8015FE0E */ .space 0x02

dlabel D_8015FE10
    /* 8015FE10 */ .space 0xE00

dlabel D_80160C10
    /* 80160C10 */ .space 0x02

dlabel D_80160C12
    /* 80160C12 */ .space 0x02

dlabel D_80160C14
    /* 80160C14 */ .space 0x02

dlabel D_80160C16
    /* 80160C16 */ .space 0x02

dlabel D_80160C18
    /* 80160C18 */ .space 0x02

dlabel D_80160C1A
    /* 80160C1A */ .space 0x02

dlabel D_80160C1C
    /* 80160C1C */ .space 0x02

dlabel D_80160C1E
    /* 80160C1E */ .space 0x02

dlabel D_80160C20
    /* 80160C20 */ .space 0x02

dlabel D_80160C22
    /* 80160C22 */ .space 0x02

dlabel D_80160C24
    /* 80160C24 */ .space 0x02

dlabel D_80160C26
    /* 80160C26 */ .space 0x02

dlabel D_80160C28
    /* 80160C28 */ .space 0x04

dlabel D_80160C2C
    /* 80160C2C */ .space 0x04

dlabel D_80160C30
    /* 80160C30 */ .space 0x04

dlabel D_80160C34
    /* 80160C34 */ .space 0x04

dlabel D_80160C38
    /* 80160C38 */ .space 0x04

dlabel D_80160C3C
    /* 80160C3C */ .space 0x04

dlabel D_80160C40
    /* 80160C40 */ .space 0x04

dlabel D_80160C44
    /* 80160C44 */ .space 0x04

dlabel D_80160C48
    /* 80160C48 */ .space 0x04

dlabel D_80160C4C
    /* 80160C4C */ .space 0x04

dlabel D_80160C50
    /* 80160C50 */ .space 0x04

dlabel D_80160C54
    /* 80160C54 */ .space 0x02

dlabel D_80160C56
    /* 80160C56 */ .space 0x02

dlabel D_80160C58
    /* 80160C58 */ .space 0x04

dlabel D_80160C5C
    /* 80160C5C */ .space 0x04

dlabel D_80160C60
    /* 80160C60 */ .space 0x04

dlabel D_80160C64
    /* 80160C64 */ .space 0x04

dlabel D_80160C68
    /* 80160C68 */ .space 0x04

dlabel D_80160C6C
    /* 80160C6C */ .space 0x04

dlabel D_80160C70
    /* 80160C70 */ .space 0x04

dlabel D_80160C74
    /* 80160C74 */ .space 0x04

dlabel D_80160C78
    /* 80160C78 */ .space 0x04

dlabel D_80160C7C
    /* 80160C7C */ .space 0x04

dlabel D_80160C80
    /* 80160C80 */ .space 0x04

dlabel D_80160C84
    /* 80160C84 */ .space 0x04

dlabel D_80160C88
    /* 80160C88 */ .space 0x04

dlabel D_80160C8C
    /* 80160C8C */ .space 0x04

dlabel D_80160C90
    /* 80160C90 */ .space 0x04

dlabel D_80160C94
    /* 80160C94 */ .space 0x04

dlabel D_80160C98
    /* 80160C98 */ .space 0x04

dlabel D_80160C9C
    /* 80160C9C */ .space 0x04

dlabel D_80160CA0
    /* 80160CA0 */ .space 0x02

dlabel D_80160CA2
    /* 80160CA2 */ .space 0x02

dlabel D_80160CA4
    /* 80160CA4 */ .space 0x02

dlabel D_80160CA6
    /* 80160CA6 */ .space 0x02

dlabel D_80160CA8
    /* 80160CA8 */ .space 0x02

dlabel D_80160CAA
    /* 80160CAA */ .space 0x02

dlabel D_80160CAC
    /* 80160CAC */ .space 0x04

dlabel D_80160CB0
    /* 80160CB0 */ .space 0x800

dlabel D_801614B0
    /* 801614B0 */ .space 0x08

dlabel D_801614B8
    /* 801614B8 */ .space 0x80

dlabel D_80161538
    /* 80161538 */ .space 0x02

dlabel D_8016153A
    /* 8016153A */ .space 0x02

dlabel D_8016153C
    /* 8016153C */ .space 0x02

dlabel D_8016153E
    /* 8016153E */ .space 0x02

dlabel D_80161540
    /* 80161540 */ .space 0x40
