.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.42.2 */

dlabel D_800F2290
    /* 800F2290 */ .space 0x08

dlabel D_800F2298
    /* 800F2298 */ .space 0x18

dlabel D_800F22B0
    /* 800F22B0 */ .space 0x04

dlabel D_800F22B4
    /* 800F22B4 */ .space 0x04

dlabel D_800F22B8
    /* 800F22B8 */ .space 0x04

dlabel D_800F22BC
    /* 800F22BC */ .space 0x04

dlabel D_800F22C0
    /* 800F22C0 */ .space 0x04

dlabel D_800F22C4
    /* 800F22C4 */ .space 0x04

dlabel D_800F22C8
    /* 800F22C8 */ .space 0x18

dlabel D_800F22E0
    /* 800F22E0 */ .space 0x20

dlabel D_800F2300
    /* 800F2300 */ .space 0x28

dlabel D_800F2328
    /* 800F2328 */ .space 0x10

dlabel mainThread
    /* 800F2338 */ .space 0x1B0

dlabel idleThread
    /* 800F24E8 */ .space 0x1B0

dlabel schedThread
    /* 800F2698 */ .space 0x21B0

dlabel mainThreadStack
    /* 800F4848 */ .space 0x2000

dlabel idleThreadStack
    /* 800F6848 */ .space 0x2000

dlabel schedThreadStack
    /* 800F8848 */ .space 0x2000
