.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.42.2 */

dlabel __osEepPifRam
    /* 80163A40 */ .space 0x3C

dlabel D_80163A7C
    /* 80163A7C */ .space 0x04

dlabel __osContPifRam
    /* 80163A80 */ .space 0x3C

dlabel D_80163ABC
    /* 80163ABC */ .space 0x04

dlabel __osContLastCmd
    /* 80163AC0 */ .space 0x01

dlabel __osMaxControllers
    /* 80163AC1 */ .space 0x27

dlabel __osEepromTimerQ
    /* 80163AE8 */ .space 0x18

dlabel __osEepromTimerMsg
    /* 80163B00 */ .space 0x10
