.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel entrypoint
    /* 1000 80025C50 3C08800F */  lui        $t0, %hi(main_BSS_START)
    /* 1004 80025C54 3C090007 */  lui        $t1, (0x72E20 >> 16)
    /* 1008 80025C58 25082040 */  addiu      $t0, $t0, %lo(main_BSS_START)
    /* 100C 80025C5C 35292E20 */  ori        $t1, $t1, (0x72E20 & 0xFFFF)
  .L80025C60:
    /* 1010 80025C60 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
    /* 1014 80025C64 AD000000 */  sw         $zero, 0x0($t0)
    /* 1018 80025C68 AD000004 */  sw         $zero, 0x4($t0)
    /* 101C 80025C6C 1520FFFC */  bnez       $t1, .L80025C60
    /* 1020 80025C70 21080008 */   addi      $t0, $t0, 0x8 /* handwritten instruction */
    /* 1024 80025C74 3C0A8003 */  lui        $t2, %hi(main)
    /* 1028 80025C78 3C1D800F */  lui        $sp, %hi(mainThreadStack)
    /* 102C 80025C7C 254A9510 */  addiu      $t2, $t2, %lo(main)
    /* 1030 80025C80 01400008 */  jr         $t2
    /* 1034 80025C84 27BD4848 */   addiu     $sp, $sp, %lo(mainThreadStack)
    /* 1038 80025C88 00000000 */  nop
    /* 103C 80025C8C 00000000 */  nop
    /* 1040 80025C90 00000000 */  nop
    /* 1044 80025C94 00000000 */  nop
    /* 1048 80025C98 00000000 */  nop
    /* 104C 80025C9C 00000000 */  nop
