.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel func_800D04B0
    /* AB860 800D04B0 10C00006 */  beqz       $a2, .L800D04CC
    /* AB864 800D04B4 00C44020 */   add       $t0, $a2, $a0 /* handwritten instruction */
  .L800D04B8:
    /* AB868 800D04B8 8C890000 */  lw         $t1, 0x0($a0)
    /* AB86C 800D04BC 24840004 */  addiu      $a0, $a0, 0x4
    /* AB870 800D04C0 ACA90000 */  sw         $t1, 0x0($a1)
    /* AB874 800D04C4 1488FFFC */  bne        $a0, $t0, .L800D04B8
    /* AB878 800D04C8 24A50004 */   addiu     $a1, $a1, 0x4
  .L800D04CC:
    /* AB87C 800D04CC 00051020 */  add        $v0, $zero, $a1 /* handwritten instruction */
    /* AB880 800D04D0 03E00008 */  jr         $ra
    /* AB884 800D04D4 00000000 */   nop
    /* AB888 800D04D8 00000000 */  nop
    /* AB88C 800D04DC 00000000 */  nop
