.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel func_800D0430
    /* AB7E0 800D0430 00804825 */  or         $t1, $a0, $zero
    /* AB7E4 800D0434 2401FFF8 */  addiu      $at, $zero, -0x8
    /* AB7E8 800D0438 01214824 */  and        $t1, $t1, $at
    /* AB7EC 800D043C 01254825 */  or         $t1, $t1, $a1
    /* AB7F0 800D0440 2401FFFB */  addiu      $at, $zero, -0x5
    /* AB7F4 800D0444 01214824 */  and        $t1, $t1, $at
    /* AB7F8 800D0448 40899000 */  mtc0       $t1, $18 /* handwritten instruction */
    /* AB7FC 800D044C 24090000 */  addiu      $t1, $zero, 0x0
    /* AB800 800D0450 01294825 */  or         $t1, $t1, $t1
    /* AB804 800D0454 40899800 */  mtc0       $t1, $19 /* handwritten instruction */
    /* AB808 800D0458 03E00008 */  jr         $ra

/* Handwritten function */
glabel func_800D045C
    /* AB80C 800D045C 24080000 */  addiu      $t0, $zero, 0x0
    /* AB810 800D0460 01084025 */  or         $t0, $t0, $t0
    /* AB814 800D0464 40889000 */  mtc0       $t0, $18 /* handwritten instruction */
    /* AB818 800D0468 24090000 */  addiu      $t1, $zero, 0x0
    /* AB81C 800D046C 01294825 */  or         $t1, $t1, $t1
    /* AB820 800D0470 40899800 */  mtc0       $t1, $19 /* handwritten instruction */
    /* AB824 800D0474 03E00008 */  jr         $ra
    /* AB828 800D0478 00000000 */   nop
    /* AB82C 800D047C 00000000 */  nop
