.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel func_800D0480
    /* AB830 800D0480 10C00007 */  beqz       $a2, .L800D04A0
    /* AB834 800D0484 00C44020 */   add       $t0, $a2, $a0 /* handwritten instruction */
  .L800D0488:
    /* AB838 800D0488 80890000 */  lb         $t1, 0x0($a0)
    /* AB83C 800D048C 24840001 */  addiu      $a0, $a0, 0x1
    /* AB840 800D0490 00094A00 */  sll        $t1, $t1, 8
    /* AB844 800D0494 A4A90000 */  sh         $t1, 0x0($a1)
    /* AB848 800D0498 1488FFFB */  bne        $a0, $t0, .L800D0488
    /* AB84C 800D049C 24A50002 */   addiu     $a1, $a1, 0x2
  .L800D04A0:
    /* AB850 800D04A0 00051020 */  add        $v0, $zero, $a1 /* handwritten instruction */
    /* AB854 800D04A4 03E00008 */  jr         $ra
    /* AB858 800D04A8 00000000 */   nop
    /* AB85C 800D04AC 00000000 */  nop
