.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel rspbootTextStart
    /* B86B0 800DD300 09000419 */  j          func_84001064
    /* B86B4 800DD304 20010FC0 */   addi      $at, $zero, 0xFC0 /* handwritten instruction */

/* Handwritten function */
glabel func_800DD308
    /* B86B8 800DD308 8C220010 */  lw         $v0, 0x10($at)
    /* B86BC 800DD30C 20030F7F */  addi       $v1, $zero, 0xF7F /* handwritten instruction */
    /* B86C0 800DD310 20071080 */  addi       $a3, $zero, 0x1080 /* handwritten instruction */
    /* B86C4 800DD314 40870000 */  mtc0       $a3, $0 /* handwritten instruction */
    /* B86C8 800DD318 40820800 */  mtc0       $v0, $1 /* handwritten instruction */
    /* B86CC 800DD31C 40831000 */  mtc0       $v1, $2 /* handwritten instruction */
  .L800DD320:
    /* B86D0 800DD320 40043000 */  mfc0       $a0, $6 /* handwritten instruction */
    /* B86D4 800DD324 1480FFFE */  bnez       $a0, .L800DD320
    /* B86D8 800DD328 00000000 */   nop
    /* B86DC 800DD32C 0D00040F */  jal        func_8400103C
    /* B86E0 800DD330 00000000 */   nop
    /* B86E4 800DD334 00E00008 */  jr         $a3
    /* B86E8 800DD338 40803800 */   mtc0      $zero, $7 /* handwritten instruction */
  .L800DD33C:
    /* B86EC 800DD33C 40082000 */  mfc0       $t0, $4 /* handwritten instruction */
    /* B86F0 800DD340 31080080 */  andi       $t0, $t0, 0x80
    /* B86F4 800DD344 15000002 */  bnez       $t0, .L800DD350
    /* B86F8 800DD348 00000000 */   nop
    /* B86FC 800DD34C 03E00008 */  jr         $ra
  .L800DD350:
    /* B8700 800DD350 40803800 */   mtc0      $zero, $7 /* handwritten instruction */
    /* B8704 800DD354 34085200 */  ori        $t0, $zero, 0x5200
    /* B8708 800DD358 40882000 */  mtc0       $t0, $4 /* handwritten instruction */
    /* B870C 800DD35C 0000000D */  break      0
    /* B8710 800DD360 00000000 */  nop
    /* B8714 800DD364 8C220004 */  lw         $v0, 0x4($at)
    /* B8718 800DD368 30420002 */  andi       $v0, $v0, 0x2
    /* B871C 800DD36C 10400007 */  beqz       $v0, .L800DD38C
    /* B8720 800DD370 00000000 */   nop
    /* B8724 800DD374 0D00040F */  jal        func_8400103C
    /* B8728 800DD378 00000000 */   nop
    /* B872C 800DD37C 40025800 */  mfc0       $v0, $11 /* handwritten instruction */
    /* B8730 800DD380 30420100 */  andi       $v0, $v0, 0x100
    /* B8734 800DD384 1C40FFED */  bgtz       $v0, .L800DD33C
    /* B8738 800DD388 00000000 */   nop
  .L800DD38C:
    /* B873C 800DD38C 8C220018 */  lw         $v0, 0x18($at)
    /* B8740 800DD390 8C23001C */  lw         $v1, 0x1C($at)
    /* B8744 800DD394 2063FFFF */  addi       $v1, $v1, -0x1 /* handwritten instruction */
  .L800DD398:
    /* B8748 800DD398 401E2800 */  mfc0       $fp, $5 /* handwritten instruction */
    /* B874C 800DD39C 17C0FFFE */  bnez       $fp, .L800DD398
    /* B8750 800DD3A0 00000000 */   nop
    /* B8754 800DD3A4 40800000 */  mtc0       $zero, $0 /* handwritten instruction */
    /* B8758 800DD3A8 40820800 */  mtc0       $v0, $1 /* handwritten instruction */
    /* B875C 800DD3AC 40831000 */  mtc0       $v1, $2 /* handwritten instruction */
  .L800DD3B0:
    /* B8760 800DD3B0 40043000 */  mfc0       $a0, $6 /* handwritten instruction */
    /* B8764 800DD3B4 1480FFFE */  bnez       $a0, .L800DD3B0
    /* B8768 800DD3B8 00000000 */   nop
    /* B876C 800DD3BC 0D00040F */  jal        func_8400103C
    /* B8770 800DD3C0 00000000 */   nop
    /* B8774 800DD3C4 09000402 */  j          func_84001008
    /* B8778 800DD3C8 00000000 */   nop
    /* B877C 800DD3CC 00000000 */  nop

/* Handwritten function */
glabel gspFast3D_fifoTextStart
    /* B8780 800DD3D0 090005E0 */  j          func_84001780
    /* B8784 800DD3D4 201D0110 */   addi      $sp, $zero, 0x110 /* handwritten instruction */

/* Handwritten function */
glabel func_800DD3D8
    /* B8788 800DD3D8 0D000447 */  jal        func_8400111C
    /* B878C 800DD3DC 03009820 */   add       $s3, $t8, $zero /* handwritten instruction */
    /* B8790 800DD3E0 0016A020 */  add        $s4, $zero, $s6 /* handwritten instruction */
    /* B8794 800DD3E4 0D00044F */  jal        func_8400113C
    /* B8798 800DD3E8 20110000 */   addi      $s1, $zero, 0x0 /* handwritten instruction */
    /* B879C 800DD3EC 842200BC */  lh         $v0, 0xBC($at)
    /* B87A0 800DD3F0 00400008 */  jr         $v0
    /* B87A4 800DD3F4 001915C2 */   srl       $v0, $t9, 23
    /* B87A8 800DD3F8 40022000 */  mfc0       $v0, $4 /* handwritten instruction */
    /* B87AC 800DD3FC 30420080 */  andi       $v0, $v0, 0x80
    /* B87B0 800DD400 14400006 */  bnez       $v0, .L800DD41C
    /* B87B4 800DD404 84150026 */   lh        $s5, 0x26($zero)
    /* B87B8 800DD408 1F80FFE9 */  bgtz       $gp, .L800DD3B0
    /* B87BC 800DD40C 00000000 */   nop
    /* B87C0 800DD410 09000435 */  j          func_840010D4
    /* B87C4 800DD414 841F0102 */   lh        $ra, 0x102($zero)
    /* B87C8 800DD418 841500B6 */  lh         $s5, 0xB6($zero)
  .L800DD41C:
    /* B87CC 800DD41C 0900043F */  j          func_840010FC
    /* B87D0 800DD420 341E0020 */   ori       $fp, $zero, 0x20

/* Handwritten function */
glabel func_800DD424
    /* B87D4 800DD424 201C0140 */  addi       $gp, $zero, 0x140 /* handwritten instruction */
    /* B87D8 800DD428 001FA820 */  add        $s5, $zero, $ra /* handwritten instruction */
    /* B87DC 800DD42C 201406A0 */  addi       $s4, $zero, 0x6A0 /* handwritten instruction */
    /* B87E0 800DD430 001A9820 */  add        $s3, $zero, $k0 /* handwritten instruction */
    /* B87E4 800DD434 2012013F */  addi       $s2, $zero, 0x13F /* handwritten instruction */
    /* B87E8 800DD438 0D00044F */  jal        func_8400113C
    /* B87EC 800DD43C 20110000 */   addi      $s1, $zero, 0x0 /* handwritten instruction */
    /* B87F0 800DD440 02A00008 */  jr         $s5
    /* B87F4 800DD444 201B06A0 */   addi      $k1, $zero, 0x6A0 /* handwritten instruction */
    /* B87F8 800DD448 001FA820 */  add        $s5, $zero, $ra /* handwritten instruction */
    /* B87FC 800DD44C 8FD30000 */  lw         $s3, 0x0($fp)
    /* B8800 800DD450 87D20004 */  lh         $s2, 0x4($fp)
    /* B8804 800DD454 87D40006 */  lh         $s4, 0x6($fp)
    /* B8808 800DD458 0D00044F */  jal        func_8400113C
    /* B880C 800DD45C 20110000 */   addi      $s1, $zero, 0x0 /* handwritten instruction */
    /* B8810 800DD460 0D000459 */  jal        func_84001164
    /* B8814 800DD464 00000000 */   nop
    /* B8818 800DD468 02A00008 */  jr         $s5
    /* B881C 800DD46C 8C0B00B8 */   lw        $t3, 0xB8($zero)
    /* B8820 800DD470 00136582 */  srl        $t4, $s3, 22
    /* B8824 800DD474 318C003C */  andi       $t4, $t4, 0x3C
    /* B8828 800DD478 026B9824 */  and        $s3, $s3, $t3
    /* B882C 800DD47C 000C6820 */  add        $t5, $zero, $t4 /* handwritten instruction */
    /* B8830 800DD480 8DAC0160 */  lw         $t4, 0x160($t5)
    /* B8834 800DD484 03E00008 */  jr         $ra
    /* B8838 800DD488 026C9820 */   add       $s3, $s3, $t4 /* handwritten instruction */

/* Handwritten function */
glabel func_800DD48C
    /* B883C 800DD48C 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
    /* B8840 800DD490 1560FFFE */  bnez       $t3, func_800DD48C
    /* B8844 800DD494 00000000 */   nop
    /* B8848 800DD498 40940000 */  mtc0       $s4, $0 /* handwritten instruction */
    /* B884C 800DD49C 1E200003 */  bgtz       $s1, .L800DD4AC
    /* B8850 800DD4A0 40930800 */   mtc0      $s3, $1 /* handwritten instruction */
    /* B8854 800DD4A4 03E00008 */  jr         $ra
    /* B8858 800DD4A8 40921000 */   mtc0      $s2, $2 /* handwritten instruction */
  .L800DD4AC:
    /* B885C 800DD4AC 03E00008 */  jr         $ra
    /* B8860 800DD4B0 40921800 */   mtc0      $s2, $3 /* handwritten instruction */

/* Handwritten function */
glabel func_800DD4B4
    /* B8864 800DD4B4 400B3000 */  mfc0       $t3, $6 /* handwritten instruction */
    /* B8868 800DD4B8 1560FFFE */  bnez       $t3, func_800DD4B4
    /* B886C 800DD4BC 00000000 */   nop
    /* B8870 800DD4C0 03E00008 */  jr         $ra
    /* B8874 800DD4C4 00000000 */   nop

/* Handwritten function */
glabel func_800DD4C8
    /* B8878 800DD4C8 001FA820 */  add        $s5, $zero, $ra /* handwritten instruction */
    /* B887C 800DD4CC 8FB30018 */  lw         $s3, 0x18($sp)
