.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

glabel sqrtf
    /* B04B0 800D5100 03E00008 */  jr         $ra
    /* B04B4 800D5104 46006004 */   sqrt.s    $fv0, $fa0
    /* B04B8 800D5108 00000000 */  nop
    /* B04BC 800D510C 00000000 */  nop
