.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel _bcopy
    /* B33D0 800D8020 10C0001A */  beqz       $a2, .L800D808C
    /* B33D4 800D8024 00A03825 */   or        $a3, $a1, $zero
    /* B33D8 800D8028 10850018 */  beq        $a0, $a1, .L800D808C
    /* B33DC 800D802C 00A4082A */   slt       $at, $a1, $a0
    /* B33E0 800D8030 54200008 */  bnel       $at, $zero, .L800D8054
    /* B33E4 800D8034 28C10010 */   slti      $at, $a2, 0x10
    /* B33E8 800D8038 00861020 */  add        $v0, $a0, $a2 /* handwritten instruction */
    /* B33EC 800D803C 00A2082A */  slt        $at, $a1, $v0
    /* B33F0 800D8040 50200004 */  beql       $at, $zero, .L800D8054
    /* B33F4 800D8044 28C10010 */   slti      $at, $a2, 0x10
    /* B33F8 800D8048 1000005B */  b          .L800D81B8
    /* B33FC 800D804C 28C10010 */   slti      $at, $a2, 0x10
    /* B3400 800D8050 28C10010 */  slti       $at, $a2, 0x10
  .L800D8054:
    /* B3404 800D8054 14200005 */  bnez       $at, .L800D806C
    /* B3408 800D8058 00000000 */   nop
    /* B340C 800D805C 30820003 */  andi       $v0, $a0, 0x3
    /* B3410 800D8060 30A30003 */  andi       $v1, $a1, 0x3
    /* B3414 800D8064 1043000B */  beq        $v0, $v1, .L800D8094
    /* B3418 800D8068 00000000 */   nop
  .L800D806C:
    /* B341C 800D806C 10C00007 */  beqz       $a2, .L800D808C
    /* B3420 800D8070 00000000 */   nop
    /* B3424 800D8074 00861821 */  addu       $v1, $a0, $a2
  .L800D8078:
    /* B3428 800D8078 80820000 */  lb         $v0, 0x0($a0)
    /* B342C 800D807C 24840001 */  addiu      $a0, $a0, 0x1
    /* B3430 800D8080 24A50001 */  addiu      $a1, $a1, 0x1
    /* B3434 800D8084 1483FFFC */  bne        $a0, $v1, .L800D8078
    /* B3438 800D8088 A0A2FFFF */   sb        $v0, -0x1($a1)
  .L800D808C:
    /* B343C 800D808C 03E00008 */  jr         $ra
    /* B3440 800D8090 00E01025 */   or        $v0, $a3, $zero
  .L800D8094:
    /* B3444 800D8094 10400018 */  beqz       $v0, .L800D80F8
    /* B3448 800D8098 24010001 */   addiu     $at, $zero, 0x1
    /* B344C 800D809C 1041000F */  beq        $v0, $at, .L800D80DC
    /* B3450 800D80A0 24010002 */   addiu     $at, $zero, 0x2
    /* B3454 800D80A4 50410008 */  beql       $v0, $at, .L800D80C8
    /* B3458 800D80A8 84820000 */   lh        $v0, 0x0($a0)
    /* B345C 800D80AC 80820000 */  lb         $v0, 0x0($a0)
    /* B3460 800D80B0 24840001 */  addiu      $a0, $a0, 0x1
    /* B3464 800D80B4 24A50001 */  addiu      $a1, $a1, 0x1
    /* B3468 800D80B8 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* B346C 800D80BC 1000000E */  b          .L800D80F8
    /* B3470 800D80C0 A0A2FFFF */   sb        $v0, -0x1($a1)
    /* B3474 800D80C4 84820000 */  lh         $v0, 0x0($a0)
  .L800D80C8:
    /* B3478 800D80C8 24840002 */  addiu      $a0, $a0, 0x2
    /* B347C 800D80CC 24A50002 */  addiu      $a1, $a1, 0x2
    /* B3480 800D80D0 24C6FFFE */  addiu      $a2, $a2, -0x2
    /* B3484 800D80D4 10000008 */  b          .L800D80F8
    /* B3488 800D80D8 A4A2FFFE */   sh        $v0, -0x2($a1)
  .L800D80DC:
    /* B348C 800D80DC 80820000 */  lb         $v0, 0x0($a0)
    /* B3490 800D80E0 84830001 */  lh         $v1, 0x1($a0)
    /* B3494 800D80E4 24840003 */  addiu      $a0, $a0, 0x3
    /* B3498 800D80E8 24A50003 */  addiu      $a1, $a1, 0x3
    /* B349C 800D80EC 24C6FFFD */  addiu      $a2, $a2, -0x3
    /* B34A0 800D80F0 A0A2FFFD */  sb         $v0, -0x3($a1)
    /* B34A4 800D80F4 A4A3FFFE */  sh         $v1, -0x2($a1)
  .L800D80F8:
    /* B34A8 800D80F8 28C10020 */  slti       $at, $a2, 0x20
    /* B34AC 800D80FC 54200016 */  bnel       $at, $zero, .L800D8158
    /* B34B0 800D8100 28C10010 */   slti      $at, $a2, 0x10
    /* B34B4 800D8104 8C820000 */  lw         $v0, 0x0($a0)
    /* B34B8 800D8108 8C830004 */  lw         $v1, 0x4($a0)
    /* B34BC 800D810C 8C880008 */  lw         $t0, 0x8($a0)
    /* B34C0 800D8110 8C89000C */  lw         $t1, 0xC($a0)
    /* B34C4 800D8114 8C8A0010 */  lw         $t2, 0x10($a0)
    /* B34C8 800D8118 8C8B0014 */  lw         $t3, 0x14($a0)
    /* B34CC 800D811C 8C8C0018 */  lw         $t4, 0x18($a0)
    /* B34D0 800D8120 8C8D001C */  lw         $t5, 0x1C($a0)
    /* B34D4 800D8124 24840020 */  addiu      $a0, $a0, 0x20
    /* B34D8 800D8128 24A50020 */  addiu      $a1, $a1, 0x20
    /* B34DC 800D812C 24C6FFE0 */  addiu      $a2, $a2, -0x20
    /* B34E0 800D8130 ACA2FFE0 */  sw         $v0, -0x20($a1)
    /* B34E4 800D8134 ACA3FFE4 */  sw         $v1, -0x1C($a1)
    /* B34E8 800D8138 ACA8FFE8 */  sw         $t0, -0x18($a1)
    /* B34EC 800D813C ACA9FFEC */  sw         $t1, -0x14($a1)
    /* B34F0 800D8140 ACAAFFF0 */  sw         $t2, -0x10($a1)
    /* B34F4 800D8144 ACABFFF4 */  sw         $t3, -0xC($a1)
    /* B34F8 800D8148 ACACFFF8 */  sw         $t4, -0x8($a1)
    /* B34FC 800D814C 1000FFEA */  b          .L800D80F8
    /* B3500 800D8150 ACADFFFC */   sw        $t5, -0x4($a1)
  .L800D8154:
    /* B3504 800D8154 28C10010 */  slti       $at, $a2, 0x10
  .L800D8158:
    /* B3508 800D8158 5420000E */  bnel       $at, $zero, .L800D8194
    /* B350C 800D815C 28C10004 */   slti      $at, $a2, 0x4
    /* B3510 800D8160 8C820000 */  lw         $v0, 0x0($a0)
    /* B3514 800D8164 8C830004 */  lw         $v1, 0x4($a0)
    /* B3518 800D8168 8C880008 */  lw         $t0, 0x8($a0)
    /* B351C 800D816C 8C89000C */  lw         $t1, 0xC($a0)
    /* B3520 800D8170 24840010 */  addiu      $a0, $a0, 0x10
    /* B3524 800D8174 24A50010 */  addiu      $a1, $a1, 0x10
    /* B3528 800D8178 24C6FFF0 */  addiu      $a2, $a2, -0x10
    /* B352C 800D817C ACA2FFF0 */  sw         $v0, -0x10($a1)
    /* B3530 800D8180 ACA3FFF4 */  sw         $v1, -0xC($a1)
    /* B3534 800D8184 ACA8FFF8 */  sw         $t0, -0x8($a1)
    /* B3538 800D8188 1000FFF2 */  b          .L800D8154
    /* B353C 800D818C ACA9FFFC */   sw        $t1, -0x4($a1)
  .L800D8190:
    /* B3540 800D8190 28C10004 */  slti       $at, $a2, 0x4
  .L800D8194:
    /* B3544 800D8194 1420FFB5 */  bnez       $at, .L800D806C
    /* B3548 800D8198 00000000 */   nop
    /* B354C 800D819C 8C820000 */  lw         $v0, 0x0($a0)
    /* B3550 800D81A0 24840004 */  addiu      $a0, $a0, 0x4
    /* B3554 800D81A4 24A50004 */  addiu      $a1, $a1, 0x4
    /* B3558 800D81A8 24C6FFFC */  addiu      $a2, $a2, -0x4
    /* B355C 800D81AC 1000FFF8 */  b          .L800D8190
    /* B3560 800D81B0 ACA2FFFC */   sw        $v0, -0x4($a1)
    /* B3564 800D81B4 28C10010 */  slti       $at, $a2, 0x10
  .L800D81B8:
    /* B3568 800D81B8 00862020 */  add        $a0, $a0, $a2 /* handwritten instruction */
    /* B356C 800D81BC 14200005 */  bnez       $at, .L800D81D4
    /* B3570 800D81C0 00A62820 */   add       $a1, $a1, $a2 /* handwritten instruction */
    /* B3574 800D81C4 30820003 */  andi       $v0, $a0, 0x3
    /* B3578 800D81C8 30A30003 */  andi       $v1, $a1, 0x3
    /* B357C 800D81CC 1043000D */  beq        $v0, $v1, .L800D8204
    /* B3580 800D81D0 00000000 */   nop
  .L800D81D4:
    /* B3584 800D81D4 10C0FFAD */  beqz       $a2, .L800D808C
    /* B3588 800D81D8 00000000 */   nop
    /* B358C 800D81DC 2484FFFF */  addiu      $a0, $a0, -0x1
    /* B3590 800D81E0 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* B3594 800D81E4 00861823 */  subu       $v1, $a0, $a2
  .L800D81E8:
    /* B3598 800D81E8 80820000 */  lb         $v0, 0x0($a0)
    /* B359C 800D81EC 2484FFFF */  addiu      $a0, $a0, -0x1
    /* B35A0 800D81F0 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* B35A4 800D81F4 1483FFFC */  bne        $a0, $v1, .L800D81E8
    /* B35A8 800D81F8 A0A20001 */   sb        $v0, 0x1($a1)
    /* B35AC 800D81FC 03E00008 */  jr         $ra
    /* B35B0 800D8200 00E01025 */   or        $v0, $a3, $zero
  .L800D8204:
    /* B35B4 800D8204 10400018 */  beqz       $v0, .L800D8268
    /* B35B8 800D8208 24010003 */   addiu     $at, $zero, 0x3
    /* B35BC 800D820C 1041000F */  beq        $v0, $at, .L800D824C
    /* B35C0 800D8210 24010002 */   addiu     $at, $zero, 0x2
    /* B35C4 800D8214 50410008 */  beql       $v0, $at, .L800D8238
    /* B35C8 800D8218 8482FFFE */   lh        $v0, -0x2($a0)
    /* B35CC 800D821C 8082FFFF */  lb         $v0, -0x1($a0)
    /* B35D0 800D8220 2484FFFF */  addiu      $a0, $a0, -0x1
    /* B35D4 800D8224 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* B35D8 800D8228 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* B35DC 800D822C 1000000E */  b          .L800D8268
    /* B35E0 800D8230 A0A20000 */   sb        $v0, 0x0($a1)
    /* B35E4 800D8234 8482FFFE */  lh         $v0, -0x2($a0)
  .L800D8238:
    /* B35E8 800D8238 2484FFFE */  addiu      $a0, $a0, -0x2
    /* B35EC 800D823C 24A5FFFE */  addiu      $a1, $a1, -0x2
    /* B35F0 800D8240 24C6FFFE */  addiu      $a2, $a2, -0x2
    /* B35F4 800D8244 10000008 */  b          .L800D8268
    /* B35F8 800D8248 A4A20000 */   sh        $v0, 0x0($a1)
  .L800D824C:
    /* B35FC 800D824C 8082FFFF */  lb         $v0, -0x1($a0)
    /* B3600 800D8250 8483FFFD */  lh         $v1, -0x3($a0)
    /* B3604 800D8254 2484FFFD */  addiu      $a0, $a0, -0x3
    /* B3608 800D8258 24A5FFFD */  addiu      $a1, $a1, -0x3
    /* B360C 800D825C 24C6FFFD */  addiu      $a2, $a2, -0x3
    /* B3610 800D8260 A0A20002 */  sb         $v0, 0x2($a1)
    /* B3614 800D8264 A4A30000 */  sh         $v1, 0x0($a1)
  .L800D8268:
    /* B3618 800D8268 28C10020 */  slti       $at, $a2, 0x20
    /* B361C 800D826C 54200016 */  bnel       $at, $zero, .L800D82C8
    /* B3620 800D8270 28C10010 */   slti      $at, $a2, 0x10
    /* B3624 800D8274 8C82FFFC */  lw         $v0, -0x4($a0)
    /* B3628 800D8278 8C83FFF8 */  lw         $v1, -0x8($a0)
    /* B362C 800D827C 8C88FFF4 */  lw         $t0, -0xC($a0)
    /* B3630 800D8280 8C89FFF0 */  lw         $t1, -0x10($a0)
    /* B3634 800D8284 8C8AFFEC */  lw         $t2, -0x14($a0)
    /* B3638 800D8288 8C8BFFE8 */  lw         $t3, -0x18($a0)
    /* B363C 800D828C 8C8CFFE4 */  lw         $t4, -0x1C($a0)
    /* B3640 800D8290 8C8DFFE0 */  lw         $t5, -0x20($a0)
    /* B3644 800D8294 2484FFE0 */  addiu      $a0, $a0, -0x20
    /* B3648 800D8298 24A5FFE0 */  addiu      $a1, $a1, -0x20
    /* B364C 800D829C 24C6FFE0 */  addiu      $a2, $a2, -0x20
    /* B3650 800D82A0 ACA2001C */  sw         $v0, 0x1C($a1)
    /* B3654 800D82A4 ACA30018 */  sw         $v1, 0x18($a1)
    /* B3658 800D82A8 ACA80014 */  sw         $t0, 0x14($a1)
    /* B365C 800D82AC ACA90010 */  sw         $t1, 0x10($a1)
    /* B3660 800D82B0 ACAA000C */  sw         $t2, 0xC($a1)
    /* B3664 800D82B4 ACAB0008 */  sw         $t3, 0x8($a1)
    /* B3668 800D82B8 ACAC0004 */  sw         $t4, 0x4($a1)
    /* B366C 800D82BC 1000FFEA */  b          .L800D8268
    /* B3670 800D82C0 ACAD0000 */   sw        $t5, 0x0($a1)
  .L800D82C4:
    /* B3674 800D82C4 28C10010 */  slti       $at, $a2, 0x10
  .L800D82C8:
    /* B3678 800D82C8 5420000E */  bnel       $at, $zero, .L800D8304
    /* B367C 800D82CC 28C10004 */   slti      $at, $a2, 0x4
    /* B3680 800D82D0 8C82FFFC */  lw         $v0, -0x4($a0)
    /* B3684 800D82D4 8C83FFF8 */  lw         $v1, -0x8($a0)
    /* B3688 800D82D8 8C88FFF4 */  lw         $t0, -0xC($a0)
    /* B368C 800D82DC 8C89FFF0 */  lw         $t1, -0x10($a0)
    /* B3690 800D82E0 2484FFF0 */  addiu      $a0, $a0, -0x10
    /* B3694 800D82E4 24A5FFF0 */  addiu      $a1, $a1, -0x10
    /* B3698 800D82E8 24C6FFF0 */  addiu      $a2, $a2, -0x10
    /* B369C 800D82EC ACA2000C */  sw         $v0, 0xC($a1)
    /* B36A0 800D82F0 ACA30008 */  sw         $v1, 0x8($a1)
    /* B36A4 800D82F4 ACA80004 */  sw         $t0, 0x4($a1)
    /* B36A8 800D82F8 1000FFF2 */  b          .L800D82C4
    /* B36AC 800D82FC ACA90000 */   sw        $t1, 0x0($a1)
  .L800D8300:
    /* B36B0 800D8300 28C10004 */  slti       $at, $a2, 0x4
  .L800D8304:
    /* B36B4 800D8304 1420FFB3 */  bnez       $at, .L800D81D4
    /* B36B8 800D8308 00000000 */   nop
    /* B36BC 800D830C 8C82FFFC */  lw         $v0, -0x4($a0)
    /* B36C0 800D8310 2484FFFC */  addiu      $a0, $a0, -0x4
    /* B36C4 800D8314 24A5FFFC */  addiu      $a1, $a1, -0x4
    /* B36C8 800D8318 24C6FFFC */  addiu      $a2, $a2, -0x4
    /* B36CC 800D831C 1000FFF8 */  b          .L800D8300
    /* B36D0 800D8320 ACA20000 */   sw        $v0, 0x0($a1)
    /* B36D4 800D8324 00000000 */  nop
    /* B36D8 800D8328 00000000 */  nop
    /* B36DC 800D832C 00000000 */  nop
