.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

glabel _bzero
    /* AEDE0 800D3A30 28A1000C */  slti       $at, $a1, 0xC
    /* AEDE4 800D3A34 1420001D */  bnez       $at, .L800D3AAC
    /* AEDE8 800D3A38 00041823 */   negu      $v1, $a0
    /* AEDEC 800D3A3C 30630003 */  andi       $v1, $v1, 0x3
    /* AEDF0 800D3A40 10600003 */  beqz       $v1, .L800D3A50
    /* AEDF4 800D3A44 00A32823 */   subu      $a1, $a1, $v1
    /* AEDF8 800D3A48 A8800000 */  swl        $zero, 0x0($a0)
    /* AEDFC 800D3A4C 00832021 */  addu       $a0, $a0, $v1
  .L800D3A50:
    /* AEE00 800D3A50 2401FFE0 */  addiu      $at, $zero, -0x20
    /* AEE04 800D3A54 00A13824 */  and        $a3, $a1, $at
    /* AEE08 800D3A58 10E0000C */  beqz       $a3, .L800D3A8C
    /* AEE0C 800D3A5C 00A72823 */   subu      $a1, $a1, $a3
    /* AEE10 800D3A60 00E43821 */  addu       $a3, $a3, $a0
  .L800D3A64:
    /* AEE14 800D3A64 24840020 */  addiu      $a0, $a0, 0x20
    /* AEE18 800D3A68 AC80FFE0 */  sw         $zero, -0x20($a0)
    /* AEE1C 800D3A6C AC80FFE4 */  sw         $zero, -0x1C($a0)
    /* AEE20 800D3A70 AC80FFE8 */  sw         $zero, -0x18($a0)
    /* AEE24 800D3A74 AC80FFEC */  sw         $zero, -0x14($a0)
    /* AEE28 800D3A78 AC80FFF0 */  sw         $zero, -0x10($a0)
    /* AEE2C 800D3A7C AC80FFF4 */  sw         $zero, -0xC($a0)
    /* AEE30 800D3A80 AC80FFF8 */  sw         $zero, -0x8($a0)
    /* AEE34 800D3A84 1487FFF7 */  bne        $a0, $a3, .L800D3A64
    /* AEE38 800D3A88 AC80FFFC */   sw        $zero, -0x4($a0)
  .L800D3A8C:
    /* AEE3C 800D3A8C 2401FFFC */  addiu      $at, $zero, -0x4
    /* AEE40 800D3A90 00A13824 */  and        $a3, $a1, $at
    /* AEE44 800D3A94 10E00005 */  beqz       $a3, .L800D3AAC
    /* AEE48 800D3A98 00A72823 */   subu      $a1, $a1, $a3
    /* AEE4C 800D3A9C 00E43821 */  addu       $a3, $a3, $a0
  .L800D3AA0:
    /* AEE50 800D3AA0 24840004 */  addiu      $a0, $a0, 0x4
    /* AEE54 800D3AA4 1487FFFE */  bne        $a0, $a3, .L800D3AA0
    /* AEE58 800D3AA8 AC80FFFC */   sw        $zero, -0x4($a0)
  .L800D3AAC:
    /* AEE5C 800D3AAC 18A00005 */  blez       $a1, .L800D3AC4
    /* AEE60 800D3AB0 00000000 */   nop
    /* AEE64 800D3AB4 00A42821 */  addu       $a1, $a1, $a0
  .L800D3AB8:
    /* AEE68 800D3AB8 24840001 */  addiu      $a0, $a0, 0x1
    /* AEE6C 800D3ABC 1485FFFE */  bne        $a0, $a1, .L800D3AB8
    /* AEE70 800D3AC0 A080FFFF */   sb        $zero, -0x1($a0)
  .L800D3AC4:
    /* AEE74 800D3AC4 03E00008 */  jr         $ra
    /* AEE78 800D3AC8 00000000 */   nop
    /* AEE7C 800D3ACC 00000000 */  nop
