.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel __osExceptionPreamble
    /* B2AB0 800D7700 3C1A800D */  lui        $k0, %hi(__osException) /* handwritten instruction */
    /* B2AB4 800D7704 275A7710 */  addiu      $k0, $k0, %lo(__osException) /* handwritten instruction */
    /* B2AB8 800D7708 03400008 */  jr         $k0
    /* B2ABC 800D770C 00000000 */   nop

/* Handwritten function */
glabel __osException
    /* B2AC0 800D7710 3C1A8016 */  lui        $k0, %hi(__osThreadSave) /* handwritten instruction */
    /* B2AC4 800D7714 275A3CB0 */  addiu      $k0, $k0, %lo(__osThreadSave) /* handwritten instruction */
    /* B2AC8 800D7718 FF410020 */  sd         $at, 0x20($k0) /* handwritten instruction */
    /* B2ACC 800D771C 401B6000 */  mfc0       $k1, $12 /* handwritten instruction */
    /* B2AD0 800D7720 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* B2AD4 800D7724 2401FFFC */  addiu      $at, $zero, -0x4
    /* B2AD8 800D7728 0361D824 */  and        $k1, $k1, $at
    /* B2ADC 800D772C 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* B2AE0 800D7730 FF480058 */  sd         $t0, 0x58($k0) /* handwritten instruction */
    /* B2AE4 800D7734 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* B2AE8 800D7738 FF4A0068 */  sd         $t2, 0x68($k0) /* handwritten instruction */
    /* B2AEC 800D773C AF400018 */  sw         $zero, 0x18($k0) /* handwritten instruction */
    /* B2AF0 800D7740 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* B2AF4 800D7744 03404025 */  or         $t0, $k0, $zero
    /* B2AF8 800D7748 3C1A800F */  lui        $k0, %hi(__osRunningThread) /* handwritten instruction */
    /* B2AFC 800D774C 8F5AAD00 */  lw         $k0, %lo(__osRunningThread)($k0) /* handwritten instruction */
    /* B2B00 800D7750 DD090020 */  ld         $t1, 0x20($t0)
    /* B2B04 800D7754 FF490020 */  sd         $t1, 0x20($k0) /* handwritten instruction */
    /* B2B08 800D7758 DD090118 */  ld         $t1, 0x118($t0)
    /* B2B0C 800D775C FF490118 */  sd         $t1, 0x118($k0) /* handwritten instruction */
    /* B2B10 800D7760 DD090058 */  ld         $t1, 0x58($t0)
    /* B2B14 800D7764 FF490058 */  sd         $t1, 0x58($k0) /* handwritten instruction */
    /* B2B18 800D7768 DD090060 */  ld         $t1, 0x60($t0)
    /* B2B1C 800D776C FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* B2B20 800D7770 DD090068 */  ld         $t1, 0x68($t0)
    /* B2B24 800D7774 FF490068 */  sd         $t1, 0x68($k0) /* handwritten instruction */
    /* B2B28 800D7778 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* B2B2C 800D777C 00004012 */  mflo       $t0
    /* B2B30 800D7780 FF480108 */  sd         $t0, 0x108($k0) /* handwritten instruction */
    /* B2B34 800D7784 00004010 */  mfhi       $t0
    /* B2B38 800D7788 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* B2B3C 800D778C FF420028 */  sd         $v0, 0x28($k0) /* handwritten instruction */
    /* B2B40 800D7790 FF430030 */  sd         $v1, 0x30($k0) /* handwritten instruction */
    /* B2B44 800D7794 FF440038 */  sd         $a0, 0x38($k0) /* handwritten instruction */
    /* B2B48 800D7798 FF450040 */  sd         $a1, 0x40($k0) /* handwritten instruction */
    /* B2B4C 800D779C FF460048 */  sd         $a2, 0x48($k0) /* handwritten instruction */
    /* B2B50 800D77A0 FF470050 */  sd         $a3, 0x50($k0) /* handwritten instruction */
    /* B2B54 800D77A4 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* B2B58 800D77A8 FF4C0078 */  sd         $t4, 0x78($k0) /* handwritten instruction */
    /* B2B5C 800D77AC FF4D0080 */  sd         $t5, 0x80($k0) /* handwritten instruction */
    /* B2B60 800D77B0 FF4E0088 */  sd         $t6, 0x88($k0) /* handwritten instruction */
    /* B2B64 800D77B4 FF4F0090 */  sd         $t7, 0x90($k0) /* handwritten instruction */
    /* B2B68 800D77B8 FF500098 */  sd         $s0, 0x98($k0) /* handwritten instruction */
    /* B2B6C 800D77BC FF5100A0 */  sd         $s1, 0xA0($k0) /* handwritten instruction */
    /* B2B70 800D77C0 FF5200A8 */  sd         $s2, 0xA8($k0) /* handwritten instruction */
    /* B2B74 800D77C4 FF5300B0 */  sd         $s3, 0xB0($k0) /* handwritten instruction */
    /* B2B78 800D77C8 FF5400B8 */  sd         $s4, 0xB8($k0) /* handwritten instruction */
    /* B2B7C 800D77CC FF5500C0 */  sd         $s5, 0xC0($k0) /* handwritten instruction */
    /* B2B80 800D77D0 FF5600C8 */  sd         $s6, 0xC8($k0) /* handwritten instruction */
    /* B2B84 800D77D4 FF5700D0 */  sd         $s7, 0xD0($k0) /* handwritten instruction */
    /* B2B88 800D77D8 FF5800D8 */  sd         $t8, 0xD8($k0) /* handwritten instruction */
    /* B2B8C 800D77DC FF5900E0 */  sd         $t9, 0xE0($k0) /* handwritten instruction */
    /* B2B90 800D77E0 FF5C00E8 */  sd         $gp, 0xE8($k0) /* handwritten instruction */
    /* B2B94 800D77E4 FF5D00F0 */  sd         $sp, 0xF0($k0) /* handwritten instruction */
    /* B2B98 800D77E8 FF5E00F8 */  sd         $fp, 0xF8($k0) /* handwritten instruction */
    /* B2B9C 800D77EC FF5F0100 */  sd         $ra, 0x100($k0) /* handwritten instruction */
    /* B2BA0 800D77F0 11200011 */  beqz       $t1, .L800D7838
    /* B2BA4 800D77F4 FF480110 */   sd        $t0, 0x110($k0) /* handwritten instruction */
    /* B2BA8 800D77F8 3C08800F */  lui        $t0, %hi(__OSGlobalIntMask)
    /* B2BAC 800D77FC 2508A300 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* B2BB0 800D7800 8D080000 */  lw         $t0, 0x0($t0)
    /* B2BB4 800D7804 2401FFFF */  addiu      $at, $zero, -0x1
    /* B2BB8 800D7808 01015026 */  xor        $t2, $t0, $at
    /* B2BBC 800D780C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* B2BC0 800D7810 314AFF00 */  andi       $t2, $t2, 0xFF00
    /* B2BC4 800D7814 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* B2BC8 800D7818 012A6025 */  or         $t4, $t1, $t2
    /* B2BCC 800D781C 03615824 */  and        $t3, $k1, $at
    /* B2BD0 800D7820 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* B2BD4 800D7824 016C5825 */  or         $t3, $t3, $t4
    /* B2BD8 800D7828 01284824 */  and        $t1, $t1, $t0
    /* B2BDC 800D782C 0361D824 */  and        $k1, $k1, $at
    /* B2BE0 800D7830 AF4B0118 */  sw         $t3, 0x118($k0) /* handwritten instruction */
    /* B2BE4 800D7834 0369D825 */  or         $k1, $k1, $t1
  .L800D7838:
    /* B2BE8 800D7838 3C09A430 */  lui        $t1, %hi(MI_INTR_MASK_REG)
    /* B2BEC 800D783C 8D29000C */  lw         $t1, %lo(MI_INTR_MASK_REG)($t1)
    /* B2BF0 800D7840 1120000B */  beqz       $t1, .L800D7870
    /* B2BF4 800D7844 00000000 */   nop
    /* B2BF8 800D7848 3C08800F */  lui        $t0, %hi(__OSGlobalIntMask)
    /* B2BFC 800D784C 2508A300 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* B2C00 800D7850 8D080000 */  lw         $t0, 0x0($t0)
    /* B2C04 800D7854 8F4C0128 */  lw         $t4, 0x128($k0) /* handwritten instruction */
    /* B2C08 800D7858 2401FFFF */  addiu      $at, $zero, -0x1
    /* B2C0C 800D785C 00084402 */  srl        $t0, $t0, 16
    /* B2C10 800D7860 01014026 */  xor        $t0, $t0, $at
    /* B2C14 800D7864 3108003F */  andi       $t0, $t0, 0x3F
    /* B2C18 800D7868 010C4024 */  and        $t0, $t0, $t4
    /* B2C1C 800D786C 01284825 */  or         $t1, $t1, $t0
  .L800D7870:
    /* B2C20 800D7870 AF490128 */  sw         $t1, 0x128($k0) /* handwritten instruction */
    /* B2C24 800D7874 40087000 */  mfc0       $t0, $14 /* handwritten instruction */
    /* B2C28 800D7878 AF48011C */  sw         $t0, 0x11C($k0) /* handwritten instruction */
    /* B2C2C 800D787C 8F480018 */  lw         $t0, 0x18($k0) /* handwritten instruction */
    /* B2C30 800D7880 11000014 */  beqz       $t0, .L800D78D4
    /* B2C34 800D7884 00000000 */   nop
    /* B2C38 800D7888 4448F800 */  cfc1       $t0, $31
    /* B2C3C 800D788C 00000000 */  nop
    /* B2C40 800D7890 AF48012C */  sw         $t0, 0x12C($k0) /* handwritten instruction */
    /* B2C44 800D7894 F7400130 */  sdc1       $fv0, 0x130($k0)
    /* B2C48 800D7898 F7420138 */  sdc1       $fv1, 0x138($k0)
    /* B2C4C 800D789C F7440140 */  sdc1       $ft0, 0x140($k0)
    /* B2C50 800D78A0 F7460148 */  sdc1       $ft1, 0x148($k0)
    /* B2C54 800D78A4 F7480150 */  sdc1       $ft2, 0x150($k0)
    /* B2C58 800D78A8 F74A0158 */  sdc1       $ft3, 0x158($k0)
    /* B2C5C 800D78AC F74C0160 */  sdc1       $fa0, 0x160($k0)
    /* B2C60 800D78B0 F74E0168 */  sdc1       $fa1, 0x168($k0)
    /* B2C64 800D78B4 F7500170 */  sdc1       $ft4, 0x170($k0)
    /* B2C68 800D78B8 F7520178 */  sdc1       $ft5, 0x178($k0)
    /* B2C6C 800D78BC F7540180 */  sdc1       $fs0, 0x180($k0)
    /* B2C70 800D78C0 F7560188 */  sdc1       $fs1, 0x188($k0)
    /* B2C74 800D78C4 F7580190 */  sdc1       $fs2, 0x190($k0)
    /* B2C78 800D78C8 F75A0198 */  sdc1       $fs3, 0x198($k0)
    /* B2C7C 800D78CC F75C01A0 */  sdc1       $fs4, 0x1A0($k0)
    /* B2C80 800D78D0 F75E01A8 */  sdc1       $fs5, 0x1A8($k0)
  .L800D78D4:
    /* B2C84 800D78D4 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* B2C88 800D78D8 AF480120 */  sw         $t0, 0x120($k0) /* handwritten instruction */
    /* B2C8C 800D78DC 24090002 */  addiu      $t1, $zero, 0x2
    /* B2C90 800D78E0 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* B2C94 800D78E4 3109007C */  andi       $t1, $t0, 0x7C
    /* B2C98 800D78E8 240A0024 */  addiu      $t2, $zero, 0x24
    /* B2C9C 800D78EC 112A00B0 */  beq        $t1, $t2, .L800D7BB0
    /* B2CA0 800D78F0 00000000 */   nop
    /* B2CA4 800D78F4 240A002C */  addiu      $t2, $zero, 0x2C
    /* B2CA8 800D78F8 112A00FF */  beq        $t1, $t2, handle_CpU
    /* B2CAC 800D78FC 00000000 */   nop
    /* B2CB0 800D7900 240A0000 */  addiu      $t2, $zero, 0x0
    /* B2CB4 800D7904 152A00C3 */  bne        $t1, $t2, .L800D7C14
    /* B2CB8 800D7908 00000000 */   nop
    /* B2CBC 800D790C 03688024 */  and        $s0, $k1, $t0
  .L800D7910:
    /* B2CC0 800D7910 3209FF00 */  andi       $t1, $s0, 0xFF00
    /* B2CC4 800D7914 00095302 */  srl        $t2, $t1, 12
    /* B2CC8 800D7918 15400003 */  bnez       $t2, .L800D7928
    /* B2CCC 800D791C 00000000 */   nop
    /* B2CD0 800D7920 00095202 */  srl        $t2, $t1, 8
    /* B2CD4 800D7924 214A0010 */  addi       $t2, $t2, 0x10 /* handwritten instruction */
  .L800D7928:
    /* B2CD8 800D7928 3C01800F */  lui        $at, %hi(exceptasm_rodata_0000)
    /* B2CDC 800D792C 002A0821 */  addu       $at, $at, $t2
    /* B2CE0 800D7930 902A1360 */  lbu        $t2, %lo(exceptasm_rodata_0000)($at)
    /* B2CE4 800D7934 3C01800F */  lui        $at, %hi(exceptasm_rodata_0020)
    /* B2CE8 800D7938 002A0821 */  addu       $at, $at, $t2
    /* B2CEC 800D793C 8C2A1380 */  lw         $t2, %lo(exceptasm_rodata_0020)($at)
    /* B2CF0 800D7940 01400008 */  jr         $t2
    /* B2CF4 800D7944 00000000 */   nop
    /* B2CF8 800D7948 2401DFFF */  addiu      $at, $zero, -0x2001
    /* B2CFC 800D794C 1000FFF0 */  b          .L800D7910
    /* B2D00 800D7950 02018024 */   and       $s0, $s0, $at
    /* B2D04 800D7954 2401BFFF */  addiu      $at, $zero, -0x4001
    /* B2D08 800D7958 1000FFED */  b          .L800D7910
    /* B2D0C 800D795C 02018024 */   and       $s0, $s0, $at
    /* B2D10 800D7960 40095800 */  mfc0       $t1, $11 /* handwritten instruction */
    /* B2D14 800D7964 40895800 */  mtc0       $t1, $11 /* handwritten instruction */
    /* B2D18 800D7968 0C035F11 */  jal        send_mesg
    /* B2D1C 800D796C 24040018 */   addiu     $a0, $zero, 0x18
    /* B2D20 800D7970 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
    /* B2D24 800D7974 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
    /* B2D28 800D7978 1000FFE5 */  b          .L800D7910
    /* B2D2C 800D797C 02018024 */   and       $s0, $s0, $at
    /* B2D30 800D7980 2401F7FF */  addiu      $at, $zero, -0x801
    /* B2D34 800D7984 02018024 */  and        $s0, $s0, $at
    /* B2D38 800D7988 240A0004 */  addiu      $t2, $zero, 0x4
    /* B2D3C 800D798C 3C01800F */  lui        $at, %hi(__osHwIntTable)
    /* B2D40 800D7990 002A0821 */  addu       $at, $at, $t2
    /* B2D44 800D7994 8C2AAD90 */  lw         $t2, %lo(__osHwIntTable)($at)
    /* B2D48 800D7998 3C1D8016 */  lui        $sp, %hi(leoDiskStack)
    /* B2D4C 800D799C 27BD3E60 */  addiu      $sp, $sp, %lo(leoDiskStack)
    /* B2D50 800D79A0 24040010 */  addiu      $a0, $zero, 0x10
    /* B2D54 800D79A4 11400007 */  beqz       $t2, .L800D79C4
    /* B2D58 800D79A8 27BD0FF0 */   addiu     $sp, $sp, 0xFF0
    /* B2D5C 800D79AC 0140F809 */  jalr       $t2
    /* B2D60 800D79B0 00000000 */   nop
    /* B2D64 800D79B4 10400003 */  beqz       $v0, .L800D79C4
    /* B2D68 800D79B8 24040010 */   addiu     $a0, $zero, 0x10
    /* B2D6C 800D79BC 10000082 */  b          .L800D7BC8
    /* B2D70 800D79C0 00000000 */   nop
  .L800D79C4:
    /* B2D74 800D79C4 0C035F11 */  jal        send_mesg
    /* B2D78 800D79C8 00000000 */   nop
    /* B2D7C 800D79CC 1000FFD0 */  b          .L800D7910
    /* B2D80 800D79D0 00000000 */   nop
    /* B2D84 800D79D4 3C08800F */  lui        $t0, %hi(__OSGlobalIntMask)
    /* B2D88 800D79D8 2508A300 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* B2D8C 800D79DC 8D080000 */  lw         $t0, 0x0($t0)
    /* B2D90 800D79E0 3C11A430 */  lui        $s1, %hi(MI_INTR_REG)
    /* B2D94 800D79E4 8E310008 */  lw         $s1, %lo(MI_INTR_REG)($s1)
    /* B2D98 800D79E8 00084402 */  srl        $t0, $t0, 16
    /* B2D9C 800D79EC 02288824 */  and        $s1, $s1, $t0
    /* B2DA0 800D79F0 32290001 */  andi       $t1, $s1, 0x1
    /* B2DA4 800D79F4 11200013 */  beqz       $t1, .L800D7A44
    /* B2DA8 800D79F8 00000000 */   nop
    /* B2DAC 800D79FC 3C0CA404 */  lui        $t4, %hi(SP_STATUS_REG)
    /* B2DB0 800D7A00 8D8C0010 */  lw         $t4, %lo(SP_STATUS_REG)($t4)
    /* B2DB4 800D7A04 24090008 */  addiu      $t1, $zero, 0x8
    /* B2DB8 800D7A08 3C01A404 */  lui        $at, %hi(SP_STATUS_REG)
    /* B2DBC 800D7A0C 318C0300 */  andi       $t4, $t4, 0x300
    /* B2DC0 800D7A10 3231003E */  andi       $s1, $s1, 0x3E
    /* B2DC4 800D7A14 11800007 */  beqz       $t4, .L800D7A34
    /* B2DC8 800D7A18 AC290010 */   sw        $t1, %lo(SP_STATUS_REG)($at)
    /* B2DCC 800D7A1C 0C035F11 */  jal        send_mesg
    /* B2DD0 800D7A20 24040020 */   addiu     $a0, $zero, 0x20
    /* B2DD4 800D7A24 12200038 */  beqz       $s1, .L800D7B08
    /* B2DD8 800D7A28 00000000 */   nop
    /* B2DDC 800D7A2C 10000005 */  b          .L800D7A44
    /* B2DE0 800D7A30 00000000 */   nop
  .L800D7A34:
    /* B2DE4 800D7A34 0C035F11 */  jal        send_mesg
    /* B2DE8 800D7A38 24040058 */   addiu     $a0, $zero, 0x58
    /* B2DEC 800D7A3C 12200032 */  beqz       $s1, .L800D7B08
    /* B2DF0 800D7A40 00000000 */   nop
  .L800D7A44:
    /* B2DF4 800D7A44 32290008 */  andi       $t1, $s1, 0x8
    /* B2DF8 800D7A48 11200007 */  beqz       $t1, .L800D7A68
    /* B2DFC 800D7A4C 3C01A440 */   lui       $at, %hi(VI_CURRENT_REG)
    /* B2E00 800D7A50 32310037 */  andi       $s1, $s1, 0x37
    /* B2E04 800D7A54 AC200010 */  sw         $zero, %lo(VI_CURRENT_REG)($at)
    /* B2E08 800D7A58 0C035F11 */  jal        send_mesg
    /* B2E0C 800D7A5C 24040038 */   addiu     $a0, $zero, 0x38
    /* B2E10 800D7A60 12200029 */  beqz       $s1, .L800D7B08
    /* B2E14 800D7A64 00000000 */   nop
  .L800D7A68:
    /* B2E18 800D7A68 32290004 */  andi       $t1, $s1, 0x4
    /* B2E1C 800D7A6C 11200009 */  beqz       $t1, .L800D7A94
    /* B2E20 800D7A70 00000000 */   nop
    /* B2E24 800D7A74 24090001 */  addiu      $t1, $zero, 0x1
    /* B2E28 800D7A78 3C01A450 */  lui        $at, %hi(AI_STATUS_REG)
    /* B2E2C 800D7A7C 3231003B */  andi       $s1, $s1, 0x3B
    /* B2E30 800D7A80 AC29000C */  sw         $t1, %lo(AI_STATUS_REG)($at)
    /* B2E34 800D7A84 0C035F11 */  jal        send_mesg
    /* B2E38 800D7A88 24040030 */   addiu     $a0, $zero, 0x30
    /* B2E3C 800D7A8C 1220001E */  beqz       $s1, .L800D7B08
    /* B2E40 800D7A90 00000000 */   nop
  .L800D7A94:
    /* B2E44 800D7A94 32290002 */  andi       $t1, $s1, 0x2
    /* B2E48 800D7A98 11200007 */  beqz       $t1, .L800D7AB8
    /* B2E4C 800D7A9C 3C01A480 */   lui       $at, %hi(SI_STATUS_REG)
    /* B2E50 800D7AA0 3231003D */  andi       $s1, $s1, 0x3D
    /* B2E54 800D7AA4 AC200018 */  sw         $zero, %lo(SI_STATUS_REG)($at)
    /* B2E58 800D7AA8 0C035F11 */  jal        send_mesg
    /* B2E5C 800D7AAC 24040028 */   addiu     $a0, $zero, 0x28
    /* B2E60 800D7AB0 12200015 */  beqz       $s1, .L800D7B08
    /* B2E64 800D7AB4 00000000 */   nop
  .L800D7AB8:
    /* B2E68 800D7AB8 32290010 */  andi       $t1, $s1, 0x10
    /* B2E6C 800D7ABC 11200009 */  beqz       $t1, .L800D7AE4
    /* B2E70 800D7AC0 00000000 */   nop
    /* B2E74 800D7AC4 24090002 */  addiu      $t1, $zero, 0x2
    /* B2E78 800D7AC8 3C01A460 */  lui        $at, %hi(PI_STATUS_REG)
    /* B2E7C 800D7ACC 3231002F */  andi       $s1, $s1, 0x2F
    /* B2E80 800D7AD0 AC290010 */  sw         $t1, %lo(PI_STATUS_REG)($at)
    /* B2E84 800D7AD4 0C035F11 */  jal        send_mesg
    /* B2E88 800D7AD8 24040040 */   addiu     $a0, $zero, 0x40
    /* B2E8C 800D7ADC 1220000A */  beqz       $s1, .L800D7B08
    /* B2E90 800D7AE0 00000000 */   nop
  .L800D7AE4:
    /* B2E94 800D7AE4 32290020 */  andi       $t1, $s1, 0x20
    /* B2E98 800D7AE8 11200007 */  beqz       $t1, .L800D7B08
    /* B2E9C 800D7AEC 00000000 */   nop
    /* B2EA0 800D7AF0 24090800 */  addiu      $t1, $zero, 0x800
    /* B2EA4 800D7AF4 3C01A430 */  lui        $at, %hi(MI_MODE_REG)
    /* B2EA8 800D7AF8 3231001F */  andi       $s1, $s1, 0x1F
    /* B2EAC 800D7AFC AC290000 */  sw         $t1, %lo(MI_MODE_REG)($at)
    /* B2EB0 800D7B00 0C035F11 */  jal        send_mesg
    /* B2EB4 800D7B04 24040048 */   addiu     $a0, $zero, 0x48
  .L800D7B08:
    /* B2EB8 800D7B08 2401FBFF */  addiu      $at, $zero, -0x401
    /* B2EBC 800D7B0C 1000FF80 */  b          .L800D7910
    /* B2EC0 800D7B10 02018024 */   and       $s0, $s0, $at
    /* B2EC4 800D7B14 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* B2EC8 800D7B18 2401EFFF */  addiu      $at, $zero, -0x1001
    /* B2ECC 800D7B1C 3C09800F */  lui        $t1, %hi(__osShutdown)
    /* B2ED0 800D7B20 0361D824 */  and        $k1, $k1, $at
    /* B2ED4 800D7B24 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* B2ED8 800D7B28 2529A2FC */  addiu      $t1, $t1, %lo(__osShutdown)
    /* B2EDC 800D7B2C 8D2A0000 */  lw         $t2, 0x0($t1)
    /* B2EE0 800D7B30 11400003 */  beqz       $t2, .L800D7B40
    /* B2EE4 800D7B34 2401EFFF */   addiu     $at, $zero, -0x1001
    /* B2EE8 800D7B38 10000023 */  b          .L800D7BC8
    /* B2EEC 800D7B3C 02018024 */   and       $s0, $s0, $at
  .L800D7B40:
    /* B2EF0 800D7B40 240A0001 */  addiu      $t2, $zero, 0x1
    /* B2EF4 800D7B44 AD2A0000 */  sw         $t2, 0x0($t1)
    /* B2EF8 800D7B48 0C035F11 */  jal        send_mesg
    /* B2EFC 800D7B4C 24040070 */   addiu     $a0, $zero, 0x70
    /* B2F00 800D7B50 3C0A800F */  lui        $t2, %hi(__osRunQueue)
    /* B2F04 800D7B54 8D4AACF8 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* B2F08 800D7B58 2401EFFF */  addiu      $at, $zero, -0x1001
    /* B2F0C 800D7B5C 02018024 */  and        $s0, $s0, $at
    /* B2F10 800D7B60 8D5B0118 */  lw         $k1, 0x118($t2) /* handwritten instruction */
    /* B2F14 800D7B64 0361D824 */  and        $k1, $k1, $at
    /* B2F18 800D7B68 10000017 */  b          .L800D7BC8
    /* B2F1C 800D7B6C AD5B0118 */   sw        $k1, 0x118($t2) /* handwritten instruction */
    /* B2F20 800D7B70 2401FDFF */  addiu      $at, $zero, -0x201
    /* B2F24 800D7B74 01014024 */  and        $t0, $t0, $at
    /* B2F28 800D7B78 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* B2F2C 800D7B7C 0C035F11 */  jal        send_mesg
    /* B2F30 800D7B80 24040008 */   addiu     $a0, $zero, 0x8
    /* B2F34 800D7B84 2401FDFF */  addiu      $at, $zero, -0x201
    /* B2F38 800D7B88 1000FF61 */  b          .L800D7910
    /* B2F3C 800D7B8C 02018024 */   and       $s0, $s0, $at
    /* B2F40 800D7B90 2401FEFF */  addiu      $at, $zero, -0x101
    /* B2F44 800D7B94 01014024 */  and        $t0, $t0, $at
    /* B2F48 800D7B98 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* B2F4C 800D7B9C 0C035F11 */  jal        send_mesg
    /* B2F50 800D7BA0 24040000 */   addiu     $a0, $zero, 0x0
    /* B2F54 800D7BA4 2401FEFF */  addiu      $at, $zero, -0x101
    /* B2F58 800D7BA8 1000FF59 */  b          .L800D7910
    /* B2F5C 800D7BAC 02018024 */   and       $s0, $s0, $at
  .L800D7BB0:
    /* B2F60 800D7BB0 24090001 */  addiu      $t1, $zero, 0x1
    /* B2F64 800D7BB4 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* B2F68 800D7BB8 0C035F11 */  jal        send_mesg
    /* B2F6C 800D7BBC 24040050 */   addiu     $a0, $zero, 0x50
    /* B2F70 800D7BC0 10000001 */  b          .L800D7BC8
    /* B2F74 800D7BC4 00000000 */   nop
  .L800D7BC8:
    /* B2F78 800D7BC8 3C0A800F */  lui        $t2, %hi(__osRunQueue)
    /* B2F7C 800D7BCC 8D4AACF8 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* B2F80 800D7BD0 8F490004 */  lw         $t1, 0x4($k0) /* handwritten instruction */
    /* B2F84 800D7BD4 8D4B0004 */  lw         $t3, 0x4($t2)
    /* B2F88 800D7BD8 012B082A */  slt        $at, $t1, $t3
    /* B2F8C 800D7BDC 10200007 */  beqz       $at, .L800D7BFC
    /* B2F90 800D7BE0 00000000 */   nop
    /* B2F94 800D7BE4 3C04800F */  lui        $a0, %hi(__osRunQueue)
    /* B2F98 800D7BE8 03402825 */  or         $a1, $k0, $zero
    /* B2F9C 800D7BEC 0C035F8B */  jal        __osEnqueueThread
    /* B2FA0 800D7BF0 2484ACF8 */   addiu     $a0, $a0, %lo(__osRunQueue)

/* Handwritten function */
glabel __rmonPanic
    /* B2FA4 800D7BF4 08035FA1 */  j          __osDispatchThread
    /* B2FA8 800D7BF8 00000000 */   nop
  .L800D7BFC:
    /* B2FAC 800D7BFC 3C09800F */  lui        $t1, %hi(__osRunQueue)
    /* B2FB0 800D7C00 2529ACF8 */  addiu      $t1, $t1, %lo(__osRunQueue)
    /* B2FB4 800D7C04 8D2A0000 */  lw         $t2, 0x0($t1)
    /* B2FB8 800D7C08 AF4A0000 */  sw         $t2, 0x0($k0) /* handwritten instruction */
    /* B2FBC 800D7C0C 08035FA1 */  j          __osDispatchThread
    /* B2FC0 800D7C10 AD3A0000 */   sw        $k0, 0x0($t1) /* handwritten instruction */
  .L800D7C14:
    /* B2FC4 800D7C14 3C01800F */  lui        $at, %hi(__osFaultedThread)
    /* B2FC8 800D7C18 AC3AAD04 */  sw         $k0, %lo(__osFaultedThread)($at) /* handwritten instruction */
    /* B2FCC 800D7C1C 24090001 */  addiu      $t1, $zero, 0x1
    /* B2FD0 800D7C20 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* B2FD4 800D7C24 24090002 */  addiu      $t1, $zero, 0x2
    /* B2FD8 800D7C28 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* B2FDC 800D7C2C 400A4000 */  mfc0       $t2, $8 /* handwritten instruction */
    /* B2FE0 800D7C30 AF4A0124 */  sw         $t2, 0x124($k0) /* handwritten instruction */
    /* B2FE4 800D7C34 0C035F11 */  jal        send_mesg
    /* B2FE8 800D7C38 24040060 */   addiu     $a0, $zero, 0x60
    /* B2FEC 800D7C3C 08035FA1 */  j          __osDispatchThread
    /* B2FF0 800D7C40 00000000 */   nop

glabel send_mesg
    /* B2FF4 800D7C44 3C0A8016 */  lui        $t2, %hi(__osEventStateTab)
    /* B2FF8 800D7C48 254A27A0 */  addiu      $t2, $t2, %lo(__osEventStateTab)
    /* B2FFC 800D7C4C 01445021 */  addu       $t2, $t2, $a0
    /* B3000 800D7C50 8D490000 */  lw         $t1, 0x0($t2)
    /* B3004 800D7C54 03E09025 */  or         $s2, $ra, $zero
    /* B3008 800D7C58 11200025 */  beqz       $t1, .L800D7CF0
    /* B300C 800D7C5C 00000000 */   nop
    /* B3010 800D7C60 8D2B0008 */  lw         $t3, 0x8($t1)
    /* B3014 800D7C64 8D2C0010 */  lw         $t4, 0x10($t1)
    /* B3018 800D7C68 016C082A */  slt        $at, $t3, $t4
    /* B301C 800D7C6C 10200020 */  beqz       $at, .L800D7CF0
    /* B3020 800D7C70 00000000 */   nop
    /* B3024 800D7C74 8D2D000C */  lw         $t5, 0xC($t1)
    /* B3028 800D7C78 01AB6821 */  addu       $t5, $t5, $t3
    /* B302C 800D7C7C 01AC001A */  div        $zero, $t5, $t4
    /* B3030 800D7C80 15800002 */  bnez       $t4, .L800D7C8C
    /* B3034 800D7C84 00000000 */   nop
    /* B3038 800D7C88 0007000D */  break      7
  .L800D7C8C:
    /* B303C 800D7C8C 2401FFFF */  addiu      $at, $zero, -0x1
    /* B3040 800D7C90 15810004 */  bne        $t4, $at, .L800D7CA4
    /* B3044 800D7C94 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* B3048 800D7C98 15A10002 */  bne        $t5, $at, .L800D7CA4
    /* B304C 800D7C9C 00000000 */   nop
    /* B3050 800D7CA0 0006000D */  break      6
  .L800D7CA4:
    /* B3054 800D7CA4 8D2C0014 */  lw         $t4, 0x14($t1)
    /* B3058 800D7CA8 00006810 */  mfhi       $t5
    /* B305C 800D7CAC 000D6880 */  sll        $t5, $t5, 2
    /* B3060 800D7CB0 018D6021 */  addu       $t4, $t4, $t5
    /* B3064 800D7CB4 8D4D0004 */  lw         $t5, 0x4($t2)
    /* B3068 800D7CB8 256A0001 */  addiu      $t2, $t3, 0x1
    /* B306C 800D7CBC AD8D0000 */  sw         $t5, 0x0($t4)
    /* B3070 800D7CC0 AD2A0008 */  sw         $t2, 0x8($t1)
    /* B3074 800D7CC4 8D2A0000 */  lw         $t2, 0x0($t1)
    /* B3078 800D7CC8 8D4B0000 */  lw         $t3, 0x0($t2)
    /* B307C 800D7CCC 11600008 */  beqz       $t3, .L800D7CF0
    /* B3080 800D7CD0 00000000 */   nop
    /* B3084 800D7CD4 0C035F9D */  jal        __osPopThread
    /* B3088 800D7CD8 01202025 */   or        $a0, $t1, $zero
    /* B308C 800D7CDC 00405025 */  or         $t2, $v0, $zero
    /* B3090 800D7CE0 3C04800F */  lui        $a0, %hi(__osRunQueue)
    /* B3094 800D7CE4 01402825 */  or         $a1, $t2, $zero
    /* B3098 800D7CE8 0C035F8B */  jal        __osEnqueueThread
    /* B309C 800D7CEC 2484ACF8 */   addiu     $a0, $a0, %lo(__osRunQueue)
  .L800D7CF0:
    /* B30A0 800D7CF0 02400008 */  jr         $s2
    /* B30A4 800D7CF4 00000000 */   nop

/* Handwritten function */
glabel handle_CpU
    /* B30A8 800D7CF8 3C013000 */  lui        $at, (0x30000000 >> 16)
    /* B30AC 800D7CFC 01014824 */  and        $t1, $t0, $at
    /* B30B0 800D7D00 00094F02 */  srl        $t1, $t1, 28
    /* B30B4 800D7D04 240A0001 */  addiu      $t2, $zero, 0x1
    /* B30B8 800D7D08 152AFFC2 */  bne        $t1, $t2, .L800D7C14
    /* B30BC 800D7D0C 00000000 */   nop
    /* B30C0 800D7D10 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* B30C4 800D7D14 3C012000 */  lui        $at, (0x20000000 >> 16)
    /* B30C8 800D7D18 24090001 */  addiu      $t1, $zero, 0x1
    /* B30CC 800D7D1C 0361D825 */  or         $k1, $k1, $at
    /* B30D0 800D7D20 AF490018 */  sw         $t1, 0x18($k0) /* handwritten instruction */
    /* B30D4 800D7D24 1000FFB5 */  b          .L800D7BFC
    /* B30D8 800D7D28 AF5B0118 */   sw        $k1, 0x118($k0) /* handwritten instruction */

/* Handwritten function */
glabel __osEnqueueAndYield
    /* B30DC 800D7D2C 3C05800F */  lui        $a1, %hi(__osRunningThread)
    /* B30E0 800D7D30 8CA5AD00 */  lw         $a1, %lo(__osRunningThread)($a1)
    /* B30E4 800D7D34 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* B30E8 800D7D38 8CBB0018 */  lw         $k1, 0x18($a1) /* handwritten instruction */
    /* B30EC 800D7D3C 35080002 */  ori        $t0, $t0, 0x2
    /* B30F0 800D7D40 ACA80118 */  sw         $t0, 0x118($a1)
    /* B30F4 800D7D44 FCB00098 */  sd         $s0, 0x98($a1)
    /* B30F8 800D7D48 FCB100A0 */  sd         $s1, 0xA0($a1)
    /* B30FC 800D7D4C FCB200A8 */  sd         $s2, 0xA8($a1)
    /* B3100 800D7D50 FCB300B0 */  sd         $s3, 0xB0($a1)
    /* B3104 800D7D54 FCB400B8 */  sd         $s4, 0xB8($a1)
    /* B3108 800D7D58 FCB500C0 */  sd         $s5, 0xC0($a1)
    /* B310C 800D7D5C FCB600C8 */  sd         $s6, 0xC8($a1)
    /* B3110 800D7D60 FCB700D0 */  sd         $s7, 0xD0($a1)
    /* B3114 800D7D64 FCBC00E8 */  sd         $gp, 0xE8($a1)
    /* B3118 800D7D68 FCBD00F0 */  sd         $sp, 0xF0($a1)
    /* B311C 800D7D6C FCBE00F8 */  sd         $fp, 0xF8($a1)
    /* B3120 800D7D70 FCBF0100 */  sd         $ra, 0x100($a1)
    /* B3124 800D7D74 13600009 */  beqz       $k1, .L800D7D9C /* handwritten instruction */
    /* B3128 800D7D78 ACBF011C */   sw        $ra, 0x11C($a1)
    /* B312C 800D7D7C 445BF800 */  cfc1       $k1, $31
    /* B3130 800D7D80 F4B40180 */  sdc1       $fs0, 0x180($a1)
    /* B3134 800D7D84 F4B60188 */  sdc1       $fs1, 0x188($a1)
    /* B3138 800D7D88 F4B80190 */  sdc1       $fs2, 0x190($a1)
    /* B313C 800D7D8C F4BA0198 */  sdc1       $fs3, 0x198($a1)
    /* B3140 800D7D90 F4BC01A0 */  sdc1       $fs4, 0x1A0($a1)
    /* B3144 800D7D94 F4BE01A8 */  sdc1       $fs5, 0x1A8($a1)
    /* B3148 800D7D98 ACBB012C */  sw         $k1, 0x12C($a1) /* handwritten instruction */
  .L800D7D9C:
    /* B314C 800D7D9C 8CBB0118 */  lw         $k1, 0x118($a1) /* handwritten instruction */
    /* B3150 800D7DA0 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* B3154 800D7DA4 1120000D */  beqz       $t1, .L800D7DDC
    /* B3158 800D7DA8 00000000 */   nop
    /* B315C 800D7DAC 3C08800F */  lui        $t0, %hi(__OSGlobalIntMask)
    /* B3160 800D7DB0 2508A300 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* B3164 800D7DB4 8D080000 */  lw         $t0, 0x0($t0)
    /* B3168 800D7DB8 2401FFFF */  addiu      $at, $zero, -0x1
    /* B316C 800D7DBC 01014026 */  xor        $t0, $t0, $at
    /* B3170 800D7DC0 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* B3174 800D7DC4 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* B3178 800D7DC8 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* B317C 800D7DCC 01284825 */  or         $t1, $t1, $t0
    /* B3180 800D7DD0 0361D824 */  and        $k1, $k1, $at
    /* B3184 800D7DD4 0369D825 */  or         $k1, $k1, $t1
    /* B3188 800D7DD8 ACBB0118 */  sw         $k1, 0x118($a1) /* handwritten instruction */
  .L800D7DDC:
    /* B318C 800D7DDC 3C1BA430 */  lui        $k1, %hi(MI_INTR_MASK_REG) /* handwritten instruction */
    /* B3190 800D7DE0 8F7B000C */  lw         $k1, %lo(MI_INTR_MASK_REG)($k1) /* handwritten instruction */
    /* B3194 800D7DE4 1360000B */  beqz       $k1, .L800D7E14 /* handwritten instruction */
    /* B3198 800D7DE8 00000000 */   nop
    /* B319C 800D7DEC 3C1A800F */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* B31A0 800D7DF0 275AA300 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* B31A4 800D7DF4 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* B31A8 800D7DF8 8CA80128 */  lw         $t0, 0x128($a1)
    /* B31AC 800D7DFC 2401FFFF */  addiu      $at, $zero, -0x1
    /* B31B0 800D7E00 001AD402 */  srl        $k0, $k0, 16
    /* B31B4 800D7E04 0341D026 */  xor        $k0, $k0, $at
    /* B31B8 800D7E08 335A003F */  andi       $k0, $k0, 0x3F /* handwritten instruction */
    /* B31BC 800D7E0C 0348D024 */  and        $k0, $k0, $t0
    /* B31C0 800D7E10 037AD825 */  or         $k1, $k1, $k0
  .L800D7E14:
    /* B31C4 800D7E14 10800003 */  beqz       $a0, .L800D7E24
    /* B31C8 800D7E18 ACBB0128 */   sw        $k1, 0x128($a1) /* handwritten instruction */
    /* B31CC 800D7E1C 0C035F8B */  jal        __osEnqueueThread
    /* B31D0 800D7E20 00000000 */   nop
  .L800D7E24:
    /* B31D4 800D7E24 08035FA1 */  j          __osDispatchThread
    /* B31D8 800D7E28 00000000 */   nop

glabel __osEnqueueThread
    /* B31DC 800D7E2C 8C980000 */  lw         $t8, 0x0($a0)
    /* B31E0 800D7E30 8CAF0004 */  lw         $t7, 0x4($a1)
    /* B31E4 800D7E34 0080C825 */  or         $t9, $a0, $zero
    /* B31E8 800D7E38 8F0E0004 */  lw         $t6, 0x4($t8)
    /* B31EC 800D7E3C 01CF082A */  slt        $at, $t6, $t7
    /* B31F0 800D7E40 14200007 */  bnez       $at, .L800D7E60
    /* B31F4 800D7E44 00000000 */   nop
  .L800D7E48:
    /* B31F8 800D7E48 0300C825 */  or         $t9, $t8, $zero
    /* B31FC 800D7E4C 8F180000 */  lw         $t8, 0x0($t8)
    /* B3200 800D7E50 8F0E0004 */  lw         $t6, 0x4($t8)
    /* B3204 800D7E54 01CF082A */  slt        $at, $t6, $t7
    /* B3208 800D7E58 1020FFFB */  beqz       $at, .L800D7E48
    /* B320C 800D7E5C 00000000 */   nop
  .L800D7E60:
    /* B3210 800D7E60 8F380000 */  lw         $t8, 0x0($t9)
    /* B3214 800D7E64 ACB80000 */  sw         $t8, 0x0($a1)
    /* B3218 800D7E68 AF250000 */  sw         $a1, 0x0($t9)
    /* B321C 800D7E6C 03E00008 */  jr         $ra
    /* B3220 800D7E70 ACA40008 */   sw        $a0, 0x8($a1)

glabel __osPopThread
    /* B3224 800D7E74 8C820000 */  lw         $v0, 0x0($a0)
    /* B3228 800D7E78 8C590000 */  lw         $t9, 0x0($v0)
    /* B322C 800D7E7C 03E00008 */  jr         $ra
    /* B3230 800D7E80 AC990000 */   sw        $t9, 0x0($a0)

/* Handwritten function */
glabel __osDispatchThread
    /* B3234 800D7E84 3C04800F */  lui        $a0, %hi(__osRunQueue)
    /* B3238 800D7E88 0C035F9D */  jal        __osPopThread
    /* B323C 800D7E8C 2484ACF8 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* B3240 800D7E90 3C01800F */  lui        $at, %hi(__osRunningThread)
    /* B3244 800D7E94 AC22AD00 */  sw         $v0, %lo(__osRunningThread)($at)
    /* B3248 800D7E98 24080004 */  addiu      $t0, $zero, 0x4
    /* B324C 800D7E9C A4480010 */  sh         $t0, 0x10($v0)
    /* B3250 800D7EA0 0040D025 */  or         $k0, $v0, $zero
    /* B3254 800D7EA4 3C08800F */  lui        $t0, %hi(__OSGlobalIntMask)
    /* B3258 800D7EA8 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* B325C 800D7EAC 2508A300 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* B3260 800D7EB0 8D080000 */  lw         $t0, 0x0($t0)
    /* B3264 800D7EB4 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* B3268 800D7EB8 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* B326C 800D7EBC 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* B3270 800D7EC0 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* B3274 800D7EC4 01284824 */  and        $t1, $t1, $t0
    /* B3278 800D7EC8 0361D824 */  and        $k1, $k1, $at
    /* B327C 800D7ECC 0369D825 */  or         $k1, $k1, $t1
    /* B3280 800D7ED0 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* B3284 800D7ED4 DF5B0108 */  ld         $k1, 0x108($k0) /* handwritten instruction */
    /* B3288 800D7ED8 DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
    /* B328C 800D7EDC DF420028 */  ld         $v0, 0x28($k0) /* handwritten instruction */
    /* B3290 800D7EE0 03600013 */  mtlo       $k1
    /* B3294 800D7EE4 DF5B0110 */  ld         $k1, 0x110($k0) /* handwritten instruction */
    /* B3298 800D7EE8 DF430030 */  ld         $v1, 0x30($k0) /* handwritten instruction */
    /* B329C 800D7EEC DF440038 */  ld         $a0, 0x38($k0) /* handwritten instruction */
    /* B32A0 800D7EF0 DF450040 */  ld         $a1, 0x40($k0) /* handwritten instruction */
    /* B32A4 800D7EF4 DF460048 */  ld         $a2, 0x48($k0) /* handwritten instruction */
    /* B32A8 800D7EF8 DF470050 */  ld         $a3, 0x50($k0) /* handwritten instruction */
    /* B32AC 800D7EFC DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
    /* B32B0 800D7F00 DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
    /* B32B4 800D7F04 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
    /* B32B8 800D7F08 DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* B32BC 800D7F0C DF4C0078 */  ld         $t4, 0x78($k0) /* handwritten instruction */
    /* B32C0 800D7F10 DF4D0080 */  ld         $t5, 0x80($k0) /* handwritten instruction */
    /* B32C4 800D7F14 DF4E0088 */  ld         $t6, 0x88($k0) /* handwritten instruction */
    /* B32C8 800D7F18 DF4F0090 */  ld         $t7, 0x90($k0) /* handwritten instruction */
    /* B32CC 800D7F1C DF500098 */  ld         $s0, 0x98($k0) /* handwritten instruction */
    /* B32D0 800D7F20 DF5100A0 */  ld         $s1, 0xA0($k0) /* handwritten instruction */
    /* B32D4 800D7F24 DF5200A8 */  ld         $s2, 0xA8($k0) /* handwritten instruction */
    /* B32D8 800D7F28 DF5300B0 */  ld         $s3, 0xB0($k0) /* handwritten instruction */
    /* B32DC 800D7F2C DF5400B8 */  ld         $s4, 0xB8($k0) /* handwritten instruction */
    /* B32E0 800D7F30 DF5500C0 */  ld         $s5, 0xC0($k0) /* handwritten instruction */
    /* B32E4 800D7F34 DF5600C8 */  ld         $s6, 0xC8($k0) /* handwritten instruction */
    /* B32E8 800D7F38 DF5700D0 */  ld         $s7, 0xD0($k0) /* handwritten instruction */
    /* B32EC 800D7F3C DF5800D8 */  ld         $t8, 0xD8($k0) /* handwritten instruction */
    /* B32F0 800D7F40 DF5900E0 */  ld         $t9, 0xE0($k0) /* handwritten instruction */
    /* B32F4 800D7F44 DF5C00E8 */  ld         $gp, 0xE8($k0) /* handwritten instruction */
    /* B32F8 800D7F48 03600011 */  mthi       $k1
    /* B32FC 800D7F4C DF5D00F0 */  ld         $sp, 0xF0($k0) /* handwritten instruction */
    /* B3300 800D7F50 DF5E00F8 */  ld         $fp, 0xF8($k0) /* handwritten instruction */
    /* B3304 800D7F54 DF5F0100 */  ld         $ra, 0x100($k0) /* handwritten instruction */
    /* B3308 800D7F58 8F5B011C */  lw         $k1, 0x11C($k0) /* handwritten instruction */
    /* B330C 800D7F5C 409B7000 */  mtc0       $k1, $14 /* handwritten instruction */
    /* B3310 800D7F60 8F5B0018 */  lw         $k1, 0x18($k0) /* handwritten instruction */
    /* B3314 800D7F64 13600013 */  beqz       $k1, .L800D7FB4 /* handwritten instruction */
    /* B3318 800D7F68 00000000 */   nop
    /* B331C 800D7F6C 8F5B012C */  lw         $k1, 0x12C($k0) /* handwritten instruction */
    /* B3320 800D7F70 44DBF800 */  ctc1       $k1, $31
    /* B3324 800D7F74 D7400130 */  ldc1       $fv0, 0x130($k0)
    /* B3328 800D7F78 D7420138 */  ldc1       $fv1, 0x138($k0)
    /* B332C 800D7F7C D7440140 */  ldc1       $ft0, 0x140($k0)
    /* B3330 800D7F80 D7460148 */  ldc1       $ft1, 0x148($k0)
    /* B3334 800D7F84 D7480150 */  ldc1       $ft2, 0x150($k0)
    /* B3338 800D7F88 D74A0158 */  ldc1       $ft3, 0x158($k0)
    /* B333C 800D7F8C D74C0160 */  ldc1       $fa0, 0x160($k0)
    /* B3340 800D7F90 D74E0168 */  ldc1       $fa1, 0x168($k0)
    /* B3344 800D7F94 D7500170 */  ldc1       $ft4, 0x170($k0)
    /* B3348 800D7F98 D7520178 */  ldc1       $ft5, 0x178($k0)
    /* B334C 800D7F9C D7540180 */  ldc1       $fs0, 0x180($k0)
    /* B3350 800D7FA0 D7560188 */  ldc1       $fs1, 0x188($k0)
    /* B3354 800D7FA4 D7580190 */  ldc1       $fs2, 0x190($k0)
    /* B3358 800D7FA8 D75A0198 */  ldc1       $fs3, 0x198($k0)
    /* B335C 800D7FAC D75C01A0 */  ldc1       $fs4, 0x1A0($k0)
    /* B3360 800D7FB0 D75E01A8 */  ldc1       $fs5, 0x1A8($k0)
  .L800D7FB4:
    /* B3364 800D7FB4 8F5B0128 */  lw         $k1, 0x128($k0) /* handwritten instruction */
    /* B3368 800D7FB8 3C1A800F */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* B336C 800D7FBC 275AA300 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* B3370 800D7FC0 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* B3374 800D7FC4 001AD402 */  srl        $k0, $k0, 16
    /* B3378 800D7FC8 037AD824 */  and        $k1, $k1, $k0
    /* B337C 800D7FCC 001BD840 */  sll        $k1, $k1, 1
    /* B3380 800D7FD0 3C1A800F */  lui        $k0, %hi(__osRcpImTable) /* handwritten instruction */
    /* B3384 800D7FD4 275A11A0 */  addiu      $k0, $k0, %lo(__osRcpImTable) /* handwritten instruction */
    /* B3388 800D7FD8 037AD821 */  addu       $k1, $k1, $k0
    /* B338C 800D7FDC 977B0000 */  lhu        $k1, 0x0($k1) /* handwritten instruction */
    /* B3390 800D7FE0 3C1AA430 */  lui        $k0, %hi(MI_INTR_MASK_REG) /* handwritten instruction */
    /* B3394 800D7FE4 275A000C */  addiu      $k0, $k0, %lo(MI_INTR_MASK_REG) /* handwritten instruction */
    /* B3398 800D7FE8 AF5B0000 */  sw         $k1, 0x0($k0) /* handwritten instruction */
    /* B339C 800D7FEC 00000000 */  nop
    /* B33A0 800D7FF0 00000000 */  nop
    /* B33A4 800D7FF4 00000000 */  nop
    /* B33A8 800D7FF8 00000000 */  nop
    /* B33AC 800D7FFC 42000018 */  eret /* handwritten instruction */

glabel __osCleanupThread
    /* B33B0 800D8000 0C037030 */  jal        osDestroyThread
    /* B33B4 800D8004 00002025 */   or        $a0, $zero, $zero
    /* B33B8 800D8008 00000000 */  nop
    /* B33BC 800D800C 00000000 */  nop
