.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel osGetCount
    /* B2AA0 800D76F0 40024800 */  mfc0       $v0, $9 /* handwritten instruction */
    /* B2AA4 800D76F4 03E00008 */  jr         $ra
    /* B2AA8 800D76F8 00000000 */   nop
    /* B2AAC 800D76FC 00000000 */  nop
