.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel __osDisableInt
    /* B25B0 800D7200 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* B25B4 800D7204 2401FFFE */  addiu      $at, $zero, -0x2
    /* B25B8 800D7208 01014824 */  and        $t1, $t0, $at
    /* B25BC 800D720C 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
    /* B25C0 800D7210 31020001 */  andi       $v0, $t0, 0x1
    /* B25C4 800D7214 00000000 */  nop
    /* B25C8 800D7218 03E00008 */  jr         $ra
    /* B25CC 800D721C 00000000 */   nop

/* Handwritten function */
glabel __osRestoreInt
    /* B25D0 800D7220 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* B25D4 800D7224 01044025 */  or         $t0, $t0, $a0
    /* B25D8 800D7228 40886000 */  mtc0       $t0, $12 /* handwritten instruction */
    /* B25DC 800D722C 00000000 */  nop
    /* B25E0 800D7230 00000000 */  nop
    /* B25E4 800D7234 03E00008 */  jr         $ra
    /* B25E8 800D7238 00000000 */   nop
    /* B25EC 800D723C 00000000 */  nop
