.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel osInvalICache
    /* B38F0 800D8540 18A00011 */  blez       $a1, .L800D8588
    /* B38F4 800D8544 00000000 */   nop
    /* B38F8 800D8548 240B4000 */  addiu      $t3, $zero, 0x4000
    /* B38FC 800D854C 00AB082B */  sltu       $at, $a1, $t3
    /* B3900 800D8550 1020000F */  beqz       $at, .L800D8590
    /* B3904 800D8554 00000000 */   nop
    /* B3908 800D8558 00804025 */  or         $t0, $a0, $zero
    /* B390C 800D855C 00854821 */  addu       $t1, $a0, $a1
    /* B3910 800D8560 0109082B */  sltu       $at, $t0, $t1
    /* B3914 800D8564 10200008 */  beqz       $at, .L800D8588
    /* B3918 800D8568 00000000 */   nop
    /* B391C 800D856C 310A001F */  andi       $t2, $t0, 0x1F
    /* B3920 800D8570 2529FFE0 */  addiu      $t1, $t1, -0x20
    /* B3924 800D8574 010A4023 */  subu       $t0, $t0, $t2
  .L800D8578:
    /* B3928 800D8578 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
    /* B392C 800D857C 0109082B */  sltu       $at, $t0, $t1
    /* B3930 800D8580 1420FFFD */  bnez       $at, .L800D8578
    /* B3934 800D8584 25080020 */   addiu     $t0, $t0, 0x20
  .L800D8588:
    /* B3938 800D8588 03E00008 */  jr         $ra
    /* B393C 800D858C 00000000 */   nop
  .L800D8590:
    /* B3940 800D8590 3C088000 */  lui        $t0, 0x8000
    /* B3944 800D8594 010B4821 */  addu       $t1, $t0, $t3
    /* B3948 800D8598 2529FFE0 */  addiu      $t1, $t1, -0x20
  .L800D859C:
    /* B394C 800D859C BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
    /* B3950 800D85A0 0109082B */  sltu       $at, $t0, $t1
    /* B3954 800D85A4 1420FFFD */  bnez       $at, .L800D859C
    /* B3958 800D85A8 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
    /* B395C 800D85AC 03E00008 */  jr         $ra
    /* B3960 800D85B0 00000000 */   nop
    /* B3964 800D85B4 00000000 */  nop
    /* B3968 800D85B8 00000000 */  nop
    /* B396C 800D85BC 00000000 */  nop
