.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel osInvalDCache
    /* AE190 800D2DE0 18A0001F */  blez       $a1, .L800D2E60
    /* AE194 800D2DE4 00000000 */   nop
    /* AE198 800D2DE8 240B2000 */  addiu      $t3, $zero, 0x2000
    /* AE19C 800D2DEC 00AB082B */  sltu       $at, $a1, $t3
    /* AE1A0 800D2DF0 1020001D */  beqz       $at, .L800D2E68
    /* AE1A4 800D2DF4 00000000 */   nop
    /* AE1A8 800D2DF8 00804025 */  or         $t0, $a0, $zero
    /* AE1AC 800D2DFC 00854821 */  addu       $t1, $a0, $a1
    /* AE1B0 800D2E00 0109082B */  sltu       $at, $t0, $t1
    /* AE1B4 800D2E04 10200016 */  beqz       $at, .L800D2E60
    /* AE1B8 800D2E08 00000000 */   nop
    /* AE1BC 800D2E0C 310A000F */  andi       $t2, $t0, 0xF
    /* AE1C0 800D2E10 11400007 */  beqz       $t2, .L800D2E30
    /* AE1C4 800D2E14 2529FFF0 */   addiu     $t1, $t1, -0x10
    /* AE1C8 800D2E18 010A4023 */  subu       $t0, $t0, $t2
    /* AE1CC 800D2E1C BD150000 */  cache      0x15, 0x0($t0) /* handwritten instruction */
    /* AE1D0 800D2E20 0109082B */  sltu       $at, $t0, $t1
    /* AE1D4 800D2E24 1020000E */  beqz       $at, .L800D2E60
    /* AE1D8 800D2E28 00000000 */   nop
    /* AE1DC 800D2E2C 25080010 */  addiu      $t0, $t0, 0x10
  .L800D2E30:
    /* AE1E0 800D2E30 312A000F */  andi       $t2, $t1, 0xF
    /* AE1E4 800D2E34 11400006 */  beqz       $t2, .L800D2E50
    /* AE1E8 800D2E38 00000000 */   nop
    /* AE1EC 800D2E3C 012A4823 */  subu       $t1, $t1, $t2
    /* AE1F0 800D2E40 BD350010 */  cache      0x15, 0x10($t1) /* handwritten instruction */
    /* AE1F4 800D2E44 0128082B */  sltu       $at, $t1, $t0
    /* AE1F8 800D2E48 14200005 */  bnez       $at, .L800D2E60
    /* AE1FC 800D2E4C 00000000 */   nop
  .L800D2E50:
    /* AE200 800D2E50 BD110000 */  cache      0x11, 0x0($t0) /* handwritten instruction */
    /* AE204 800D2E54 0109082B */  sltu       $at, $t0, $t1
    /* AE208 800D2E58 1420FFFD */  bnez       $at, .L800D2E50
    /* AE20C 800D2E5C 25080010 */   addiu     $t0, $t0, 0x10
  .L800D2E60:
    /* AE210 800D2E60 03E00008 */  jr         $ra
    /* AE214 800D2E64 00000000 */   nop
  .L800D2E68:
    /* AE218 800D2E68 3C088000 */  lui        $t0, 0x8000
    /* AE21C 800D2E6C 010B4821 */  addu       $t1, $t0, $t3
    /* AE220 800D2E70 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L800D2E74:
    /* AE224 800D2E74 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* AE228 800D2E78 0109082B */  sltu       $at, $t0, $t1
    /* AE22C 800D2E7C 1420FFFD */  bnez       $at, .L800D2E74
    /* AE230 800D2E80 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* AE234 800D2E84 03E00008 */  jr         $ra
    /* AE238 800D2E88 00000000 */   nop
    /* AE23C 800D2E8C 00000000 */  nop
