.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel osMapTLBRdb
    /* B3970 800D85C0 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* B3974 800D85C4 2409001F */  addiu      $t1, $zero, 0x1F
    /* B3978 800D85C8 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* B397C 800D85CC 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
    /* B3980 800D85D0 240A0017 */  addiu      $t2, $zero, 0x17
    /* B3984 800D85D4 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
    /* B3988 800D85D8 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* B398C 800D85DC 3C098000 */  lui        $t1, (0x80000000 >> 16)
    /* B3990 800D85E0 00095982 */  srl        $t3, $t1, 6
    /* B3994 800D85E4 016A5825 */  or         $t3, $t3, $t2
    /* B3998 800D85E8 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
    /* B399C 800D85EC 24090001 */  addiu      $t1, $zero, 0x1
    /* B39A0 800D85F0 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
    /* B39A4 800D85F4 00000000 */  nop
    /* B39A8 800D85F8 42000002 */  tlbwi /* handwritten instruction */
    /* B39AC 800D85FC 00000000 */  nop
    /* B39B0 800D8600 00000000 */  nop
    /* B39B4 800D8604 00000000 */  nop
    /* B39B8 800D8608 00000000 */  nop
    /* B39BC 800D860C 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* B39C0 800D8610 03E00008 */  jr         $ra
    /* B39C4 800D8614 00000000 */   nop
    /* B39C8 800D8618 00000000 */  nop
    /* B39CC 800D861C 00000000 */  nop
