.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel __osProbeTLB
    /* B2090 800D6CE0 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* B2094 800D6CE4 310900FF */  andi       $t1, $t0, 0xFF
    /* B2098 800D6CE8 2401E000 */  addiu      $at, $zero, -0x2000
    /* B209C 800D6CEC 00815024 */  and        $t2, $a0, $at
    /* B20A0 800D6CF0 012A4825 */  or         $t1, $t1, $t2
    /* B20A4 800D6CF4 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* B20A8 800D6CF8 00000000 */  nop
    /* B20AC 800D6CFC 00000000 */  nop
    /* B20B0 800D6D00 00000000 */  nop
    /* B20B4 800D6D04 42000008 */  tlbp /* handwritten instruction */
    /* B20B8 800D6D08 00000000 */  nop
    /* B20BC 800D6D0C 00000000 */  nop
    /* B20C0 800D6D10 400B0000 */  mfc0       $t3, $0 /* handwritten instruction */
    /* B20C4 800D6D14 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* B20C8 800D6D18 01615824 */  and        $t3, $t3, $at
    /* B20CC 800D6D1C 1560001A */  bnez       $t3, .L800D6D88
    /* B20D0 800D6D20 00000000 */   nop
    /* B20D4 800D6D24 42000001 */  tlbr /* handwritten instruction */
    /* B20D8 800D6D28 00000000 */  nop
    /* B20DC 800D6D2C 00000000 */  nop
    /* B20E0 800D6D30 00000000 */  nop
    /* B20E4 800D6D34 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
    /* B20E8 800D6D38 216B2000 */  addi       $t3, $t3, 0x2000 /* handwritten instruction */
    /* B20EC 800D6D3C 000B5842 */  srl        $t3, $t3, 1
    /* B20F0 800D6D40 01646024 */  and        $t4, $t3, $a0
    /* B20F4 800D6D44 15800004 */  bnez       $t4, .L800D6D58
    /* B20F8 800D6D48 216BFFFF */   addi      $t3, $t3, -0x1 /* handwritten instruction */
    /* B20FC 800D6D4C 40021000 */  mfc0       $v0, $2 /* handwritten instruction */
    /* B2100 800D6D50 10000002 */  b          .L800D6D5C
    /* B2104 800D6D54 00000000 */   nop
  .L800D6D58:
    /* B2108 800D6D58 40021800 */  mfc0       $v0, $3 /* handwritten instruction */
  .L800D6D5C:
    /* B210C 800D6D5C 304D0002 */  andi       $t5, $v0, 0x2
    /* B2110 800D6D60 11A00009 */  beqz       $t5, .L800D6D88
    /* B2114 800D6D64 00000000 */   nop
    /* B2118 800D6D68 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
    /* B211C 800D6D6C 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
    /* B2120 800D6D70 00411024 */  and        $v0, $v0, $at
    /* B2124 800D6D74 00021180 */  sll        $v0, $v0, 6
    /* B2128 800D6D78 008B6824 */  and        $t5, $a0, $t3
    /* B212C 800D6D7C 004D1020 */  add        $v0, $v0, $t5 /* handwritten instruction */
    /* B2130 800D6D80 10000002 */  b          .L800D6D8C
    /* B2134 800D6D84 00000000 */   nop
  .L800D6D88:
    /* B2138 800D6D88 2402FFFF */  addiu      $v0, $zero, -0x1
  .L800D6D8C:
    /* B213C 800D6D8C 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* B2140 800D6D90 03E00008 */  jr         $ra
    /* B2144 800D6D94 00000000 */   nop
    /* B2148 800D6D98 00000000 */  nop
    /* B214C 800D6D9C 00000000 */  nop
