.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel __osSetCompare
    /* B6BE0 800DB830 40845800 */  mtc0       $a0, $11 /* handwritten instruction */
    /* B6BE4 800DB834 03E00008 */  jr         $ra
    /* B6BE8 800DB838 00000000 */   nop
    /* B6BEC 800DB83C 00000000 */  nop
