.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

glabel __osSetFpcCsr
    /* B3840 800D8490 4442F800 */  cfc1       $v0, $31
    /* B3844 800D8494 44C4F800 */  ctc1       $a0, $31
    /* B3848 800D8498 03E00008 */  jr         $ra
    /* B384C 800D849C 00000000 */   nop
