.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel osSetIntMask
    /* AC8A0 800D14F0 400C6000 */  mfc0       $t4, $12 /* handwritten instruction */
    /* AC8A4 800D14F4 3182FF01 */  andi       $v0, $t4, 0xFF01
    /* AC8A8 800D14F8 3C08800F */  lui        $t0, %hi(__OSGlobalIntMask)
    /* AC8AC 800D14FC 2508A300 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* AC8B0 800D1500 8D0B0000 */  lw         $t3, 0x0($t0)
    /* AC8B4 800D1504 2401FFFF */  addiu      $at, $zero, -0x1
    /* AC8B8 800D1508 01614026 */  xor        $t0, $t3, $at
    /* AC8BC 800D150C 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* AC8C0 800D1510 00481025 */  or         $v0, $v0, $t0
    /* AC8C4 800D1514 3C0AA430 */  lui        $t2, %hi(MI_INTR_MASK_REG)
    /* AC8C8 800D1518 8D4A000C */  lw         $t2, %lo(MI_INTR_MASK_REG)($t2)
    /* AC8CC 800D151C 11400005 */  beqz       $t2, .L800D1534
    /* AC8D0 800D1520 000B4C02 */   srl       $t1, $t3, 16
    /* AC8D4 800D1524 2401FFFF */  addiu      $at, $zero, -0x1
    /* AC8D8 800D1528 01214826 */  xor        $t1, $t1, $at
    /* AC8DC 800D152C 3129003F */  andi       $t1, $t1, 0x3F
    /* AC8E0 800D1530 01495025 */  or         $t2, $t2, $t1
  .L800D1534:
    /* AC8E4 800D1534 000A5400 */  sll        $t2, $t2, 16
    /* AC8E8 800D1538 004A1025 */  or         $v0, $v0, $t2
    /* AC8EC 800D153C 3C01003F */  lui        $at, (0x3F0000 >> 16)
    /* AC8F0 800D1540 00814024 */  and        $t0, $a0, $at
    /* AC8F4 800D1544 010B4024 */  and        $t0, $t0, $t3
    /* AC8F8 800D1548 000843C2 */  srl        $t0, $t0, 15
    /* AC8FC 800D154C 3C0A800F */  lui        $t2, %hi(__osRcpImTable)
    /* AC900 800D1550 01485021 */  addu       $t2, $t2, $t0
    /* AC904 800D1554 954A11A0 */  lhu        $t2, %lo(__osRcpImTable)($t2)
    /* AC908 800D1558 3C01A430 */  lui        $at, %hi(MI_INTR_MASK_REG)
    /* AC90C 800D155C AC2A000C */  sw         $t2, %lo(MI_INTR_MASK_REG)($at)
    /* AC910 800D1560 3088FF01 */  andi       $t0, $a0, 0xFF01
    /* AC914 800D1564 3169FF00 */  andi       $t1, $t3, 0xFF00
    /* AC918 800D1568 01094024 */  and        $t0, $t0, $t1
    /* AC91C 800D156C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* AC920 800D1570 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* AC924 800D1574 01816024 */  and        $t4, $t4, $at
    /* AC928 800D1578 01886025 */  or         $t4, $t4, $t0
    /* AC92C 800D157C 408C6000 */  mtc0       $t4, $12 /* handwritten instruction */
    /* AC930 800D1580 00000000 */  nop
    /* AC934 800D1584 00000000 */  nop
    /* AC938 800D1588 03E00008 */  jr         $ra
    /* AC93C 800D158C 00000000 */   nop
