.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel __osSetSR
    /* B3820 800D8470 40846000 */  mtc0       $a0, $12 /* handwritten instruction */
    /* B3824 800D8474 00000000 */  nop
    /* B3828 800D8478 03E00008 */  jr         $ra
    /* B382C 800D847C 00000000 */   nop

/* Handwritten function */
glabel __osGetSR
    /* B3830 800D8480 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
    /* B3834 800D8484 03E00008 */  jr         $ra
    /* B3838 800D8488 00000000 */   nop
    /* B383C 800D848C 00000000 */  nop
