.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel osWritebackDCacheAll
    /* ACD20 800D1970 3C088000 */  lui        $t0, 0x8000
    /* ACD24 800D1974 240A2000 */  addiu      $t2, $zero, 0x2000
    /* ACD28 800D1978 010A4821 */  addu       $t1, $t0, $t2
    /* ACD2C 800D197C 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L800D1980:
    /* ACD30 800D1980 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* ACD34 800D1984 0109082B */  sltu       $at, $t0, $t1
    /* ACD38 800D1988 1420FFFD */  bnez       $at, .L800D1980
    /* ACD3C 800D198C 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* ACD40 800D1990 03E00008 */  jr         $ra
    /* ACD44 800D1994 00000000 */   nop
    /* ACD48 800D1998 00000000 */  nop
    /* ACD4C 800D199C 00000000 */  nop
