.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
glabel osWritebackDCache
    /* B1110 800D5D60 18A00011 */  blez       $a1, .L800D5DA8
    /* B1114 800D5D64 00000000 */   nop
    /* B1118 800D5D68 240B2000 */  addiu      $t3, $zero, 0x2000
    /* B111C 800D5D6C 00AB082B */  sltu       $at, $a1, $t3
    /* B1120 800D5D70 1020000F */  beqz       $at, .L800D5DB0
    /* B1124 800D5D74 00000000 */   nop
    /* B1128 800D5D78 00804025 */  or         $t0, $a0, $zero
    /* B112C 800D5D7C 00854821 */  addu       $t1, $a0, $a1
    /* B1130 800D5D80 0109082B */  sltu       $at, $t0, $t1
    /* B1134 800D5D84 10200008 */  beqz       $at, .L800D5DA8
    /* B1138 800D5D88 00000000 */   nop
    /* B113C 800D5D8C 310A000F */  andi       $t2, $t0, 0xF
    /* B1140 800D5D90 2529FFF0 */  addiu      $t1, $t1, -0x10
    /* B1144 800D5D94 010A4023 */  subu       $t0, $t0, $t2
  .L800D5D98:
    /* B1148 800D5D98 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
    /* B114C 800D5D9C 0109082B */  sltu       $at, $t0, $t1
    /* B1150 800D5DA0 1420FFFD */  bnez       $at, .L800D5D98
    /* B1154 800D5DA4 25080010 */   addiu     $t0, $t0, 0x10
  .L800D5DA8:
    /* B1158 800D5DA8 03E00008 */  jr         $ra
    /* B115C 800D5DAC 00000000 */   nop
  .L800D5DB0:
    /* B1160 800D5DB0 3C088000 */  lui        $t0, 0x8000
    /* B1164 800D5DB4 010B4821 */  addu       $t1, $t0, $t3
    /* B1168 800D5DB8 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L800D5DBC:
    /* B116C 800D5DBC BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* B1170 800D5DC0 0109082B */  sltu       $at, $t0, $t1
    /* B1174 800D5DC4 1420FFFD */  bnez       $at, .L800D5DBC
    /* B1178 800D5DC8 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* B117C 800D5DCC 03E00008 */  jr         $ra
    /* B1180 800D5DD0 00000000 */   nop
    /* B1184 800D5DD4 00000000 */  nop
    /* B1188 800D5DD8 00000000 */  nop
    /* B118C 800D5DDC 00000000 */  nop
