.section .late_rodata
dlabel jtbl_800F1094
    /* CC444 800F1094 800ACCF4 */ .word .L800ACCF4
    /* CC448 800F1098 800ACD00 */ .word .L800ACD00
    /* CC44C 800F109C 800ACD0C */ .word .L800ACD0C
    /* CC450 800F10A0 800ACD2C */ .word .L800ACD2C
    /* CC454 800F10A4 800ACCEC */ .word .L800ACCEC
    /* CC458 800F10A8 800ACD4C */ .word .L800ACD4C
    /* CC45C 800F10AC 800ACD54 */ .word .L800ACD54

.align 3
dlabel D_800F10B0
    /* CC460 800F10B0 40DDF88000000000 */ .double 30690

.align 3
dlabel D_800F10B8
    /* CC468 800F10B8 40DE1F4000000000 */ .double 30845

dlabel D_800F10C0
    /* CC470 800F10C0 44BB8000 */ .float 1500


.section .text
/* Generated by spimdisasm 1.42.2 */

glabel func_800ACB94
    /* 87F44 800ACB94 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 87F48 800ACB98 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 87F4C 800ACB9C AFA40038 */  sw         $a0, 0x38($sp)
    /* 87F50 800ACBA0 AFA5003C */  sw         $a1, 0x3C($sp)
    /* 87F54 800ACBA4 A7A00036 */  sh         $zero, 0x36($sp)
    /* 87F58 800ACBA8 84C224A6 */  lh         $v0, 0x24A6($a2)
    /* 87F5C 800ACBAC 00C03825 */  or         $a3, $a2, $zero
    /* 87F60 800ACBB0 10400002 */  beqz       $v0, .L800ACBBC
    /* 87F64 800ACBB4 244E0001 */   addiu     $t6, $v0, 0x1
    /* 87F68 800ACBB8 A4CE24A6 */  sh         $t6, 0x24A6($a2)
  .L800ACBBC:
    /* 87F6C 800ACBBC 94EF23D2 */  lhu        $t7, 0x23D2($a3)
    /* 87F70 800ACBC0 97B8003A */  lhu        $t8, 0x3A($sp)
    /* 87F74 800ACBC4 11E00006 */  beqz       $t7, .L800ACBE0
    /* 87F78 800ACBC8 97B9003A */   lhu       $t9, 0x3A($sp)
    /* 87F7C 800ACBCC 13000004 */  beqz       $t8, .L800ACBE0
    /* 87F80 800ACBD0 97B9003A */   lhu       $t9, 0x3A($sp)
    /* 87F84 800ACBD4 10000006 */  b          .L800ACBF0
    /* 87F88 800ACBD8 A7A0003A */   sh        $zero, 0x3A($sp)
    /* 87F8C 800ACBDC 97B9003A */  lhu        $t9, 0x3A($sp)
  .L800ACBE0:
    /* 87F90 800ACBE0 00000000 */  nop
    /* 87F94 800ACBE4 17200002 */  bnez       $t9, .L800ACBF0
    /* 87F98 800ACBE8 00000000 */   nop
    /* 87F9C 800ACBEC A4E023D2 */  sh         $zero, 0x23D2($a3)
  .L800ACBF0:
    /* 87FA0 800ACBF0 90EB1680 */  lbu        $t3, 0x1680($a3)
    /* 87FA4 800ACBF4 00000000 */  nop
    /* 87FA8 800ACBF8 1560000B */  bnez       $t3, .L800ACC28
    /* 87FAC 800ACBFC 00000000 */   nop
    /* 87FB0 800ACC00 84EC23AE */  lh         $t4, 0x23AE($a3)
    /* 87FB4 800ACC04 97AD003A */  lhu        $t5, 0x3A($sp)
    /* 87FB8 800ACC08 11800002 */  beqz       $t4, .L800ACC14
    /* 87FBC 800ACC0C 31AE5FFF */   andi      $t6, $t5, 0x5FFF
    /* 87FC0 800ACC10 A7AE003A */  sh         $t6, 0x3A($sp)
  .L800ACC14:
    /* 87FC4 800ACC14 84EF23B0 */  lh         $t7, 0x23B0($a3)
    /* 87FC8 800ACC18 97B8003A */  lhu        $t8, 0x3A($sp)
    /* 87FCC 800ACC1C 11E00002 */  beqz       $t7, .L800ACC28
    /* 87FD0 800ACC20 3319BFFF */   andi      $t9, $t8, 0xBFFF
    /* 87FD4 800ACC24 A7B9003A */  sh         $t9, 0x3A($sp)
  .L800ACC28:
    /* 87FD8 800ACC28 84EB23BC */  lh         $t3, 0x23BC($a3)
    /* 87FDC 800ACC2C 97AC003A */  lhu        $t4, 0x3A($sp)
    /* 87FE0 800ACC30 116000C4 */  beqz       $t3, .L800ACF44
    /* 87FE4 800ACC34 00000000 */   nop
    /* 87FE8 800ACC38 A7AC0028 */  sh         $t4, 0x28($sp)
    /* 87FEC 800ACC3C A7A0003A */  sh         $zero, 0x3A($sp)
    /* 87FF0 800ACC40 84ED23C4 */  lh         $t5, 0x23C4($a3)
    /* 87FF4 800ACC44 00000000 */  nop
    /* 87FF8 800ACC48 1DA00013 */  bgtz       $t5, .L800ACC98
    /* 87FFC 800ACC4C 00000000 */   nop
    /* 88000 800ACC50 84E223BE */  lh         $v0, 0x23BE($a3)
    /* 88004 800ACC54 8CE323C8 */  lw         $v1, 0x23C8($a3)
    /* 88008 800ACC58 00027040 */  sll        $t6, $v0, 1
    /* 8800C 800ACC5C 006E7821 */  addu       $t7, $v1, $t6
    /* 88010 800ACC60 95F80000 */  lhu        $t8, 0x0($t7)
    /* 88014 800ACC64 24590001 */  addiu      $t9, $v0, 0x1
    /* 88018 800ACC68 A4F923BE */  sh         $t9, 0x23BE($a3)
    /* 8801C 800ACC6C 84E223BE */  lh         $v0, 0x23BE($a3)
    /* 88020 800ACC70 A4F823C4 */  sh         $t8, 0x23C4($a3)
    /* 88024 800ACC74 00025840 */  sll        $t3, $v0, 1
    /* 88028 800ACC78 006B6021 */  addu       $t4, $v1, $t3
    /* 8802C 800ACC7C 958D0000 */  lhu        $t5, 0x0($t4)
    /* 88030 800ACC80 244E0001 */  addiu      $t6, $v0, 0x1
    /* 88034 800ACC84 A7AD003A */  sh         $t5, 0x3A($sp)
    /* 88038 800ACC88 A4EE23BE */  sh         $t6, 0x23BE($a3)
    /* 8803C 800ACC8C 97AF003A */  lhu        $t7, 0x3A($sp)
    /* 88040 800ACC90 10000004 */  b          .L800ACCA4
    /* 88044 800ACC94 A4EF23C2 */   sh        $t7, 0x23C2($a3)
  .L800ACC98:
    /* 88048 800ACC98 94F823C2 */  lhu        $t8, 0x23C2($a3)
    /* 8804C 800ACC9C 00000000 */  nop
    /* 88050 800ACCA0 A7B8003A */  sh         $t8, 0x3A($sp)
  .L800ACCA4:
    /* 88054 800ACCA4 97B9003A */  lhu        $t9, 0x3A($sp)
    /* 88058 800ACCA8 94EA23C0 */  lhu        $t2, 0x23C0($a3)
    /* 8805C 800ACCAC A4F923C0 */  sh         $t9, 0x23C0($a3)
    /* 88060 800ACCB0 97A8003A */  lhu        $t0, 0x3A($sp)
    /* 88064 800ACCB4 24010F00 */  addiu      $at, $zero, 0xF00
    /* 88068 800ACCB8 1501002F */  bne        $t0, $at, .L800ACD78
    /* 8806C 800ACCBC 24010C00 */   addiu     $at, $zero, 0xC00
    /* 88070 800ACCC0 94EB23C4 */  lhu        $t3, 0x23C4($a3)
    /* 88074 800ACCC4 00000000 */  nop
    /* 88078 800ACCC8 2D610007 */  sltiu      $at, $t3, 0x7
    /* 8807C 800ACCCC 10200023 */  beqz       $at, .L800ACD5C
    /* 88080 800ACCD0 000B5880 */   sll       $t3, $t3, 2
    /* 88084 800ACCD4 3C01800F */  lui        $at, %hi(jtbl_800F1094)
    /* 88088 800ACCD8 002B0821 */  addu       $at, $at, $t3
    /* 8808C 800ACCDC 8C2B1094 */  lw         $t3, %lo(jtbl_800F1094)($at)
    /* 88090 800ACCE0 00000000 */  nop
    /* 88094 800ACCE4 01600008 */  jr         $t3
    /* 88098 800ACCE8 00000000 */   nop
  .L800ACCEC:
    /* 8809C 800ACCEC 1000001B */  b          .L800ACD5C
    /* 880A0 800ACCF0 ACE0240C */   sw        $zero, 0x240C($a3)
  .L800ACCF4:
    /* 880A4 800ACCF4 240C04B0 */  addiu      $t4, $zero, 0x4B0
    /* 880A8 800ACCF8 10000018 */  b          .L800ACD5C
    /* 880AC 800ACCFC ACEC240C */   sw        $t4, 0x240C($a3)
  .L800ACD00:
    /* 880B0 800ACD00 240D1068 */  addiu      $t5, $zero, 0x1068
    /* 880B4 800ACD04 10000015 */  b          .L800ACD5C
    /* 880B8 800ACD08 ACED240C */   sw        $t5, 0x240C($a3)
  .L800ACD0C:
    /* 880BC 800ACD0C 00E02025 */  or         $a0, $a3, $zero
    /* 880C0 800ACD10 0C02B726 */  jal        func_800ADC98
    /* 880C4 800ACD14 AFA70040 */   sw        $a3, 0x40($sp)
    /* 880C8 800ACD18 8FA70040 */  lw         $a3, 0x40($sp)
    /* 880CC 800ACD1C 24090001 */  addiu      $t1, $zero, 0x1
    /* 880D0 800ACD20 A4E924BA */  sh         $t1, 0x24BA($a3)
    /* 880D4 800ACD24 1000000D */  b          .L800ACD5C
    /* 880D8 800ACD28 A4E93234 */   sh        $t1, 0x3234($a3)
  .L800ACD2C:
    /* 880DC 800ACD2C 00E02025 */  or         $a0, $a3, $zero
    /* 880E0 800ACD30 0C02B73C */  jal        func_800ADCF0
    /* 880E4 800ACD34 AFA70040 */   sw        $a3, 0x40($sp)
    /* 880E8 800ACD38 8FA70040 */  lw         $a3, 0x40($sp)
    /* 880EC 800ACD3C 00000000 */  nop
    /* 880F0 800ACD40 A4E024BA */  sh         $zero, 0x24BA($a3)
    /* 880F4 800ACD44 10000005 */  b          .L800ACD5C
    /* 880F8 800ACD48 A4E03234 */   sh        $zero, 0x3234($a3)
  .L800ACD4C:
    /* 880FC 800ACD4C 10000003 */  b          .L800ACD5C
    /* 88100 800ACD50 A4E03234 */   sh        $zero, 0x3234($a3)
  .L800ACD54:
    /* 88104 800ACD54 24090001 */  addiu      $t1, $zero, 0x1
    /* 88108 800ACD58 A4E93234 */  sh         $t1, 0x3234($a3)
  .L800ACD5C:
    /* 8810C 800ACD5C A4E023C4 */  sh         $zero, 0x23C4($a3)
    /* 88110 800ACD60 A7A0003A */  sh         $zero, 0x3A($sp)
    /* 88114 800ACD64 00005025 */  or         $t2, $zero, $zero
    /* 88118 800ACD68 A4E023C2 */  sh         $zero, 0x23C2($a3)
    /* 8811C 800ACD6C A4E023C0 */  sh         $zero, 0x23C0($a3)
    /* 88120 800ACD70 00004025 */  or         $t0, $zero, $zero
    /* 88124 800ACD74 24010C00 */  addiu      $at, $zero, 0xC00
  .L800ACD78:
    /* 88128 800ACD78 1501000D */  bne        $t0, $at, .L800ACDB0
    /* 8812C 800ACD7C 24090001 */   addiu     $t1, $zero, 0x1
    /* 88130 800ACD80 00E02025 */  or         $a0, $a3, $zero
    /* 88134 800ACD84 A7A0003A */  sh         $zero, 0x3A($sp)
    /* 88138 800ACD88 00005025 */  or         $t2, $zero, $zero
    /* 8813C 800ACD8C AFA70040 */  sw         $a3, 0x40($sp)
    /* 88140 800ACD90 0C02B71C */  jal        func_800ADC70
    /* 88144 800ACD94 A7A0003E */   sh        $zero, 0x3E($sp)
    /* 88148 800ACD98 8FA70040 */  lw         $a3, 0x40($sp)
    /* 8814C 800ACD9C 97AA003E */  lhu        $t2, 0x3E($sp)
    /* 88150 800ACDA0 24090001 */  addiu      $t1, $zero, 0x1
    /* 88154 800ACDA4 00004025 */  or         $t0, $zero, $zero
    /* 88158 800ACDA8 A4E023C2 */  sh         $zero, 0x23C2($a3)
    /* 8815C 800ACDAC A4E023C0 */  sh         $zero, 0x23C0($a3)
  .L800ACDB0:
    /* 88160 800ACDB0 24010300 */  addiu      $at, $zero, 0x300
    /* 88164 800ACDB4 1501000D */  bne        $t0, $at, .L800ACDEC
    /* 88168 800ACDB8 00E02025 */   or        $a0, $a3, $zero
    /* 8816C 800ACDBC A4E023BC */  sh         $zero, 0x23BC($a3)
    /* 88170 800ACDC0 A7A0003A */  sh         $zero, 0x3A($sp)
    /* 88174 800ACDC4 A4E023C2 */  sh         $zero, 0x23C2($a3)
    /* 88178 800ACDC8 A4E023C0 */  sh         $zero, 0x23C0($a3)
    /* 8817C 800ACDCC A4E923C4 */  sh         $t1, 0x23C4($a3)
    /* 88180 800ACDD0 A7A0003E */  sh         $zero, 0x3E($sp)
    /* 88184 800ACDD4 0C02B73C */  jal        func_800ADCF0
    /* 88188 800ACDD8 AFA70040 */   sw        $a3, 0x40($sp)
    /* 8818C 800ACDDC 8FA70040 */  lw         $a3, 0x40($sp)
    /* 88190 800ACDE0 97AA003E */  lhu        $t2, 0x3E($sp)
    /* 88194 800ACDE4 24090001 */  addiu      $t1, $zero, 0x1
    /* 88198 800ACDE8 00004025 */  or         $t0, $zero, $zero
  .L800ACDEC:
    /* 8819C 800ACDEC 24010700 */  addiu      $at, $zero, 0x700
    /* 881A0 800ACDF0 1501000B */  bne        $t0, $at, .L800ACE20
    /* 881A4 800ACDF4 240E0001 */   addiu     $t6, $zero, 0x1
    /* 881A8 800ACDF8 3C01800E */  lui        $at, %hi(D_800E23EC)
    /* 881AC 800ACDFC A7A0003A */  sh         $zero, 0x3A($sp)
    /* 881B0 800ACE00 A42E23EC */  sh         $t6, %lo(D_800E23EC)($at)
    /* 881B4 800ACE04 AFA70040 */  sw         $a3, 0x40($sp)
    /* 881B8 800ACE08 0C01D2C0 */  jal        func_80074B00
    /* 881BC 800ACE0C A7AA003E */   sh        $t2, 0x3E($sp)
    /* 881C0 800ACE10 8FA70040 */  lw         $a3, 0x40($sp)
    /* 881C4 800ACE14 97AA003E */  lhu        $t2, 0x3E($sp)
    /* 881C8 800ACE18 24090001 */  addiu      $t1, $zero, 0x1
    /* 881CC 800ACE1C 00004025 */  or         $t0, $zero, $zero
  .L800ACE20:
    /* 881D0 800ACE20 24010E00 */  addiu      $at, $zero, 0xE00
    /* 881D4 800ACE24 15010008 */  bne        $t0, $at, .L800ACE48
    /* 881D8 800ACE28 240F000F */   addiu     $t7, $zero, 0xF
    /* 881DC 800ACE2C A4E923B4 */  sh         $t1, 0x23B4($a3)
    /* 881E0 800ACE30 A4EF23B6 */  sh         $t7, 0x23B6($a3)
    /* 881E4 800ACE34 A7A0003A */  sh         $zero, 0x3A($sp)
    /* 881E8 800ACE38 00005025 */  or         $t2, $zero, $zero
    /* 881EC 800ACE3C A4E023C2 */  sh         $zero, 0x23C2($a3)
    /* 881F0 800ACE40 A4E023C0 */  sh         $zero, 0x23C0($a3)
    /* 881F4 800ACE44 00004025 */  or         $t0, $zero, $zero
  .L800ACE48:
    /* 881F8 800ACE48 24010B00 */  addiu      $at, $zero, 0xB00
    /* 881FC 800ACE4C 15010036 */  bne        $t0, $at, .L800ACF28
    /* 88200 800ACE50 00000000 */   nop
    /* 88204 800ACE54 84F823BE */  lh         $t8, 0x23BE($a3)
    /* 88208 800ACE58 3C0C8010 */  lui        $t4, %hi(D_80103960)
    /* 8820C 800ACE5C 2719FFFE */  addiu      $t9, $t8, -0x2
    /* 88210 800ACE60 A4F923BE */  sh         $t9, 0x23BE($a3)
    /* 88214 800ACE64 A7A0003A */  sh         $zero, 0x3A($sp)
    /* 88218 800ACE68 80EB3103 */  lb         $t3, 0x3103($a3)
    /* 8821C 800ACE6C 3C0D8010 */  lui        $t5, %hi(D_8010395C)
    /* 88220 800ACE70 11600016 */  beqz       $t3, .L800ACECC
    /* 88224 800ACE74 97AB0028 */   lhu       $t3, 0x28($sp)
    /* 88228 800ACE78 8D8C3960 */  lw         $t4, %lo(D_80103960)($t4)
    /* 8822C 800ACE7C 8DAD395C */  lw         $t5, %lo(D_8010395C)($t5)
    /* 88230 800ACE80 24190096 */  addiu      $t9, $zero, 0x96
    /* 88234 800ACE84 018D082B */  sltu       $at, $t4, $t5
    /* 88238 800ACE88 1420000D */  bnez       $at, .L800ACEC0
    /* 8823C 800ACE8C 00000000 */   nop
    /* 88240 800ACE90 84E23104 */  lh         $v0, 0x3104($a3)
    /* 88244 800ACE94 3C01800E */  lui        $at, %hi(D_800E23EC)
    /* 88248 800ACE98 10400003 */  beqz       $v0, .L800ACEA8
    /* 8824C 800ACE9C 244EFFFF */   addiu     $t6, $v0, -0x1
    /* 88250 800ACEA0 10000021 */  b          .L800ACF28
    /* 88254 800ACEA4 A4EE3104 */   sh        $t6, 0x3104($a3)
  .L800ACEA8:
    /* 88258 800ACEA8 A42023EC */  sh         $zero, %lo(D_800E23EC)($at)
    /* 8825C 800ACEAC 84EF23BE */  lh         $t7, 0x23BE($a3)
    /* 88260 800ACEB0 00000000 */  nop
    /* 88264 800ACEB4 25F80002 */  addiu      $t8, $t7, 0x2
    /* 88268 800ACEB8 1000001B */  b          .L800ACF28
    /* 8826C 800ACEBC A4F823BE */   sh        $t8, 0x23BE($a3)
  .L800ACEC0:
    /* 88270 800ACEC0 10000019 */  b          .L800ACF28
    /* 88274 800ACEC4 A4F93104 */   sh        $t9, 0x3104($a3)
    /* 88278 800ACEC8 97AB0028 */  lhu        $t3, 0x28($sp)
  .L800ACECC:
    /* 8827C 800ACECC 3C0D800E */  lui        $t5, %hi(D_800E6DD0)
    /* 88280 800ACED0 316C8400 */  andi       $t4, $t3, 0x8400
    /* 88284 800ACED4 11800014 */  beqz       $t4, .L800ACF28
    /* 88288 800ACED8 00000000 */   nop
    /* 8828C 800ACEDC 95AD6DD0 */  lhu        $t5, %lo(D_800E6DD0)($t5)
    /* 88290 800ACEE0 3C028010 */  lui        $v0, %hi(D_8010395C)
    /* 88294 800ACEE4 31AE8400 */  andi       $t6, $t5, 0x8400
    /* 88298 800ACEE8 15C0000F */  bnez       $t6, .L800ACF28
    /* 8829C 800ACEEC 3C0F8010 */   lui       $t7, %hi(D_80103960)
    /* 882A0 800ACEF0 8C42395C */  lw         $v0, %lo(D_8010395C)($v0)
    /* 882A4 800ACEF4 8DEF3960 */  lw         $t7, %lo(D_80103960)($t7)
    /* 882A8 800ACEF8 00000000 */  nop
    /* 882AC 800ACEFC 01E2082B */  sltu       $at, $t7, $v0
    /* 882B0 800ACF00 10200003 */  beqz       $at, .L800ACF10
    /* 882B4 800ACF04 3C018010 */   lui       $at, %hi(D_80103960)
    /* 882B8 800ACF08 10000007 */  b          .L800ACF28
    /* 882BC 800ACF0C AC223960 */   sw        $v0, %lo(D_80103960)($at)
  .L800ACF10:
    /* 882C0 800ACF10 3C01800E */  lui        $at, %hi(D_800E23EC)
    /* 882C4 800ACF14 A42023EC */  sh         $zero, %lo(D_800E23EC)($at)
    /* 882C8 800ACF18 84F823BE */  lh         $t8, 0x23BE($a3)
    /* 882CC 800ACF1C 00000000 */  nop
    /* 882D0 800ACF20 27190002 */  addiu      $t9, $t8, 0x2
    /* 882D4 800ACF24 A4F923BE */  sh         $t9, 0x23BE($a3)
  .L800ACF28:
    /* 882D8 800ACF28 84EB23C4 */  lh         $t3, 0x23C4($a3)
    /* 882DC 800ACF2C 3C01800E */  lui        $at, %hi(D_800E6DD0)
    /* 882E0 800ACF30 256CFFFF */  addiu      $t4, $t3, -0x1
    /* 882E4 800ACF34 A4EC23C4 */  sh         $t4, 0x23C4($a3)
    /* 882E8 800ACF38 97AD0028 */  lhu        $t5, 0x28($sp)
    /* 882EC 800ACF3C A7AA003E */  sh         $t2, 0x3E($sp)
    /* 882F0 800ACF40 A42D6DD0 */  sh         $t5, %lo(D_800E6DD0)($at)
  .L800ACF44:
    /* 882F4 800ACF44 3C02800E */  lui        $v0, %hi(D_800E44A8)
    /* 882F8 800ACF48 844244A8 */  lh         $v0, %lo(D_800E44A8)($v0)
    /* 882FC 800ACF4C 24010003 */  addiu      $at, $zero, 0x3
    /* 88300 800ACF50 14410008 */  bne        $v0, $at, .L800ACF74
    /* 88304 800ACF54 24090001 */   addiu     $t1, $zero, 0x1
    /* 88308 800ACF58 97A4003A */  lhu        $a0, 0x3A($sp)
    /* 8830C 800ACF5C 0C01D334 */  jal        func_80074CD0
    /* 88310 800ACF60 AFA70040 */   sw        $a3, 0x40($sp)
    /* 88314 800ACF64 3C02800E */  lui        $v0, %hi(D_800E44A8)
    /* 88318 800ACF68 844244A8 */  lh         $v0, %lo(D_800E44A8)($v0)
    /* 8831C 800ACF6C 8FA70040 */  lw         $a3, 0x40($sp)
    /* 88320 800ACF70 24090001 */  addiu      $t1, $zero, 0x1
  .L800ACF74:
    /* 88324 800ACF74 24010003 */  addiu      $at, $zero, 0x3
    /* 88328 800ACF78 1041000E */  beq        $v0, $at, .L800ACFB4
    /* 8832C 800ACF7C 00000000 */   nop
    /* 88330 800ACF80 80EE3103 */  lb         $t6, 0x3103($a3)
    /* 88334 800ACF84 00000000 */  nop
    /* 88338 800ACF88 11C0000A */  beqz       $t6, .L800ACFB4
    /* 8833C 800ACF8C 00000000 */   nop
    /* 88340 800ACF90 84EF23A2 */  lh         $t7, 0x23A2($a3)
    /* 88344 800ACF94 00E02025 */  or         $a0, $a3, $zero
    /* 88348 800ACF98 11E00006 */  beqz       $t7, .L800ACFB4
    /* 8834C 800ACF9C 00000000 */   nop
    /* 88350 800ACFA0 0C02CBA5 */  jal        func_800B2E94
    /* 88354 800ACFA4 AFA70040 */   sw        $a3, 0x40($sp)
    /* 88358 800ACFA8 8FA70040 */  lw         $a3, 0x40($sp)
    /* 8835C 800ACFAC 24090001 */  addiu      $t1, $zero, 0x1
    /* 88360 800ACFB0 A7A2003A */  sh         $v0, 0x3A($sp)
  .L800ACFB4:
    /* 88364 800ACFB4 84F823B2 */  lh         $t8, 0x23B2($a3)
    /* 88368 800ACFB8 3C02800E */  lui        $v0, %hi(D_800E4484)
    /* 8836C 800ACFBC 1538000A */  bne        $t1, $t8, .L800ACFE8
    /* 88370 800ACFC0 24040001 */   addiu     $a0, $zero, 0x1
    /* 88374 800ACFC4 3C03800E */  lui        $v1, %hi(D_800E4478)
    /* 88378 800ACFC8 24634478 */  addiu      $v1, $v1, %lo(D_800E4478)
    /* 8837C 800ACFCC 24424484 */  addiu      $v0, $v0, %lo(D_800E4484)
    /* 88380 800ACFD0 84590000 */  lh         $t9, 0x0($v0)
    /* 88384 800ACFD4 8C6C0000 */  lw         $t4, 0x0($v1)
    /* 88388 800ACFD8 272B0001 */  addiu      $t3, $t9, 0x1
    /* 8838C 800ACFDC 258D0001 */  addiu      $t5, $t4, 0x1
    /* 88390 800ACFE0 A44B0000 */  sh         $t3, 0x0($v0)
    /* 88394 800ACFE4 AC6D0000 */  sw         $t5, 0x0($v1)
  .L800ACFE8:
    /* 88398 800ACFE8 0C0207A4 */  jal        func_80081E90
    /* 8839C 800ACFEC AFA70040 */   sw        $a3, 0x40($sp)
    /* 883A0 800ACFF0 3C0E800E */  lui        $t6, %hi(D_800E44FC)
    /* 883A4 800ACFF4 91CE44FC */  lbu        $t6, %lo(D_800E44FC)($t6)
    /* 883A8 800ACFF8 8FA70040 */  lw         $a3, 0x40($sp)
    /* 883AC 800ACFFC 97AA003E */  lhu        $t2, 0x3E($sp)
    /* 883B0 800AD000 11C00042 */  beqz       $t6, .L800AD10C
    /* 883B4 800AD004 24090001 */   addiu     $t1, $zero, 0x1
    /* 883B8 800AD008 3C038010 */  lui        $v1, %hi(D_801033D0)
    /* 883BC 800AD00C 846333D0 */  lh         $v1, %lo(D_801033D0)($v1)
    /* 883C0 800AD010 97AF003A */  lhu        $t7, 0x3A($sp)
    /* 883C4 800AD014 0461002F */  bgez       $v1, .L800AD0D4
    /* 883C8 800AD018 31F8A400 */   andi      $t8, $t7, 0xA400
    /* 883CC 800AD01C 1300002D */  beqz       $t8, .L800AD0D4
    /* 883D0 800AD020 3159A400 */   andi      $t9, $t2, 0xA400
    /* 883D4 800AD024 1720002B */  bnez       $t9, .L800AD0D4
    /* 883D8 800AD028 3C028010 */   lui       $v0, %hi(D_8010395C)
    /* 883DC 800AD02C 3C0B8010 */  lui        $t3, %hi(D_80103960)
    /* 883E0 800AD030 8D6B3960 */  lw         $t3, %lo(D_80103960)($t3)
    /* 883E4 800AD034 8C42395C */  lw         $v0, %lo(D_8010395C)($v0)
    /* 883E8 800AD038 00000000 */  nop
    /* 883EC 800AD03C 0162082B */  sltu       $at, $t3, $v0
    /* 883F0 800AD040 10200003 */  beqz       $at, .L800AD050
    /* 883F4 800AD044 3C018010 */   lui       $at, %hi(D_80103960)
    /* 883F8 800AD048 10000022 */  b          .L800AD0D4
    /* 883FC 800AD04C AC223960 */   sw        $v0, %lo(D_80103960)($at)
  .L800AD050:
    /* 88400 800AD050 1040000F */  beqz       $v0, .L800AD090
    /* 88404 800AD054 00E02025 */   or        $a0, $a3, $zero
    /* 88408 800AD058 904C0000 */  lbu        $t4, 0x0($v0)
    /* 8840C 800AD05C 00000000 */  nop
    /* 88410 800AD060 1180000B */  beqz       $t4, .L800AD090
    /* 88414 800AD064 00000000 */   nop
    /* 88418 800AD068 0C01D0C7 */  jal        func_8007431C
    /* 8841C 800AD06C A7AA003E */   sh        $t2, 0x3E($sp)
    /* 88420 800AD070 3C0D8010 */  lui        $t5, %hi(D_8010395C)
    /* 88424 800AD074 8DAD395C */  lw         $t5, %lo(D_8010395C)($t5)
    /* 88428 800AD078 3C038010 */  lui        $v1, %hi(D_801033D0)
    /* 8842C 800AD07C 97AA003E */  lhu        $t2, 0x3E($sp)
    /* 88430 800AD080 846333D0 */  lh         $v1, %lo(D_801033D0)($v1)
    /* 88434 800AD084 3C018010 */  lui        $at, %hi(D_80103958)
    /* 88438 800AD088 10000012 */  b          .L800AD0D4
    /* 8843C 800AD08C AC2D3958 */   sw        $t5, %lo(D_80103958)($at)
  .L800AD090:
    /* 88440 800AD090 AFA70040 */  sw         $a3, 0x40($sp)
    /* 88444 800AD094 0C02B73C */  jal        func_800ADCF0
    /* 88448 800AD098 A7AA003E */   sh        $t2, 0x3E($sp)
    /* 8844C 800AD09C 8FA40040 */  lw         $a0, 0x40($sp)
    /* 88450 800AD0A0 3C01800E */  lui        $at, %hi(D_800E44FC)
    /* 88454 800AD0A4 A48024BA */  sh         $zero, 0x24BA($a0)
    /* 88458 800AD0A8 A4803234 */  sh         $zero, 0x3234($a0)
    /* 8845C 800AD0AC A02044FC */  sb         $zero, %lo(D_800E44FC)($at)
    /* 88460 800AD0B0 240E429A */  addiu      $t6, $zero, 0x429A
    /* 88464 800AD0B4 240F0001 */  addiu      $t7, $zero, 0x1
    /* 88468 800AD0B8 A48E2414 */  sh         $t6, 0x2414($a0)
    /* 8846C 800AD0BC 0C02B754 */  jal        func_800ADD50
    /* 88470 800AD0C0 A48F23D2 */   sh        $t7, 0x23D2($a0)
    /* 88474 800AD0C4 3C038010 */  lui        $v1, %hi(D_801033D0)
    /* 88478 800AD0C8 846333D0 */  lh         $v1, %lo(D_801033D0)($v1)
    /* 8847C 800AD0CC 97AA003E */  lhu        $t2, 0x3E($sp)
    /* 88480 800AD0D0 00000000 */  nop
  .L800AD0D4:
    /* 88484 800AD0D4 0461000B */  bgez       $v1, .L800AD104
    /* 88488 800AD0D8 97A2003A */   lhu       $v0, 0x3A($sp)
    /* 8848C 800AD0DC 97B8003A */  lhu        $t8, 0x3A($sp)
    /* 88490 800AD0E0 314B4800 */  andi       $t3, $t2, 0x4800
    /* 88494 800AD0E4 33194800 */  andi       $t9, $t8, 0x4800
    /* 88498 800AD0E8 13200006 */  beqz       $t9, .L800AD104
    /* 8849C 800AD0EC 97A2003A */   lhu       $v0, 0x3A($sp)
    /* 884A0 800AD0F0 15600004 */  bnez       $t3, .L800AD104
    /* 884A4 800AD0F4 97A2003A */   lhu       $v0, 0x3A($sp)
    /* 884A8 800AD0F8 0C01D0DD */  jal        func_80074374
    /* 884AC 800AD0FC 00000000 */   nop
    /* 884B0 800AD100 97A2003A */  lhu        $v0, 0x3A($sp)
  .L800AD104:
    /* 884B4 800AD104 100002AB */  b          .L800ADBB4
    /* 884B8 800AD108 8FBF0014 */   lw        $ra, 0x14($sp)
  .L800AD10C:
    /* 884BC 800AD10C 3C0C8010 */  lui        $t4, %hi(D_801033D0)
    /* 884C0 800AD110 858C33D0 */  lh         $t4, %lo(D_801033D0)($t4)
    /* 884C4 800AD114 97A2003A */  lhu        $v0, 0x3A($sp)
    /* 884C8 800AD118 05800003 */  bltz       $t4, .L800AD128
    /* 884CC 800AD11C 00000000 */   nop
    /* 884D0 800AD120 100002A4 */  b          .L800ADBB4
    /* 884D4 800AD124 8FBF0014 */   lw        $ra, 0x14($sp)
  .L800AD128:
    /* 884D8 800AD128 90ED1680 */  lbu        $t5, 0x1680($a3)
    /* 884DC 800AD12C 97A8003A */  lhu        $t0, 0x3A($sp)
    /* 884E0 800AD130 11A00032 */  beqz       $t5, .L800AD1FC
    /* 884E4 800AD134 310EB000 */   andi      $t6, $t0, 0xB000
    /* 884E8 800AD138 11C0000F */  beqz       $t6, .L800AD178
    /* 884EC 800AD13C 314FB000 */   andi      $t7, $t2, 0xB000
    /* 884F0 800AD140 15E0000D */  bnez       $t7, .L800AD178
    /* 884F4 800AD144 3C188014 */   lui       $t8, %hi(D_80139E64)
    /* 884F8 800AD148 93189E64 */  lbu        $t8, %lo(D_80139E64)($t8)
    /* 884FC 800AD14C 3C048011 */  lui        $a0, %hi(D_80108828)
    /* 88500 800AD150 13000005 */  beqz       $t8, .L800AD168
    /* 88504 800AD154 24848828 */   addiu     $a0, $a0, %lo(D_80108828)
    /* 88508 800AD158 0C01EB7E */  jal        func_8007ADF8
    /* 8850C 800AD15C AFA70040 */   sw        $a3, 0x40($sp)
    /* 88510 800AD160 8FA70040 */  lw         $a3, 0x40($sp)
    /* 88514 800AD164 00000000 */  nop
  .L800AD168:
    /* 88518 800AD168 24190080 */  addiu      $t9, $zero, 0x80
    /* 8851C 800AD16C A0F91688 */  sb         $t9, 0x1688($a3)
    /* 88520 800AD170 3C018014 */  lui        $at, %hi(D_80139E68)
    /* 88524 800AD174 AC209E68 */  sw         $zero, %lo(D_80139E68)($at)
  .L800AD178:
    /* 88528 800AD178 8CEB2B28 */  lw         $t3, 0x2B28($a3)
    /* 8852C 800AD17C 8CE32B40 */  lw         $v1, 0x2B40($a3)
    /* 88530 800AD180 8CF92B2C */  lw         $t9, 0x2B2C($a3)
    /* 88534 800AD184 000B6200 */  sll        $t4, $t3, 8
    /* 88538 800AD188 8CE42B44 */  lw         $a0, 0x2B44($a3)
    /* 8853C 800AD18C 01836823 */  subu       $t5, $t4, $v1
    /* 88540 800AD190 00195A00 */  sll        $t3, $t9, 8
    /* 88544 800AD194 25AE0080 */  addiu      $t6, $t5, 0x80
    /* 88548 800AD198 01646023 */  subu       $t4, $t3, $a0
    /* 8854C 800AD19C 258D0080 */  addiu      $t5, $t4, 0x80
    /* 88550 800AD1A0 05C10003 */  bgez       $t6, .L800AD1B0
    /* 88554 800AD1A4 000E7903 */   sra       $t7, $t6, 4
    /* 88558 800AD1A8 25C1000F */  addiu      $at, $t6, 0xF
    /* 8855C 800AD1AC 00017903 */  sra        $t7, $at, 4
  .L800AD1B0:
    /* 88560 800AD1B0 006FC021 */  addu       $t8, $v1, $t7
    /* 88564 800AD1B4 ACF82B40 */  sw         $t8, 0x2B40($a3)
    /* 88568 800AD1B8 8CF82B48 */  lw         $t8, 0x2B48($a3)
    /* 8856C 800AD1BC 8CEC2B4C */  lw         $t4, 0x2B4C($a3)
    /* 88570 800AD1C0 05A10003 */  bgez       $t5, .L800AD1D0
    /* 88574 800AD1C4 000D7103 */   sra       $t6, $t5, 4
    /* 88578 800AD1C8 25A1000F */  addiu      $at, $t5, 0xF
    /* 8857C 800AD1CC 00017103 */  sra        $t6, $at, 4
  .L800AD1D0:
    /* 88580 800AD1D0 008E7821 */  addu       $t7, $a0, $t6
    /* 88584 800AD1D4 0018CA03 */  sra        $t9, $t8, 8
    /* 88588 800AD1D8 000C6A03 */  sra        $t5, $t4, 8
    /* 8858C 800AD1DC 332B001F */  andi       $t3, $t9, 0x1F
    /* 88590 800AD1E0 31AE001F */  andi       $t6, $t5, 0x1F
    /* 88594 800AD1E4 ACEF2B44 */  sw         $t7, 0x2B44($a3)
    /* 88598 800AD1E8 ACEB2B18 */  sw         $t3, 0x2B18($a3)
    /* 8859C 800AD1EC ACEE2B1C */  sw         $t6, 0x2B1C($a3)
    /* 885A0 800AD1F0 97A2003A */  lhu        $v0, 0x3A($sp)
    /* 885A4 800AD1F4 1000026F */  b          .L800ADBB4
    /* 885A8 800AD1F8 8FBF0014 */   lw        $ra, 0x14($sp)
  .L800AD1FC:
    /* 885AC 800AD1FC 84EF23A2 */  lh         $t7, 0x23A2($a3)
    /* 885B0 800AD200 00000000 */  nop
    /* 885B4 800AD204 11E0012C */  beqz       $t7, .L800AD6B8
    /* 885B8 800AD208 31020200 */   andi      $v0, $t0, 0x200
    /* 885BC 800AD20C 1040001E */  beqz       $v0, .L800AD288
    /* 885C0 800AD210 00000000 */   nop
    /* 885C4 800AD214 84F82458 */  lh         $t8, 0x2458($a3)
    /* 885C8 800AD218 00000000 */  nop
    /* 885CC 800AD21C 1700001A */  bnez       $t8, .L800AD288
    /* 885D0 800AD220 00000000 */   nop
    /* 885D4 800AD224 8CF92B28 */  lw         $t9, 0x2B28($a3)
    /* 885D8 800AD228 31064000 */  andi       $a2, $t0, 0x4000
    /* 885DC 800AD22C 272B0001 */  addiu      $t3, $t9, 0x1
    /* 885E0 800AD230 10C00004 */  beqz       $a2, .L800AD244
    /* 885E4 800AD234 ACEB2B28 */   sw        $t3, 0x2B28($a3)
    /* 885E8 800AD238 84EC246C */  lh         $t4, 0x246C($a3)
    /* 885EC 800AD23C 10000004 */  b          .L800AD250
    /* 885F0 800AD240 A4EC2458 */   sh        $t4, 0x2458($a3)
  .L800AD244:
    /* 885F4 800AD244 84ED2468 */  lh         $t5, 0x2468($a3)
    /* 885F8 800AD248 00000000 */  nop
    /* 885FC 800AD24C A4ED2458 */  sh         $t5, 0x2458($a3)
  .L800AD250:
    /* 88600 800AD250 84EE245A */  lh         $t6, 0x245A($a3)
    /* 88604 800AD254 00000000 */  nop
    /* 88608 800AD258 11C00009 */  beqz       $t6, .L800AD280
    /* 8860C 800AD25C 00000000 */   nop
    /* 88610 800AD260 10C00004 */  beqz       $a2, .L800AD274
    /* 88614 800AD264 00000000 */   nop
    /* 88618 800AD268 84EF246C */  lh         $t7, 0x246C($a3)
    /* 8861C 800AD26C 10000004 */  b          .L800AD280
    /* 88620 800AD270 A4EF2458 */   sh        $t7, 0x2458($a3)
  .L800AD274:
    /* 88624 800AD274 84F8246A */  lh         $t8, 0x246A($a3)
    /* 88628 800AD278 00000000 */  nop
    /* 8862C 800AD27C A4F82458 */  sh         $t8, 0x2458($a3)
  .L800AD280:
    /* 88630 800AD280 A4E9245A */  sh         $t1, 0x245A($a3)
    /* 88634 800AD284 A7A90036 */  sh         $t1, 0x36($sp)
  .L800AD288:
    /* 88638 800AD288 10400007 */  beqz       $v0, .L800AD2A8
    /* 8863C 800AD28C 31590200 */   andi      $t9, $t2, 0x200
    /* 88640 800AD290 13200005 */  beqz       $t9, .L800AD2A8
    /* 88644 800AD294 00000000 */   nop
    /* 88648 800AD298 84EB2458 */  lh         $t3, 0x2458($a3)
    /* 8864C 800AD29C 00000000 */  nop
    /* 88650 800AD2A0 256CFFFF */  addiu      $t4, $t3, -0x1
    /* 88654 800AD2A4 A4EC2458 */  sh         $t4, 0x2458($a3)
  .L800AD2A8:
    /* 88658 800AD2A8 14400004 */  bnez       $v0, .L800AD2BC
    /* 8865C 800AD2AC 31020100 */   andi      $v0, $t0, 0x100
    /* 88660 800AD2B0 A4E02458 */  sh         $zero, 0x2458($a3)
    /* 88664 800AD2B4 A4E0245A */  sh         $zero, 0x245A($a3)
    /* 88668 800AD2B8 31020100 */  andi       $v0, $t0, 0x100
  .L800AD2BC:
    /* 8866C 800AD2BC 10400021 */  beqz       $v0, .L800AD344
    /* 88670 800AD2C0 00000000 */   nop
    /* 88674 800AD2C4 84ED245C */  lh         $t5, 0x245C($a3)
    /* 88678 800AD2C8 00000000 */  nop
    /* 8867C 800AD2CC 15A0001D */  bnez       $t5, .L800AD344
    /* 88680 800AD2D0 00000000 */   nop
    /* 88684 800AD2D4 8CEE2B28 */  lw         $t6, 0x2B28($a3)
    /* 88688 800AD2D8 31064000 */  andi       $a2, $t0, 0x4000
    /* 8868C 800AD2DC 25CFFFFF */  addiu      $t7, $t6, -0x1
    /* 88690 800AD2E0 10C00004 */  beqz       $a2, .L800AD2F4
    /* 88694 800AD2E4 ACEF2B28 */   sw        $t7, 0x2B28($a3)
    /* 88698 800AD2E8 84F8246C */  lh         $t8, 0x246C($a3)
    /* 8869C 800AD2EC 10000004 */  b          .L800AD300
    /* 886A0 800AD2F0 A4F8245C */   sh        $t8, 0x245C($a3)
  .L800AD2F4:
    /* 886A4 800AD2F4 84F92468 */  lh         $t9, 0x2468($a3)
    /* 886A8 800AD2F8 00000000 */  nop
    /* 886AC 800AD2FC A4F9245C */  sh         $t9, 0x245C($a3)
  .L800AD300:
    /* 886B0 800AD300 84EB245E */  lh         $t3, 0x245E($a3)
    /* 886B4 800AD304 00000000 */  nop
    /* 886B8 800AD308 11600009 */  beqz       $t3, .L800AD330
    /* 886BC 800AD30C 00000000 */   nop
    /* 886C0 800AD310 10C00004 */  beqz       $a2, .L800AD324
    /* 886C4 800AD314 00000000 */   nop
    /* 886C8 800AD318 84EC246C */  lh         $t4, 0x246C($a3)
    /* 886CC 800AD31C 10000004 */  b          .L800AD330
    /* 886D0 800AD320 A4EC245C */   sh        $t4, 0x245C($a3)
  .L800AD324:
    /* 886D4 800AD324 84ED246A */  lh         $t5, 0x246A($a3)
    /* 886D8 800AD328 00000000 */  nop
    /* 886DC 800AD32C A4ED245C */  sh         $t5, 0x245C($a3)
  .L800AD330:
    /* 886E0 800AD330 A4E9245E */  sh         $t1, 0x245E($a3)
    /* 886E4 800AD334 87AE0036 */  lh         $t6, 0x36($sp)
    /* 886E8 800AD338 00000000 */  nop
    /* 886EC 800AD33C 25CF0001 */  addiu      $t7, $t6, 0x1
    /* 886F0 800AD340 A7AF0036 */  sh         $t7, 0x36($sp)
  .L800AD344:
    /* 886F4 800AD344 10400007 */  beqz       $v0, .L800AD364
    /* 886F8 800AD348 31580100 */   andi      $t8, $t2, 0x100
    /* 886FC 800AD34C 13000005 */  beqz       $t8, .L800AD364
    /* 88700 800AD350 00000000 */   nop
    /* 88704 800AD354 84F9245C */  lh         $t9, 0x245C($a3)
    /* 88708 800AD358 00000000 */  nop
    /* 8870C 800AD35C 272BFFFF */  addiu      $t3, $t9, -0x1
    /* 88710 800AD360 A4EB245C */  sh         $t3, 0x245C($a3)
  .L800AD364:
    /* 88714 800AD364 14400004 */  bnez       $v0, .L800AD378
    /* 88718 800AD368 31020800 */   andi      $v0, $t0, 0x800
    /* 8871C 800AD36C A4E0245C */  sh         $zero, 0x245C($a3)
    /* 88720 800AD370 A4E0245E */  sh         $zero, 0x245E($a3)
    /* 88724 800AD374 31020800 */  andi       $v0, $t0, 0x800
  .L800AD378:
    /* 88728 800AD378 10400021 */  beqz       $v0, .L800AD400
    /* 8872C 800AD37C 00000000 */   nop
    /* 88730 800AD380 84EC2460 */  lh         $t4, 0x2460($a3)
    /* 88734 800AD384 00000000 */  nop
    /* 88738 800AD388 1580001D */  bnez       $t4, .L800AD400
    /* 8873C 800AD38C 00000000 */   nop
    /* 88740 800AD390 8CED2B2C */  lw         $t5, 0x2B2C($a3)
    /* 88744 800AD394 31064000 */  andi       $a2, $t0, 0x4000
    /* 88748 800AD398 25AE0001 */  addiu      $t6, $t5, 0x1
    /* 8874C 800AD39C 10C00004 */  beqz       $a2, .L800AD3B0
    /* 88750 800AD3A0 ACEE2B2C */   sw        $t6, 0x2B2C($a3)
    /* 88754 800AD3A4 84EF246C */  lh         $t7, 0x246C($a3)
    /* 88758 800AD3A8 10000004 */  b          .L800AD3BC
    /* 8875C 800AD3AC A4EF2460 */   sh        $t7, 0x2460($a3)
  .L800AD3B0:
    /* 88760 800AD3B0 84F82468 */  lh         $t8, 0x2468($a3)
    /* 88764 800AD3B4 00000000 */  nop
    /* 88768 800AD3B8 A4F82460 */  sh         $t8, 0x2460($a3)
  .L800AD3BC:
    /* 8876C 800AD3BC 84F92462 */  lh         $t9, 0x2462($a3)
    /* 88770 800AD3C0 00000000 */  nop
    /* 88774 800AD3C4 13200009 */  beqz       $t9, .L800AD3EC
    /* 88778 800AD3C8 00000000 */   nop
    /* 8877C 800AD3CC 10C00004 */  beqz       $a2, .L800AD3E0
    /* 88780 800AD3D0 00000000 */   nop
    /* 88784 800AD3D4 84EB246C */  lh         $t3, 0x246C($a3)
    /* 88788 800AD3D8 10000004 */  b          .L800AD3EC
    /* 8878C 800AD3DC A4EB2460 */   sh        $t3, 0x2460($a3)
  .L800AD3E0:
    /* 88790 800AD3E0 84EC246A */  lh         $t4, 0x246A($a3)
    /* 88794 800AD3E4 00000000 */  nop
    /* 88798 800AD3E8 A4EC2460 */  sh         $t4, 0x2460($a3)
  .L800AD3EC:
    /* 8879C 800AD3EC A4E92462 */  sh         $t1, 0x2462($a3)
    /* 887A0 800AD3F0 87AD0036 */  lh         $t5, 0x36($sp)
    /* 887A4 800AD3F4 00000000 */  nop
    /* 887A8 800AD3F8 25AE0001 */  addiu      $t6, $t5, 0x1
    /* 887AC 800AD3FC A7AE0036 */  sh         $t6, 0x36($sp)
  .L800AD400:
    /* 887B0 800AD400 10400007 */  beqz       $v0, .L800AD420
    /* 887B4 800AD404 314F0800 */   andi      $t7, $t2, 0x800
    /* 887B8 800AD408 11E00005 */  beqz       $t7, .L800AD420
    /* 887BC 800AD40C 00000000 */   nop
    /* 887C0 800AD410 84F82460 */  lh         $t8, 0x2460($a3)
    /* 887C4 800AD414 00000000 */  nop
    /* 887C8 800AD418 2719FFFF */  addiu      $t9, $t8, -0x1
    /* 887CC 800AD41C A4F92460 */  sh         $t9, 0x2460($a3)
  .L800AD420:
    /* 887D0 800AD420 14400004 */  bnez       $v0, .L800AD434
    /* 887D4 800AD424 31020400 */   andi      $v0, $t0, 0x400
    /* 887D8 800AD428 A4E02460 */  sh         $zero, 0x2460($a3)
    /* 887DC 800AD42C A4E02462 */  sh         $zero, 0x2462($a3)
    /* 887E0 800AD430 31020400 */  andi       $v0, $t0, 0x400
  .L800AD434:
    /* 887E4 800AD434 10400021 */  beqz       $v0, .L800AD4BC
    /* 887E8 800AD438 00000000 */   nop
    /* 887EC 800AD43C 84EB2464 */  lh         $t3, 0x2464($a3)
    /* 887F0 800AD440 00000000 */  nop
    /* 887F4 800AD444 1560001D */  bnez       $t3, .L800AD4BC
    /* 887F8 800AD448 00000000 */   nop
    /* 887FC 800AD44C 8CEC2B2C */  lw         $t4, 0x2B2C($a3)
    /* 88800 800AD450 31064000 */  andi       $a2, $t0, 0x4000
    /* 88804 800AD454 258DFFFF */  addiu      $t5, $t4, -0x1
    /* 88808 800AD458 10C00004 */  beqz       $a2, .L800AD46C
    /* 8880C 800AD45C ACED2B2C */   sw        $t5, 0x2B2C($a3)
    /* 88810 800AD460 84EE246C */  lh         $t6, 0x246C($a3)
    /* 88814 800AD464 10000004 */  b          .L800AD478
    /* 88818 800AD468 A4EE2464 */   sh        $t6, 0x2464($a3)
  .L800AD46C:
    /* 8881C 800AD46C 84EF2468 */  lh         $t7, 0x2468($a3)
    /* 88820 800AD470 00000000 */  nop
    /* 88824 800AD474 A4EF2464 */  sh         $t7, 0x2464($a3)
  .L800AD478:
    /* 88828 800AD478 84F82466 */  lh         $t8, 0x2466($a3)
    /* 8882C 800AD47C 00000000 */  nop
    /* 88830 800AD480 13000009 */  beqz       $t8, .L800AD4A8
    /* 88834 800AD484 00000000 */   nop
    /* 88838 800AD488 10C00004 */  beqz       $a2, .L800AD49C
    /* 8883C 800AD48C 00000000 */   nop
    /* 88840 800AD490 84F9246C */  lh         $t9, 0x246C($a3)
    /* 88844 800AD494 10000004 */  b          .L800AD4A8
    /* 88848 800AD498 A4F92464 */   sh        $t9, 0x2464($a3)
  .L800AD49C:
    /* 8884C 800AD49C 84EB246A */  lh         $t3, 0x246A($a3)
    /* 88850 800AD4A0 00000000 */  nop
    /* 88854 800AD4A4 A4EB2464 */  sh         $t3, 0x2464($a3)
  .L800AD4A8:
    /* 88858 800AD4A8 A4E92466 */  sh         $t1, 0x2466($a3)
    /* 8885C 800AD4AC 87AC0036 */  lh         $t4, 0x36($sp)
    /* 88860 800AD4B0 00000000 */  nop
    /* 88864 800AD4B4 258D0001 */  addiu      $t5, $t4, 0x1
    /* 88868 800AD4B8 A7AD0036 */  sh         $t5, 0x36($sp)
  .L800AD4BC:
    /* 8886C 800AD4BC 10400008 */  beqz       $v0, .L800AD4E0
    /* 88870 800AD4C0 3C19800E */   lui       $t9, %hi(D_800E44A8)
    /* 88874 800AD4C4 314E0400 */  andi       $t6, $t2, 0x400
    /* 88878 800AD4C8 11C00005 */  beqz       $t6, .L800AD4E0
    /* 8887C 800AD4CC 00000000 */   nop
    /* 88880 800AD4D0 84EF2464 */  lh         $t7, 0x2464($a3)
    /* 88884 800AD4D4 00000000 */  nop
    /* 88888 800AD4D8 25F8FFFF */  addiu      $t8, $t7, -0x1
    /* 8888C 800AD4DC A4F82464 */  sh         $t8, 0x2464($a3)
  .L800AD4E0:
    /* 88890 800AD4E0 14400003 */  bnez       $v0, .L800AD4F0
    /* 88894 800AD4E4 00000000 */   nop
    /* 88898 800AD4E8 A4E02464 */  sh         $zero, 0x2464($a3)
    /* 8889C 800AD4EC A4E02466 */  sh         $zero, 0x2466($a3)
  .L800AD4F0:
    /* 888A0 800AD4F0 873944A8 */  lh         $t9, %lo(D_800E44A8)($t9)
    /* 888A4 800AD4F4 24010004 */  addiu      $at, $zero, 0x4
    /* 888A8 800AD4F8 17210008 */  bne        $t9, $at, .L800AD51C
    /* 888AC 800AD4FC 3C028014 */   lui       $v0, %hi(D_8013DD00)
    /* 888B0 800AD500 8C42DD00 */  lw         $v0, %lo(D_8013DD00)($v0)
    /* 888B4 800AD504 00000000 */  nop
    /* 888B8 800AD508 844B25C6 */  lh         $t3, 0x25C6($v0)
    /* 888BC 800AD50C 00000000 */  nop
    /* 888C0 800AD510 15600002 */  bnez       $t3, .L800AD51C
    /* 888C4 800AD514 00000000 */   nop
    /* 888C8 800AD518 A44923AE */  sh         $t1, 0x23AE($v0)
  .L800AD51C:
    /* 888CC 800AD51C 84EC23A4 */  lh         $t4, 0x23A4($a3)
    /* 888D0 800AD520 00000000 */  nop
    /* 888D4 800AD524 11800064 */  beqz       $t4, .L800AD6B8
    /* 888D8 800AD528 00000000 */   nop
    /* 888DC 800AD52C 84ED23AE */  lh         $t5, 0x23AE($a3)
    /* 888E0 800AD530 00000000 */  nop
    /* 888E4 800AD534 15A00060 */  bnez       $t5, .L800AD6B8
    /* 888E8 800AD538 00000000 */   nop
    /* 888EC 800AD53C 84EE24B6 */  lh         $t6, 0x24B6($a3)
    /* 888F0 800AD540 3102A000 */  andi       $v0, $t0, 0xA000
    /* 888F4 800AD544 15C0005C */  bnez       $t6, .L800AD6B8
    /* 888F8 800AD548 00000000 */   nop
    /* 888FC 800AD54C 84EF2416 */  lh         $t7, 0x2416($a3)
    /* 88900 800AD550 3C01800F */  lui        $at, %hi(D_800F10B0)
    /* 88904 800AD554 448F2000 */  mtc1       $t7, $ft0
    /* 88908 800AD558 C42110B0 */  lwc1       $fv0f, %lo(D_800F10B0)($at)
    /* 8890C 800AD55C 468021A1 */  cvt.d.w    $ft1, $ft0
    /* 88910 800AD560 C42010B4 */  lwc1       $fv0, %lo(D_800F10B0 + 0x4)($at)
    /* 88914 800AD564 3158A000 */  andi       $t8, $t2, 0xA000
    /* 88918 800AD568 4620303C */  c.lt.d     $ft1, $fv0
    /* 8891C 800AD56C 00000000 */  nop
    /* 88920 800AD570 45000002 */  bc1f       .L800AD57C
    /* 88924 800AD574 00000000 */   nop
    /* 88928 800AD578 A4E023AC */  sh         $zero, 0x23AC($a3)
  .L800AD57C:
    /* 8892C 800AD57C 10400003 */  beqz       $v0, .L800AD58C
    /* 88930 800AD580 00000000 */   nop
    /* 88934 800AD584 13000009 */  beqz       $t8, .L800AD5AC
    /* 88938 800AD588 00000000 */   nop
  .L800AD58C:
    /* 8893C 800AD58C 84F92416 */  lh         $t9, 0x2416($a3)
    /* 88940 800AD590 00000000 */  nop
    /* 88944 800AD594 44994000 */  mtc1       $t9, $ft2
    /* 88948 800AD598 00000000 */  nop
    /* 8894C 800AD59C 468042A1 */  cvt.d.w    $ft3, $ft2
    /* 88950 800AD5A0 462A003E */  c.le.d     $fv0, $ft3
    /* 88954 800AD5A4 00000000 */  nop
    /* 88958 800AD5A8 45000043 */  bc1f       .L800AD6B8
  .L800AD5AC:
    /* 8895C 800AD5AC 3C0B800E */   lui       $t3, %hi(D_800DFD4C)
    /* 88960 800AD5B0 856BFD4C */  lh         $t3, %lo(D_800DFD4C)($t3)
    /* 88964 800AD5B4 24010002 */  addiu      $at, $zero, 0x2
    /* 88968 800AD5B8 15610014 */  bne        $t3, $at, .L800AD60C
    /* 8896C 800AD5BC 00000000 */   nop
    /* 88970 800AD5C0 84EC2416 */  lh         $t4, 0x2416($a3)
    /* 88974 800AD5C4 240D429A */  addiu      $t5, $zero, 0x429A
    /* 88978 800AD5C8 448C8000 */  mtc1       $t4, $ft4
    /* 8897C 800AD5CC 00E02025 */  or         $a0, $a3, $zero
    /* 88980 800AD5D0 468084A1 */  cvt.d.w    $ft5, $ft4
    /* 88984 800AD5D4 4632003E */  c.le.d     $fv0, $ft5
    /* 88988 800AD5D8 00000000 */  nop
    /* 8898C 800AD5DC 45000036 */  bc1f       .L800AD6B8
    /* 88990 800AD5E0 00000000 */   nop
    /* 88994 800AD5E4 A4ED2414 */  sh         $t5, 0x2414($a3)
    /* 88998 800AD5E8 A7AA003E */  sh         $t2, 0x3E($sp)
    /* 8899C 800AD5EC AFA80020 */  sw         $t0, 0x20($sp)
    /* 889A0 800AD5F0 0C02503C */  jal        func_800940F0
    /* 889A4 800AD5F4 AFA70040 */   sw        $a3, 0x40($sp)
    /* 889A8 800AD5F8 8FA70040 */  lw         $a3, 0x40($sp)
    /* 889AC 800AD5FC 8FA80020 */  lw         $t0, 0x20($sp)
    /* 889B0 800AD600 97AA003E */  lhu        $t2, 0x3E($sp)
    /* 889B4 800AD604 1000002C */  b          .L800AD6B8
    /* 889B8 800AD608 24090001 */   addiu     $t1, $zero, 0x1
  .L800AD60C:
    /* 889BC 800AD60C 1040000B */  beqz       $v0, .L800AD63C
    /* 889C0 800AD610 314EA000 */   andi      $t6, $t2, 0xA000
    /* 889C4 800AD614 15C0000A */  bnez       $t6, .L800AD640
    /* 889C8 800AD618 2419003C */   addiu     $t9, $zero, 0x3C
    /* 889CC 800AD61C 84EF24B6 */  lh         $t7, 0x24B6($a3)
    /* 889D0 800AD620 24185595 */  addiu      $t8, $zero, 0x5595
    /* 889D4 800AD624 15E0000B */  bnez       $t7, .L800AD654
    /* 889D8 800AD628 00000000 */   nop
    /* 889DC 800AD62C A4F824B2 */  sh         $t8, 0x24B2($a3)
    /* 889E0 800AD630 A4E024B4 */  sh         $zero, 0x24B4($a3)
    /* 889E4 800AD634 10000007 */  b          .L800AD654
    /* 889E8 800AD638 A4E023AC */   sh        $zero, 0x23AC($a3)
  .L800AD63C:
    /* 889EC 800AD63C 2419003C */  addiu      $t9, $zero, 0x3C
  .L800AD640:
    /* 889F0 800AD640 240B5595 */  addiu      $t3, $zero, 0x5595
    /* 889F4 800AD644 A4E924B6 */  sh         $t1, 0x24B6($a3)
    /* 889F8 800AD648 A4F924B8 */  sh         $t9, 0x24B8($a3)
    /* 889FC 800AD64C A4EB24B2 */  sh         $t3, 0x24B2($a3)
    /* 88A00 800AD650 A4E924B4 */  sh         $t1, 0x24B4($a3)
  .L800AD654:
    /* 88A04 800AD654 8CED2B28 */  lw         $t5, 0x2B28($a3)
    /* 88A08 800AD658 84EC2374 */  lh         $t4, 0x2374($a3)
    /* 88A0C 800AD65C 8CF82B2C */  lw         $t8, 0x2B2C($a3)
    /* 88A10 800AD660 25AE0007 */  addiu      $t6, $t5, 0x7
    /* 88A14 800AD664 84ED23AC */  lh         $t5, 0x23AC($a3)
    /* 88A18 800AD668 A4EC24AA */  sh         $t4, 0x24AA($a3)
    /* 88A1C 800AD66C 27190007 */  addiu      $t9, $t8, 0x7
    /* 88A20 800AD670 31CF001F */  andi       $t7, $t6, 0x1F
    /* 88A24 800AD674 332B001F */  andi       $t3, $t9, 0x1F
    /* 88A28 800AD678 240C0008 */  addiu      $t4, $zero, 0x8
    /* 88A2C 800AD67C A4EF24AC */  sh         $t7, 0x24AC($a3)
    /* 88A30 800AD680 A4EB24AE */  sh         $t3, 0x24AE($a3)
    /* 88A34 800AD684 A4EC24B0 */  sh         $t4, 0x24B0($a3)
    /* 88A38 800AD688 A4E92B5C */  sh         $t1, 0x2B5C($a3)
    /* 88A3C 800AD68C A4E023A4 */  sh         $zero, 0x23A4($a3)
    /* 88A40 800AD690 15A00008 */  bnez       $t5, .L800AD6B4
    /* 88A44 800AD694 A4E001E6 */   sh        $zero, 0x1E6($a3)
    /* 88A48 800AD698 3C0E800E */  lui        $t6, %hi(D_800E44A8)
    /* 88A4C 800AD69C 85CE44A8 */  lh         $t6, %lo(D_800E44A8)($t6)
    /* 88A50 800AD6A0 24010004 */  addiu      $at, $zero, 0x4
    /* 88A54 800AD6A4 11C10002 */  beq        $t6, $at, .L800AD6B0
    /* 88A58 800AD6A8 240F4EB6 */   addiu     $t7, $zero, 0x4EB6
    /* 88A5C 800AD6AC A4EF2414 */  sh         $t7, 0x2414($a3)
  .L800AD6B0:
    /* 88A60 800AD6B0 A4E924A6 */  sh         $t1, 0x24A6($a3)
  .L800AD6B4:
    /* 88A64 800AD6B4 A4E923AC */  sh         $t1, 0x23AC($a3)
  .L800AD6B8:
    /* 88A68 800AD6B8 8CF82B28 */  lw         $t8, 0x2B28($a3)
    /* 88A6C 800AD6BC 8CE32B40 */  lw         $v1, 0x2B40($a3)
    /* 88A70 800AD6C0 8CEF2B2C */  lw         $t7, 0x2B2C($a3)
    /* 88A74 800AD6C4 0018CA00 */  sll        $t9, $t8, 8
    /* 88A78 800AD6C8 8CE42B44 */  lw         $a0, 0x2B44($a3)
    /* 88A7C 800AD6CC 03235823 */  subu       $t3, $t9, $v1
    /* 88A80 800AD6D0 000FC200 */  sll        $t8, $t7, 8
    /* 88A84 800AD6D4 256C0080 */  addiu      $t4, $t3, 0x80
    /* 88A88 800AD6D8 0304C823 */  subu       $t9, $t8, $a0
    /* 88A8C 800AD6DC 272B0080 */  addiu      $t3, $t9, 0x80
    /* 88A90 800AD6E0 05810003 */  bgez       $t4, .L800AD6F0
    /* 88A94 800AD6E4 000C6903 */   sra       $t5, $t4, 4
    /* 88A98 800AD6E8 2581000F */  addiu      $at, $t4, 0xF
    /* 88A9C 800AD6EC 00016903 */  sra        $t5, $at, 4
  .L800AD6F0:
    /* 88AA0 800AD6F0 006D7021 */  addu       $t6, $v1, $t5
    /* 88AA4 800AD6F4 ACEE2B40 */  sw         $t6, 0x2B40($a3)
    /* 88AA8 800AD6F8 8CEE2B48 */  lw         $t6, 0x2B48($a3)
    /* 88AAC 800AD6FC 8CF92B4C */  lw         $t9, 0x2B4C($a3)
    /* 88AB0 800AD700 05610003 */  bgez       $t3, .L800AD710
    /* 88AB4 800AD704 000B6103 */   sra       $t4, $t3, 4
    /* 88AB8 800AD708 2561000F */  addiu      $at, $t3, 0xF
    /* 88ABC 800AD70C 00016103 */  sra        $t4, $at, 4
  .L800AD710:
    /* 88AC0 800AD710 84E224A6 */  lh         $v0, 0x24A6($a3)
    /* 88AC4 800AD714 008C6821 */  addu       $t5, $a0, $t4
    /* 88AC8 800AD718 000E7A03 */  sra        $t7, $t6, 8
    /* 88ACC 800AD71C 00195A03 */  sra        $t3, $t9, 8
    /* 88AD0 800AD720 31F8001F */  andi       $t8, $t7, 0x1F
    /* 88AD4 800AD724 316C001F */  andi       $t4, $t3, 0x1F
    /* 88AD8 800AD728 ACED2B44 */  sw         $t5, 0x2B44($a3)
    /* 88ADC 800AD72C ACF82B18 */  sw         $t8, 0x2B18($a3)
    /* 88AE0 800AD730 ACEC2B1C */  sw         $t4, 0x2B1C($a3)
    /* 88AE4 800AD734 00002825 */  or         $a1, $zero, $zero
    /* 88AE8 800AD738 14400004 */  bnez       $v0, .L800AD74C
    /* 88AEC 800AD73C 31064000 */   andi      $a2, $t0, 0x4000
    /* 88AF0 800AD740 00092C00 */  sll        $a1, $t1, 16
    /* 88AF4 800AD744 00056C03 */  sra        $t5, $a1, 16
    /* 88AF8 800AD748 01A02825 */  or         $a1, $t5, $zero
  .L800AD74C:
    /* 88AFC 800AD74C 10400008 */  beqz       $v0, .L800AD770
    /* 88B00 800AD750 00000000 */   nop
    /* 88B04 800AD754 84EE25CA */  lh         $t6, 0x25CA($a3)
    /* 88B08 800AD758 00000000 */  nop
    /* 88B0C 800AD75C 15C00004 */  bnez       $t6, .L800AD770
    /* 88B10 800AD760 00000000 */   nop
    /* 88B14 800AD764 00092C00 */  sll        $a1, $t1, 16
    /* 88B18 800AD768 00057C03 */  sra        $t7, $a1, 16
    /* 88B1C 800AD76C 01E02825 */  or         $a1, $t7, $zero
  .L800AD770:
    /* 88B20 800AD770 10A0001D */  beqz       $a1, .L800AD7E8
    /* 88B24 800AD774 3C18800E */   lui       $t8, %hi(D_800E44FC)
    /* 88B28 800AD778 931844FC */  lbu        $t8, %lo(D_800E44FC)($t8)
    /* 88B2C 800AD77C 3C198010 */  lui        $t9, %hi(D_801033D0)
    /* 88B30 800AD780 17000019 */  bnez       $t8, .L800AD7E8
    /* 88B34 800AD784 00000000 */   nop
    /* 88B38 800AD788 873933D0 */  lh         $t9, %lo(D_801033D0)($t9)
    /* 88B3C 800AD78C 00000000 */  nop
    /* 88B40 800AD790 07210015 */  bgez       $t9, .L800AD7E8
    /* 88B44 800AD794 00000000 */   nop
    /* 88B48 800AD798 84E22414 */  lh         $v0, 0x2414($a3)
    /* 88B4C 800AD79C 3C01800F */  lui        $at, %hi(D_800F10B8)
    /* 88B50 800AD7A0 44823000 */  mtc1       $v0, $ft1
    /* 88B54 800AD7A4 C42510B8 */  lwc1       $ft0f, %lo(D_800F10B8)($at)
    /* 88B58 800AD7A8 46803221 */  cvt.d.w    $ft2, $ft1
    /* 88B5C 800AD7AC C42410BC */  lwc1       $ft0, %lo(D_800F10B8 + 0x4)($at)
    /* 88B60 800AD7B0 00000000 */  nop
    /* 88B64 800AD7B4 4624403E */  c.le.d     $ft2, $ft0
    /* 88B68 800AD7B8 00000000 */  nop
    /* 88B6C 800AD7BC 4500000A */  bc1f       .L800AD7E8
    /* 88B70 800AD7C0 00000000 */   nop
    /* 88B74 800AD7C4 84EB23E0 */  lh         $t3, 0x23E0($a3)
    /* 88B78 800AD7C8 00000000 */  nop
    /* 88B7C 800AD7CC 15600006 */  bnez       $t3, .L800AD7E8
    /* 88B80 800AD7D0 00000000 */   nop
    /* 88B84 800AD7D4 8CEC2404 */  lw         $t4, 0x2404($a3)
    /* 88B88 800AD7D8 00000000 */  nop
    /* 88B8C 800AD7DC 000C6C03 */  sra        $t5, $t4, 16
    /* 88B90 800AD7E0 004D7021 */  addu       $t6, $v0, $t5
    /* 88B94 800AD7E4 A4EE2414 */  sh         $t6, 0x2414($a3)
  .L800AD7E8:
    /* 88B98 800AD7E8 84E22416 */  lh         $v0, 0x2416($a3)
    /* 88B9C 800AD7EC 84EF2414 */  lh         $t7, 0x2414($a3)
    /* 88BA0 800AD7F0 24010009 */  addiu      $at, $zero, 0x9
    /* 88BA4 800AD7F4 01E2C023 */  subu       $t8, $t7, $v0
    /* 88BA8 800AD7F8 0301001A */  div        $zero, $t8, $at
    /* 88BAC 800AD7FC A4E02B68 */  sh         $zero, 0x2B68($a3)
    /* 88BB0 800AD800 3C0D800E */  lui        $t5, %hi(D_800E44A8)
    /* 88BB4 800AD804 24010004 */  addiu      $at, $zero, 0x4
    /* 88BB8 800AD808 310E0008 */  andi       $t6, $t0, 0x8
    /* 88BBC 800AD80C 0000C812 */  mflo       $t9
    /* 88BC0 800AD810 00595821 */  addu       $t3, $v0, $t9
    /* 88BC4 800AD814 256C0001 */  addiu      $t4, $t3, 0x1
    /* 88BC8 800AD818 A4EC2416 */  sh         $t4, 0x2416($a3)
    /* 88BCC 800AD81C 85AD44A8 */  lh         $t5, %lo(D_800E44A8)($t5)
    /* 88BD0 800AD820 00000000 */  nop
    /* 88BD4 800AD824 15A1002D */  bne        $t5, $at, .L800AD8DC
    /* 88BD8 800AD828 310F0004 */   andi      $t7, $t0, 0x4
    /* 88BDC 800AD82C 11C0002A */  beqz       $t6, .L800AD8D8
    /* 88BE0 800AD830 314F0008 */   andi      $t7, $t2, 0x8
    /* 88BE4 800AD834 15E00029 */  bnez       $t7, .L800AD8DC
    /* 88BE8 800AD838 310F0004 */   andi      $t7, $t0, 0x4
    /* 88BEC 800AD83C 84F8323E */  lh         $t8, 0x323E($a3)
    /* 88BF0 800AD840 00000000 */  nop
    /* 88BF4 800AD844 17000025 */  bnez       $t8, .L800AD8DC
    /* 88BF8 800AD848 310F0004 */   andi      $t7, $t0, 0x4
    /* 88BFC 800AD84C 90F91680 */  lbu        $t9, 0x1680($a3)
    /* 88C00 800AD850 00E02025 */  or         $a0, $a3, $zero
    /* 88C04 800AD854 17200021 */  bnez       $t9, .L800AD8DC
    /* 88C08 800AD858 310F0004 */   andi      $t7, $t0, 0x4
    /* 88C0C 800AD85C AFA6001C */  sw         $a2, 0x1C($sp)
    /* 88C10 800AD860 AFA70040 */  sw         $a3, 0x40($sp)
    /* 88C14 800AD864 AFA80020 */  sw         $t0, 0x20($sp)
    /* 88C18 800AD868 0C02B711 */  jal        func_800ADC44
    /* 88C1C 800AD86C A7AA003E */   sh        $t2, 0x3E($sp)
    /* 88C20 800AD870 8FA40040 */  lw         $a0, 0x40($sp)
    /* 88C24 800AD874 0C0248A8 */  jal        func_800922A0
    /* 88C28 800AD878 00000000 */   nop
    /* 88C2C 800AD87C 8FA70040 */  lw         $a3, 0x40($sp)
    /* 88C30 800AD880 8FA6001C */  lw         $a2, 0x1C($sp)
    /* 88C34 800AD884 8FA80020 */  lw         $t0, 0x20($sp)
    /* 88C38 800AD888 24090001 */  addiu      $t1, $zero, 0x1
    /* 88C3C 800AD88C 97AA003E */  lhu        $t2, 0x3E($sp)
    /* 88C40 800AD890 3C018014 */  lui        $at, %hi(D_8013D260)
    /* 88C44 800AD894 A4E93262 */  sh         $t1, 0x3262($a3)
    /* 88C48 800AD898 A4E9323E */  sh         $t1, 0x323E($a3)
    /* 88C4C 800AD89C 3C02800E */  lui        $v0, %hi(D_800E4498)
    /* 88C50 800AD8A0 3C03800E */  lui        $v1, %hi(D_800E449C)
    /* 88C54 800AD8A4 A420D260 */  sh         $zero, %lo(D_8013D260)($at)
    /* 88C58 800AD8A8 2463449C */  addiu      $v1, $v1, %lo(D_800E449C)
    /* 88C5C 800AD8AC 24424498 */  addiu      $v0, $v0, %lo(D_800E4498)
    /* 88C60 800AD8B0 844B0000 */  lh         $t3, 0x0($v0)
    /* 88C64 800AD8B4 846D0000 */  lh         $t5, 0x0($v1)
    /* 88C68 800AD8B8 256CFFFF */  addiu      $t4, $t3, -0x1
    /* 88C6C 800AD8BC 25AEFFFF */  addiu      $t6, $t5, -0x1
    /* 88C70 800AD8C0 A44C0000 */  sh         $t4, 0x0($v0)
    /* 88C74 800AD8C4 A46E0000 */  sh         $t6, 0x0($v1)
    /* 88C78 800AD8C8 A4E923B4 */  sh         $t1, 0x23B4($a3)
    /* 88C7C 800AD8CC A4E923B6 */  sh         $t1, 0x23B6($a3)
    /* 88C80 800AD8D0 A4E024B2 */  sh         $zero, 0x24B2($a3)
    /* 88C84 800AD8D4 A4E024A6 */  sh         $zero, 0x24A6($a3)
  .L800AD8D8:
    /* 88C88 800AD8D8 310F0004 */  andi       $t7, $t0, 0x4
  .L800AD8DC:
    /* 88C8C 800AD8DC 11E00005 */  beqz       $t7, .L800AD8F4
    /* 88C90 800AD8E0 3C02800E */   lui       $v0, %hi(D_800E44A8)
    /* 88C94 800AD8E4 31580004 */  andi       $t8, $t2, 0x4
    /* 88C98 800AD8E8 17000002 */  bnez       $t8, .L800AD8F4
    /* 88C9C 800AD8EC 24190001 */   addiu     $t9, $zero, 0x1
    /* 88CA0 800AD8F0 A0F90703 */  sb         $t9, 0x703($a3)
  .L800AD8F4:
    /* 88CA4 800AD8F4 844244A8 */  lh         $v0, %lo(D_800E44A8)($v0)
    /* 88CA8 800AD8F8 24010004 */  addiu      $at, $zero, 0x4
    /* 88CAC 800AD8FC 10410004 */  beq        $v0, $at, .L800AD910
    /* 88CB0 800AD900 310B0020 */   andi      $t3, $t0, 0x20
    /* 88CB4 800AD904 24010003 */  addiu      $at, $zero, 0x3
    /* 88CB8 800AD908 14410026 */  bne        $v0, $at, .L800AD9A4
    /* 88CBC 800AD90C 00000000 */   nop
  .L800AD910:
    /* 88CC0 800AD910 11600012 */  beqz       $t3, .L800AD95C
    /* 88CC4 800AD914 310D0010 */   andi      $t5, $t0, 0x10
    /* 88CC8 800AD918 314C0020 */  andi       $t4, $t2, 0x20
    /* 88CCC 800AD91C 1580000F */  bnez       $t4, .L800AD95C
    /* 88CD0 800AD920 3C01C47A */   lui       $at, (0xC47A0000 >> 16)
    /* 88CD4 800AD924 44810000 */  mtc1       $at, $fv0
    /* 88CD8 800AD928 3C01439C */  lui        $at, (0x439C0000 >> 16)
    /* 88CDC 800AD92C 44818000 */  mtc1       $at, $ft4
    /* 88CE0 800AD930 C4EA2440 */  lwc1       $ft3, 0x2440($a3)
    /* 88CE4 800AD934 00000000 */  nop
    /* 88CE8 800AD938 46105481 */  sub.s      $ft5, $ft3, $ft4
    /* 88CEC 800AD93C E4F22440 */  swc1       $ft5, 0x2440($a3)
    /* 88CF0 800AD940 C4E62440 */  lwc1       $ft1, 0x2440($a3)
    /* 88CF4 800AD944 00000000 */  nop
    /* 88CF8 800AD948 4600303C */  c.lt.s     $ft1, $fv0
    /* 88CFC 800AD94C 00000000 */  nop
    /* 88D00 800AD950 45000002 */  bc1f       .L800AD95C
    /* 88D04 800AD954 00000000 */   nop
    /* 88D08 800AD958 E4E02440 */  swc1       $fv0, 0x2440($a3)
  .L800AD95C:
    /* 88D0C 800AD95C 11A00011 */  beqz       $t5, .L800AD9A4
    /* 88D10 800AD960 314E0010 */   andi      $t6, $t2, 0x10
    /* 88D14 800AD964 15C0000F */  bnez       $t6, .L800AD9A4
    /* 88D18 800AD968 3C01800F */   lui       $at, %hi(D_800F10C0)
    /* 88D1C 800AD96C C42010C0 */  lwc1       $fv0, %lo(D_800F10C0)($at)
    /* 88D20 800AD970 3C01439C */  lui        $at, (0x439C0000 >> 16)
    /* 88D24 800AD974 44814000 */  mtc1       $at, $ft2
    /* 88D28 800AD978 C4E42440 */  lwc1       $ft0, 0x2440($a3)
    /* 88D2C 800AD97C 00000000 */  nop
    /* 88D30 800AD980 46082280 */  add.s      $ft3, $ft0, $ft2
    /* 88D34 800AD984 E4EA2440 */  swc1       $ft3, 0x2440($a3)
    /* 88D38 800AD988 C4F02440 */  lwc1       $ft4, 0x2440($a3)
    /* 88D3C 800AD98C 00000000 */  nop
    /* 88D40 800AD990 4610003C */  c.lt.s     $fv0, $ft4
    /* 88D44 800AD994 00000000 */  nop
    /* 88D48 800AD998 45000002 */  bc1f       .L800AD9A4
    /* 88D4C 800AD99C 00000000 */   nop
    /* 88D50 800AD9A0 E4E02440 */  swc1       $fv0, 0x2440($a3)
  .L800AD9A4:
    /* 88D54 800AD9A4 10C00010 */  beqz       $a2, .L800AD9E8
    /* 88D58 800AD9A8 240F0003 */   addiu     $t7, $zero, 0x3
    /* 88D5C 800AD9AC A4E92B52 */  sh         $t1, 0x2B52($a3)
    /* 88D60 800AD9B0 A4EF2B68 */  sh         $t7, 0x2B68($a3)
    /* 88D64 800AD9B4 A4E92B5E */  sh         $t1, 0x2B5E($a3)
    /* 88D68 800AD9B8 87B80036 */  lh         $t8, 0x36($sp)
    /* 88D6C 800AD9BC 3C048011 */  lui        $a0, %hi(D_8010B358)
    /* 88D70 800AD9C0 13000016 */  beqz       $t8, .L800ADA1C
    /* 88D74 800AD9C4 2484B358 */   addiu     $a0, $a0, %lo(D_8010B358)
    /* 88D78 800AD9C8 3C05800E */  lui        $a1, %hi(D_800E2828)
    /* 88D7C 800AD9CC 24A52828 */  addiu      $a1, $a1, %lo(D_800E2828)
    /* 88D80 800AD9D0 2406001B */  addiu      $a2, $zero, 0x1B
    /* 88D84 800AD9D4 0C01F517 */  jal        func_8007D45C
    /* 88D88 800AD9D8 AFA70040 */   sw        $a3, 0x40($sp)
    /* 88D8C 800AD9DC 8FA70040 */  lw         $a3, 0x40($sp)
    /* 88D90 800AD9E0 1000000E */  b          .L800ADA1C
    /* 88D94 800AD9E4 24090001 */   addiu     $t1, $zero, 0x1
  .L800AD9E8:
    /* 88D98 800AD9E8 87B90036 */  lh         $t9, 0x36($sp)
    /* 88D9C 800AD9EC 3C048011 */  lui        $a0, %hi(D_8010B358)
    /* 88DA0 800AD9F0 13200008 */  beqz       $t9, .L800ADA14
    /* 88DA4 800AD9F4 2484B358 */   addiu     $a0, $a0, %lo(D_8010B358)
    /* 88DA8 800AD9F8 3C05800E */  lui        $a1, %hi(D_800E2828)
    /* 88DAC 800AD9FC 24A52828 */  addiu      $a1, $a1, %lo(D_800E2828)
    /* 88DB0 800ADA00 2406002C */  addiu      $a2, $zero, 0x2C
    /* 88DB4 800ADA04 0C01F517 */  jal        func_8007D45C
    /* 88DB8 800ADA08 AFA70040 */   sw        $a3, 0x40($sp)
    /* 88DBC 800ADA0C 8FA70040 */  lw         $a3, 0x40($sp)
    /* 88DC0 800ADA10 24090001 */  addiu      $t1, $zero, 0x1
  .L800ADA14:
    /* 88DC4 800ADA14 A4E02B52 */  sh         $zero, 0x2B52($a3)
    /* 88DC8 800ADA18 A4E02B54 */  sh         $zero, 0x2B54($a3)
  .L800ADA1C:
    /* 88DCC 800ADA1C 84EB2B5C */  lh         $t3, 0x2B5C($a3)
    /* 88DD0 800ADA20 00000000 */  nop
    /* 88DD4 800ADA24 11600003 */  beqz       $t3, .L800ADA34
    /* 88DD8 800ADA28 00000000 */   nop
    /* 88DDC 800ADA2C A4E02B52 */  sh         $zero, 0x2B52($a3)
    /* 88DE0 800ADA30 A4E02B54 */  sh         $zero, 0x2B54($a3)
  .L800ADA34:
    /* 88DE4 800ADA34 84E22492 */  lh         $v0, 0x2492($a3)
    /* 88DE8 800ADA38 C4E42498 */  lwc1       $ft0, 0x2498($a3)
    /* 88DEC 800ADA3C 44829000 */  mtc1       $v0, $ft5
    /* 88DF0 800ADA40 84E32494 */  lh         $v1, 0x2494($a3)
    /* 88DF4 800ADA44 468091A0 */  cvt.s.w    $ft1, $ft5
    /* 88DF8 800ADA48 44838000 */  mtc1       $v1, $ft4
    /* 88DFC 800ADA4C 94EC2480 */  lhu        $t4, 0x2480($a3)
    /* 88E00 800ADA50 46043202 */  mul.s      $ft2, $ft1, $ft0
    /* 88E04 800ADA54 C4E6249C */  lwc1       $ft1, 0x249C($a3)
    /* 88E08 800ADA58 01826821 */  addu       $t5, $t4, $v0
    /* 88E0C 800ADA5C A4ED2480 */  sh         $t5, 0x2480($a3)
    /* 88E10 800ADA60 444BF800 */  cfc1       $t3, $31
    /* 88E14 800ADA64 84E42496 */  lh         $a0, 0x2496($a3)
    /* 88E18 800ADA68 35610003 */  ori        $at, $t3, 0x3
    /* 88E1C 800ADA6C 38210002 */  xori       $at, $at, 0x2
    /* 88E20 800ADA70 44C1F800 */  ctc1       $at, $31
    /* 88E24 800ADA74 94EE2482 */  lhu        $t6, 0x2482($a3)
    /* 88E28 800ADA78 460042A4 */  cvt.w.s    $ft3, $ft2
    /* 88E2C 800ADA7C 01C37821 */  addu       $t7, $t6, $v1
    /* 88E30 800ADA80 44CBF800 */  ctc1       $t3, $31
    /* 88E34 800ADA84 440C5000 */  mfc1       $t4, $ft3
    /* 88E38 800ADA88 468084A0 */  cvt.s.w    $ft5, $ft4
    /* 88E3C 800ADA8C 44845000 */  mtc1       $a0, $ft3
    /* 88E40 800ADA90 A4EF2482 */  sh         $t7, 0x2482($a3)
    /* 88E44 800ADA94 46069102 */  mul.s      $ft0, $ft5, $ft1
    /* 88E48 800ADA98 C4F224A0 */  lwc1       $ft5, 0x24A0($a3)
    /* 88E4C 800ADA9C 94F82484 */  lhu        $t8, 0x2484($a3)
    /* 88E50 800ADAA0 84E52486 */  lh         $a1, 0x2486($a3)
    /* 88E54 800ADAA4 444DF800 */  cfc1       $t5, $31
    /* 88E58 800ADAA8 0304C821 */  addu       $t9, $t8, $a0
    /* 88E5C 800ADAAC 35A10003 */  ori        $at, $t5, 0x3
    /* 88E60 800ADAB0 38210002 */  xori       $at, $at, 0x2
    /* 88E64 800ADAB4 44C1F800 */  ctc1       $at, $31
    /* 88E68 800ADAB8 A4F92484 */  sh         $t9, 0x2484($a3)
    /* 88E6C 800ADABC 46002224 */  cvt.w.s    $ft2, $ft0
    /* 88E70 800ADAC0 A4EC2492 */  sh         $t4, 0x2492($a3)
    /* 88E74 800ADAC4 44CDF800 */  ctc1       $t5, $31
    /* 88E78 800ADAC8 440E4000 */  mfc1       $t6, $ft2
    /* 88E7C 800ADACC 46805420 */  cvt.s.w    $ft4, $ft3
    /* 88E80 800ADAD0 24B9FFE0 */  addiu      $t9, $a1, -0x20
    /* 88E84 800ADAD4 A4EE2494 */  sh         $t6, 0x2494($a3)
    /* 88E88 800ADAD8 46128182 */  mul.s      $ft1, $ft4, $ft5
    /* 88E8C 800ADADC 444FF800 */  cfc1       $t7, $31
    /* 88E90 800ADAE0 00000000 */  nop
    /* 88E94 800ADAE4 35E10003 */  ori        $at, $t7, 0x3
    /* 88E98 800ADAE8 38210002 */  xori       $at, $at, 0x2
    /* 88E9C 800ADAEC 44C1F800 */  ctc1       $at, $31
    /* 88EA0 800ADAF0 28A10021 */  slti       $at, $a1, 0x21
    /* 88EA4 800ADAF4 46003124 */  cvt.w.s    $ft0, $ft1
    /* 88EA8 800ADAF8 44182000 */  mfc1       $t8, $ft0
    /* 88EAC 800ADAFC 44CFF800 */  ctc1       $t7, $31
    /* 88EB0 800ADB00 14200002 */  bnez       $at, .L800ADB0C
    /* 88EB4 800ADB04 A4F82496 */   sh        $t8, 0x2496($a3)
    /* 88EB8 800ADB08 A4F92486 */  sh         $t9, 0x2486($a3)
  .L800ADB0C:
    /* 88EBC 800ADB0C 84E22488 */  lh         $v0, 0x2488($a3)
    /* 88EC0 800ADB10 00000000 */  nop
    /* 88EC4 800ADB14 28410021 */  slti       $at, $v0, 0x21
    /* 88EC8 800ADB18 14200002 */  bnez       $at, .L800ADB24
    /* 88ECC 800ADB1C 244BFFE0 */   addiu     $t3, $v0, -0x20
    /* 88ED0 800ADB20 A4EB2488 */  sh         $t3, 0x2488($a3)
  .L800ADB24:
    /* 88ED4 800ADB24 84E2248A */  lh         $v0, 0x248A($a3)
    /* 88ED8 800ADB28 00000000 */  nop
    /* 88EDC 800ADB2C 28410021 */  slti       $at, $v0, 0x21
    /* 88EE0 800ADB30 14200002 */  bnez       $at, .L800ADB3C
    /* 88EE4 800ADB34 244CFFE0 */   addiu     $t4, $v0, -0x20
    /* 88EE8 800ADB38 A4EC248A */  sh         $t4, 0x248A($a3)
  .L800ADB3C:
    /* 88EEC 800ADB3C 84ED2486 */  lh         $t5, 0x2486($a3)
    /* 88EF0 800ADB40 00000000 */  nop
    /* 88EF4 800ADB44 29A10021 */  slti       $at, $t5, 0x21
    /* 88EF8 800ADB48 10200010 */  beqz       $at, .L800ADB8C
    /* 88EFC 800ADB4C 00000000 */   nop
    /* 88F00 800ADB50 84EE2488 */  lh         $t6, 0x2488($a3)
    /* 88F04 800ADB54 00000000 */  nop
    /* 88F08 800ADB58 29C10021 */  slti       $at, $t6, 0x21
    /* 88F0C 800ADB5C 1020000B */  beqz       $at, .L800ADB8C
    /* 88F10 800ADB60 00000000 */   nop
    /* 88F14 800ADB64 84EF248A */  lh         $t7, 0x248A($a3)
    /* 88F18 800ADB68 00000000 */  nop
    /* 88F1C 800ADB6C 29E10021 */  slti       $at, $t7, 0x21
    /* 88F20 800ADB70 10200006 */  beqz       $at, .L800ADB8C
    /* 88F24 800ADB74 00000000 */   nop
    /* 88F28 800ADB78 A4E02476 */  sh         $zero, 0x2476($a3)
    /* 88F2C 800ADB7C A4E02486 */  sh         $zero, 0x2486($a3)
    /* 88F30 800ADB80 A4E02488 */  sh         $zero, 0x2488($a3)
    /* 88F34 800ADB84 10000002 */  b          .L800ADB90
    /* 88F38 800ADB88 A4E0248A */   sh        $zero, 0x248A($a3)
  .L800ADB8C:
    /* 88F3C 800ADB8C A4E92476 */  sh         $t1, 0x2476($a3)
  .L800ADB90:
    /* 88F40 800ADB90 84F82478 */  lh         $t8, 0x2478($a3)
    /* 88F44 800ADB94 84F92476 */  lh         $t9, 0x2476($a3)
    /* 88F48 800ADB98 00000000 */  nop
    /* 88F4C 800ADB9C 03195825 */  or         $t3, $t8, $t9
    /* 88F50 800ADBA0 0C03465C */  jal        osWritebackDCacheAll
    /* 88F54 800ADBA4 A4EB2478 */   sh        $t3, 0x2478($a3)
    /* 88F58 800ADBA8 97A2003A */  lhu        $v0, 0x3A($sp)
    /* 88F5C 800ADBAC 00000000 */  nop
    /* 88F60 800ADBB0 8FBF0014 */  lw         $ra, 0x14($sp)
  .L800ADBB4:
    /* 88F64 800ADBB4 27BD0038 */  addiu      $sp, $sp, 0x38
    /* 88F68 800ADBB8 03E00008 */  jr         $ra
    /* 88F6C 800ADBBC 00000000 */   nop
